### ISSUE TITLE
BUG: Unable to resolve type URL /palomachain.paloma.paloma.MsgAddStatusUpdate: tx parse error 

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#1006]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

ERROR: **failed to send paloma status update**

**Logs from TRGC:**
time="2023-10-09T09:11:10Z" level=warning msg="no consensus reached" chain-reference-id=eth-main message-id=152290 message-type="types.Message_SubmitLogicCall" msg-id=152290 queue-name=evm/eth-main/evm-turnstone-message queue-type-name=evm/eth-main/evm-turnstone-message x-correlation-id=ckhs7b4bbloc773f8rqg

time="2023-10-09T09:11:11Z" level=error msg="failed to send paloma status update" chain-reference-id=eth-main error="unable to resolve type URL /palomachain.paloma.paloma.MsgAddStatusUpdate: tx parse error [cosmos/cosmos-sdk@v0.47.4/x/auth/tx/decoder.go:42]" message-id=152290 message-type="types.Message_SubmitLogicCall" msg-id=152290 queue-name=evm/eth-main/evm-turnstone-message queue-type-name=evm/eth-main/evm-turnstone-message x-correlation-id=ckhs7b4bbloc773f8rqg

time="2023-10-09T09:11:11Z" level=error msg="couldn't get events" action=handle-gravity-batch-send-events chain-reference-id=eth-main error="end (18311934) < begin (18311935)" x-correlation-id=ckhs7bkbbloc773f8rs0

time="2023-10-09T09:11:11Z" level=error msg="error returned in process loop" err="end (18311934) < begin (18311935)"

time="2023-10-09T09:11:12Z" level=error msg="Error while trying to keep pigeon alive." error="rpc error: code = Unknown desc = rpc error: code = Unknown desc = account sequence mismatch, expected 400349, got 400345: incorrect account sequence [cosmos/cosmos-sdk@v0.47.4/x/auth/ante/sigverify.go:269] With gas wanted: '18446744073709551615' and gas used: '15041' : unknown request" x-correlation-id=ckhs76sbbloc773f8rcg

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

Paloma v1.9.0
Pigeon v1.9.1

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Validators restart and are jailed.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Okay, so this appears to be a Cosmos encoding and decoding issue around `/palomachain.paloma.paloma.MsgAddStatusUpdate` and we'll need to fix so that the Statusupdates have resolveable URLs.

**Comment by tan-yotsombat** [comment]
paloma v1.9.0
pigeon v1.9.1
pigeon error logs https://gist.github.com/tan-yotsombat/44ef16d174bc35aeac42ef7c7d196fa4

**Comment by taariq** [comment]
Checking Cosmos-SDK for possible issues: https://github.com/cosmos/cosmos-sdk/issues/10949

**Comment by taariq** [comment]
Yeup. Cosmos is unable do decode the message for the tx `/palomachain.paloma.paloma.MsgAddStatusUpdate`. @byte-bandit I guess we need a a fix for this in pigeon.

**Comment by byte-bandit** [comment]
So, the most important thing is, this error is causing a lot of noise, but it shouldn't be concerning. It simply reduces our observability into what's going on with Pigeons. Not ideal, but not blocking operations.

With that out of the way, it's worth noting that this behaviour started showing with the release of `1.9.0`, but the feature was released in `1.8.2` without any incidents being reported, which leads me to think that some change between those versions caused a regression.

Another interesting detail: we're still receiving this message on Paloma and process it successfully, there are hundreds of log entries for the past 24h from different pigeons. So, the message **does work**, just not always, even though the error reads very deterministic.

Will keep digging.

**Comment by taariq** [comment]
Closing as fixed
