### ISSUE TITLE
Error paloma 

### ISSUE THREAD

**Issue by ERNcrypto** [palomachain/paloma#1007]
Paloma version 1.9.0, pigeon version 1.9.1, I run the node using snapshot but I keep getting an error
Started Paloma Node.
palomad.service: Main process exited, code=killed, status=9/KILL
palomad.service: Failed with result 'signal'.

sudo apt update
sudo apt install -y curl git jq lz4 build-essential unzip

bash <(curl -s "https://raw.githubusercontent.com/nodejumper-org/cosmos-scripts/master/utils/go_install.sh")
source .bash_profile

curl -L https://github.com/CosmWasm/wasmvm/releases/download/v1.4.0/libwasmvm.x86_64.so > libwasmvm.x86_64.so
sudo mv -f libwasmvm.x86_64.so /usr/lib/libwasmvm.x86_64.so

git clone https://github.com/palomachain/paloma.git
cd paloma
git checkout v1.9.0
make build
sudo mv ./build/palomad /usr/local/bin/palomad

NODE_MONIKER="ERN"
palomad config chain-id messenger
palomad init "$NODE_MONIKER" --chain-id messenger

wget -O ~/.paloma/config/genesis.json https://raw.githubusercontent.com/palomachain/mainnet/master/messenger/genesis.json
wget -O ~/.paloma/config/addrbook.json https://raw.githubusercontent.com/palomachain/mainnet/master/messenger/addrbook.json

curl https://snapshots.nodejumper.io/paloma/paloma_latest.tar.lz4 | lz4 -dc - | tar -xf - -C $HOME/.paloma

palomad start

**Comment by byte-bandit** [comment]
I can see you're using `v1.4.0` for your setup. The `README` actually still lists this, but we've rolled back to `1.3.0`. I'm not convinced this is connected, but can you try falling changing your local lib to `1.3.0` again. Also make sure to clear the cache as instructed on the README.

**Comment by taariq** [comment]
Closing as fixed.
