### ISSUE TITLE
Valset, smart contract execution and generic signature verification

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#104]
https://www.notion.so/volumefi/EPIC-05-13-Turnstone-Valset-and-generic-signature-verification-878763f01506450db99500172e8d19f8

# Background

We need to have a generic way to process incoming messages that have reached consensus and process them. Right now we only support two types of messages which are: `update_valset` & `execute_smart_contract`.

# Done when

- https://github.com/palomachain/turnstone/pull/4
- https://github.com/palomachain/turnstone/pull/7

# Please break this down into multiple smaller PRs

**Comment by measure-fi** [comment]
Execution moved to https://github.com/palomachain/paloma/issues/111
