### ISSUE TITLE
Node performance problem

### ISSUE THREAD

**Issue by mesahin001** [palomachain/paloma#1049]
Hi, my node performing not well. It is missing to validate some blocks. Here are the logs from paloma and pigeon:

root@vmd107513:~# sudo journalctl -u palomad --since "1 day ago" | grep error
Dec 01 21:13:43 vmd107513.contaboserver.net palomad[543697]: 9:13PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:15:19 vmd107513.contaboserver.net palomad[543697]: 9:15PM ERR Stopping peer for error err="write tcp 149.102.156.223:44532->95.217.229.18:10656: write: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:16:13 vmd107513.contaboserver.net palomad[543697]: 9:16PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:17:04 vmd107513.contaboserver.net palomad[543697]: 9:17PM ERR Stopping peer for error err="read tcp 149.102.156.223:45134->95.217.229.18:10656: read: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:18:13 vmd107513.contaboserver.net palomad[543697]: 9:18PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:18:49 vmd107513.contaboserver.net palomad[543697]: 9:18PM ERR Stopping peer for error err="write tcp 149.102.156.223:59382->95.217.229.18:10656: write: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:20:13 vmd107513.contaboserver.net palomad[543697]: 9:20PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:20:34 vmd107513.contaboserver.net palomad[543697]: 9:20PM ERR Stopping peer for error err="write tcp 149.102.156.223:59088->95.217.229.18:10656: write: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:22:19 vmd107513.contaboserver.net palomad[543697]: 9:22PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:22:43 vmd107513.contaboserver.net palomad[543697]: 9:22PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:24:04 vmd107513.contaboserver.net palomad[543697]: 9:24PM ERR Stopping peer for error err="write tcp 149.102.156.223:54020->95.217.229.18:10656: write: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:24:28 vmd107513.contaboserver.net palomad[543697]: 9:24PM ERR Stopping peer for error err="write tcp 149.102.156.223:26656->65.109.106.211:48434: write: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:24:43 vmd107513.contaboserver.net palomad[543697]: 9:24PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:25:16 vmd107513.contaboserver.net palomad[543697]: 9:25PM ERR Stopping peer for error err="write tcp 149.102.156.223:26656->138.201.32.103:55634: write: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:25:49 vmd107513.contaboserver.net palomad[543697]: 9:25PM ERR Stopping peer for error err="read tcp 149.102.156.223:54682->95.217.229.18:10656: read: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:26:43 vmd107513.contaboserver.net palomad[543697]: 9:26PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:27:16 vmd107513.contaboserver.net palomad[543697]: 9:27PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:27:35 vmd107513.contaboserver.net palomad[543697]: 9:27PM ERR Stopping peer for error err="read tcp 149.102.156.223:52200->95.217.229.18:10656: read: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:29:13 vmd107513.contaboserver.net palomad[543697]: 9:29PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:29:20 vmd107513.contaboserver.net palomad[543697]: 9:29PM ERR Stopping peer for error err="write tcp 149.102.156.223:57450->95.217.229.18:10656: write: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:31:05 vmd107513.contaboserver.net palomad[543697]: 9:31PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:31:13 vmd107513.contaboserver.net palomad[543697]: 9:31PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:32:50 vmd107513.contaboserver.net palomad[543697]: 9:32PM ERR Stopping peer for error err="write tcp 149.102.156.223:52146->95.217.229.18:10656: write: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:33:13 vmd107513.contaboserver.net palomad[543697]: 9:33PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:34:35 vmd107513.contaboserver.net palomad[543697]: 9:34PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:35:43 vmd107513.contaboserver.net palomad[543697]: 9:35PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:36:20 vmd107513.contaboserver.net palomad[543697]: 9:36PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:37:43 vmd107513.contaboserver.net palomad[543697]: 9:37PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:37:58 vmd107513.contaboserver.net palomad[543697]: 9:37PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:38:05 vmd107513.contaboserver.net palomad[543697]: 9:38PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:38:16 vmd107513.contaboserver.net palomad[543697]: 9:38PM ERR Stopping peer for error err="write tcp 149.102.156.223:26656->138.201.32.103:55638: write: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:39:51 vmd107513.contaboserver.net palomad[543697]: 9:39PM ERR Stopping peer for error err="write tcp 149.102.156.223:56444->95.217.229.18:10656: write: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:40:13 vmd107513.contaboserver.net palomad[543697]: 9:40PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:41:36 vmd107513.contaboserver.net palomad[543697]: 9:41PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:42:43 vmd107513.contaboserver.net palomad[543697]: 9:42PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:43:21 vmd107513.contaboserver.net palomad[543697]: 9:43PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:44:43 vmd107513.contaboserver.net palomad[543697]: 9:44PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:45:06 vmd107513.contaboserver.net palomad[543697]: 9:45PM ERR Stopping peer for error err="write tcp 149.102.156.223:43286->95.217.229.18:10656: write: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:46:28 vmd107513.contaboserver.net palomad[543697]: 9:46PM ERR Stopping peer for error err="write tcp 149.102.156.223:26656->65.109.106.211:46764: write: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:46:51 vmd107513.contaboserver.net palomad[543697]: 9:46PM ERR Stopping peer for error err="write tcp 149.102.156.223:40990->95.217.229.18:10656: write: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:47:13 vmd107513.contaboserver.net palomad[543697]: 9:47PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:48:16 vmd107513.contaboserver.net palomad[543697]: 9:48PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:48:36 vmd107513.contaboserver.net palomad[543697]: 9:48PM ERR Stopping peer for error err="read tcp 149.102.156.223:34936->95.217.229.18:10656: read: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:49:13 vmd107513.contaboserver.net palomad[543697]: 9:49PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:50:21 vmd107513.contaboserver.net palomad[543697]: 9:50PM ERR Stopping peer for error err="write tcp 149.102.156.223:43410->95.217.229.18:10656: write: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:51:13 vmd107513.contaboserver.net palomad[543697]: 9:51PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:52:06 vmd107513.contaboserver.net palomad[543697]: 9:52PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:53:43 vmd107513.contaboserver.net palomad[543697]: 9:53PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:53:52 vmd107513.contaboserver.net palomad[543697]: 9:53PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:55:37 vmd107513.contaboserver.net palomad[543697]: 9:55PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:56:13 vmd107513.contaboserver.net palomad[543697]: 9:56PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:57:22 vmd107513.contaboserver.net palomad[543697]: 9:57PM ERR Stopping peer for error err="write tcp 149.102.156.223:48852->95.217.229.18:10656: write: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:58:13 vmd107513.contaboserver.net palomad[543697]: 9:58PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 21:59:07 vmd107513.contaboserver.net palomad[543697]: 9:59PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 22:00:13 vmd107513.contaboserver.net palomad[543697]: 10:00PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 22:00:52 vmd107513.contaboserver.net palomad[543697]: 10:00PM ERR Stopping peer for error err="write tcp 149.102.156.223:39298->95.217.229.18:10656: write: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 22:01:16 vmd107513.contaboserver.net palomad[543697]: 10:01PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 22:02:37 vmd107513.contaboserver.net palomad[543697]: 10:02PM ERR Stopping peer for error err="write tcp 149.102.156.223:37154->95.217.229.18:10656: write: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 22:02:43 vmd107513.contaboserver.net palomad[543697]: 10:02PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 22:04:22 vmd107513.contaboserver.net palomad[543697]: 10:04PM ERR Stopping peer for error err="write tcp 149.102.156.223:44744->95.217.229.18:10656: write: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 22:04:43 vmd107513.contaboserver.net palomad[543697]: 10:04PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 22:06:07 vmd107513.contaboserver.net palomad[543697]: 10:06PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 22:07:13 vmd107513.contaboserver.net palomad[543697]: 10:07PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 22:07:53 vmd107513.contaboserver.net palomad[543697]: 10:07PM ERR Stopping peer for error err="write tcp 149.102.156.223:37576->95.217.229.18:10656: write: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 22:09:13 vmd107513.contaboserver.net palomad[543697]: 10:09PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 22:09:38 vmd107513.contaboserver.net palomad[543697]: 10:09PM ERR Stopping peer for error err="write tcp 149.102.156.223:54028->95.217.229.18:10656: write: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 22:11:23 vmd107513.contaboserver.net palomad[543697]: 10:11PM ERR Stopping peer for error err="write tcp 149.102.156.223:58616->95.217.229.18:10656: write: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 22:11:43 vmd107513.contaboserver.net palomad[543697]: 10:11PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 22:12:16 vmd107513.contaboserver.net palomad[543697]: 10:12PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 22:13:08 vmd107513.contaboserver.net palomad[543697]: 10:13PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 22:13:43 vmd107513.contaboserver.net palomad[543697]: 10:13PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
Dec 01 22:14:53 vmd107513.contaboserver.net palomad[543697]: 10:14PM ERR Stopping peer for error err="write tcp 149.102.156.223:46214->95.217.229.18:10656: write: connection reset by peer" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
root@vmd107513:~#

root@vmd107513:~# sudo journalctl -u pigeond --since "1 day ago" | grep error

Dec 01 22:15:18 vmd107513.contaboserver.net pigeon[543689]: {"action":"handle-gravity-batch-send-events","chain-reference-id":"base-main","error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15881,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"couldn't get events","time":"2023-12-01T22:15:18Z","x-correlation-id":"cll5ltmuohroghfhivq0"}
Dec 01 22:15:18 vmd107513.contaboserver.net pigeon[543689]: {"error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15881,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"error returned in process loop","time":"2023-12-01T22:15:18Z","x-correlation-id":"cll5ltmuohroghfhivq0"}
Dec 01 22:15:18 vmd107513.contaboserver.net pigeon[543689]: {"action":"handle-gravity-send-to-paloma-events","chain-reference-id":"base-main","error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15883,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"couldn't get events","time":"2023-12-01T22:15:18Z","x-correlation-id":"cll5ltmuohroghfhivmg"}
Dec 01 22:15:18 vmd107513.contaboserver.net pigeon[543689]: {"error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15883,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"error returned in process loop","time":"2023-12-01T22:15:18Z","x-correlation-id":"cll5ltmuohroghfhivmg"}
Dec 01 22:15:23 vmd107513.contaboserver.net pigeon[543689]: {"action":"handle-gravity-batch-send-events","chain-reference-id":"base-main","error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15885,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"couldn't get events","time":"2023-12-01T22:15:23Z","x-correlation-id":"cll5luuuohroghfhj08g"}
Dec 01 22:15:23 vmd107513.contaboserver.net pigeon[543689]: {"error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15885,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"error returned in process loop","time":"2023-12-01T22:15:23Z","x-correlation-id":"cll5luuuohroghfhj08g"}
Dec 01 22:15:29 vmd107513.contaboserver.net pigeon[543689]: {"action":"handle-gravity-batch-send-events","chain-reference-id":"base-main","error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15887,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"couldn't get events","time":"2023-12-01T22:15:29Z","x-correlation-id":"cll5m06uohroghfhj0lg"}
Dec 01 22:15:29 vmd107513.contaboserver.net pigeon[543689]: {"error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15887,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"error returned in process loop","time":"2023-12-01T22:15:29Z","x-correlation-id":"cll5m06uohroghfhj0lg"}
Dec 01 22:15:33 vmd107513.contaboserver.net pigeon[543689]: {"action":"handle-gravity-batch-send-events","chain-reference-id":"base-main","error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15889,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"couldn't get events","time":"2023-12-01T22:15:33Z","x-correlation-id":"cll5m1euohroghfhj160"}
Dec 01 22:15:33 vmd107513.contaboserver.net pigeon[543689]: {"error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15889,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"error returned in process loop","time":"2023-12-01T22:15:33Z","x-correlation-id":"cll5m1euohroghfhj160"}
Dec 01 22:15:38 vmd107513.contaboserver.net pigeon[543689]: {"action":"handle-gravity-batch-send-events","chain-reference-id":"base-main","error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15891,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"couldn't get events","time":"2023-12-01T22:15:38Z","x-correlation-id":"cll5m2muohroghfhj1n0"}
Dec 01 22:15:38 vmd107513.contaboserver.net pigeon[543689]: {"error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15891,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"error returned in process loop","time":"2023-12-01T22:15:38Z","x-correlation-id":"cll5m2muohroghfhj1n0"}
Dec 01 22:15:45 vmd107513.contaboserver.net pigeon[543689]: {"action":"handle-gravity-batch-send-events","chain-reference-id":"base-main","error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15893,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"couldn't get events","time":"2023-12-01T22:15:45Z","x-correlation-id":"cll5m3uuohroghfhj28g"}
Dec 01 22:15:45 vmd107513.contaboserver.net pigeon[543689]: {"error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15893,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"error returned in process loop","time":"2023-12-01T22:15:45Z","x-correlation-id":"cll5m3uuohroghfhj28g"}
Dec 01 22:15:48 vmd107513.contaboserver.net pigeon[543689]: {"action":"handle-gravity-batch-send-events","chain-reference-id":"base-main","error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15895,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"couldn't get events","time":"2023-12-01T22:15:48Z","x-correlation-id":"cll5m56uohroghfhj2lg"}
Dec 01 22:15:48 vmd107513.contaboserver.net pigeon[543689]: {"error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15895,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"error returned in process loop","time":"2023-12-01T22:15:48Z","x-correlation-id":"cll5m56uohroghfhj2lg"}
Dec 01 22:15:53 vmd107513.contaboserver.net pigeon[543689]: {"component":"cache","error":null,"estimatedBlockSpeed":1665000000,"lastAliveUntil":8721734,"lastBlockHeight":8720936,"lastRefresh":"2023-12-01T22:15:53.398233917Z","level":"debug","msg":"cache refreshed","time":"2023-12-01T22:15:53Z","x-correlation-id":"cll5m6euohroghfhj3ag"}
Dec 01 22:15:53 vmd107513.contaboserver.net pigeon[543689]: {"action":"handle-gravity-batch-send-events","chain-reference-id":"base-main","error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15897,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"couldn't get events","time":"2023-12-01T22:15:53Z","x-correlation-id":"cll5m6euohroghfhj370"}
Dec 01 22:15:53 vmd107513.contaboserver.net pigeon[543689]: {"error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15897,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"error returned in process loop","time":"2023-12-01T22:15:53Z","x-correlation-id":"cll5m6euohroghfhj370"}
Dec 01 22:16:00 vmd107513.contaboserver.net pigeon[543689]: {"action":"handle-gravity-batch-send-events","chain-reference-id":"base-main","error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15899,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"couldn't get events","time":"2023-12-01T22:16:00Z","x-correlation-id":"cll5m7muohroghfhj3og"}
Dec 01 22:16:00 vmd107513.contaboserver.net pigeon[543689]: {"error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15899,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"error returned in process loop","time":"2023-12-01T22:16:00Z","x-correlation-id":"cll5m7muohroghfhj3og"}
Dec 01 22:16:03 vmd107513.contaboserver.net pigeon[543689]: {"action":"handle-gravity-batch-send-events","chain-reference-id":"base-main","error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15901,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"couldn't get events","time":"2023-12-01T22:16:03Z","x-correlation-id":"cll5m8uuohroghfhj47g"}
Dec 01 22:16:03 vmd107513.contaboserver.net pigeon[543689]: {"error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15901,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"error returned in process loop","time":"2023-12-01T22:16:03Z","x-correlation-id":"cll5m8uuohroghfhj47g"}
Dec 01 22:16:08 vmd107513.contaboserver.net pigeon[543689]: {"action":"handle-gravity-batch-send-events","chain-reference-id":"base-main","error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15903,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"couldn't get events","time":"2023-12-01T22:16:08Z","x-correlation-id":"cll5ma6uohroghfhj4og"}
Dec 01 22:16:08 vmd107513.contaboserver.net pigeon[543689]: {"error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15903,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"error returned in process loop","time":"2023-12-01T22:16:08Z","x-correlation-id":"cll5ma6uohroghfhj4og"}
Dec 01 22:16:13 vmd107513.contaboserver.net pigeon[543689]: {"action":"handle-gravity-batch-send-events","chain-reference-id":"base-main","error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15905,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"couldn't get events","time":"2023-12-01T22:16:13Z","x-correlation-id":"cll5mbeuohroghfhj5a0"}
Dec 01 22:16:13 vmd107513.contaboserver.net pigeon[543689]: {"error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15905,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"error returned in process loop","time":"2023-12-01T22:16:13Z","x-correlation-id":"cll5mbeuohroghfhj5a0"}
Dec 01 22:16:18 vmd107513.contaboserver.net pigeon[543689]: {"action":"handle-gravity-send-to-paloma-events","chain-reference-id":"base-main","error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15907,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"couldn't get events","time":"2023-12-01T22:16:18Z","x-correlation-id":"cll5mcmuohroghfhj5n0"}
Dec 01 22:16:18 vmd107513.contaboserver.net pigeon[543689]: {"error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15907,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"error returned in process loop","time":"2023-12-01T22:16:18Z","x-correlation-id":"cll5mcmuohroghfhj5n0"}
Dec 01 22:16:18 vmd107513.contaboserver.net pigeon[543689]: {"action":"handle-gravity-batch-send-events","chain-reference-id":"base-main","error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15909,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"couldn't get events","time":"2023-12-01T22:16:18Z","x-correlation-id":"cll5mcmuohroghfhj5r0"}
Dec 01 22:16:18 vmd107513.contaboserver.net pigeon[543689]: {"error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15909,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"error returned in process loop","time":"2023-12-01T22:16:18Z","x-correlation-id":"cll5mcmuohroghfhj5r0"}
Dec 01 22:16:23 vmd107513.contaboserver.net pigeon[543689]: {"action":"handle-gravity-batch-send-events","chain-reference-id":"base-main","error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15911,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"couldn't get events","time":"2023-12-01T22:16:23Z","x-correlation-id":"cll5mduuohroghfhj69g"}
Dec 01 22:16:23 vmd107513.contaboserver.net pigeon[543689]: {"error":"413 Request Entity Too Large: {\"jsonrpc\":\"2.0\",\"id\":15911,\"error\":{\"code\":-32602,\"message\":\"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range\"}}","level":"error","msg":"error returned in process loop","time":"2023-12-01T22:16:23Z","x-correlation-id":"cll5mduuohroghfhj69g"}

**Comment by taariq** [comment]
Your RPC provider is rate limiting you.

`"message":"getMultipleAccounts, eth_getLogs, and eth_newFilter are limited to a 5 range"}}","level":"error","msg":"error returned in process loop","time":"2023-12-01T22:15:23Z","x-correlation-id":"cll5luuuohroghfhj08g"}`

This is not a Paloma issue. This is RPC provider. You'll need to find a node provider to suppport Paloma. Please check Nodies as offered to the community here: https://forum.palomachain.com/t/nodies-dlb-highly-performant-affordable-rpc-services/472
