### ISSUE TITLE
reason: 'not supporting these external chains: [evm, arbitrum-main]'

### ISSUE THREAD

**Issue by secard51** [palomachain/paloma#1061]
Hello, after the update, I am faced with the error reason: 'not supporting these external chains: [evm, arbitrum-main]'. I made the config settings as you specified. I get out of jail for a while, but I end up in jail again.

**Comment by taariq** [comment]
@secard51 will you provide pigeon logs and sanitized config.yaml?

**Comment by secard51** [comment]
I bought a new RPC from Alchemy, I think the problem has been solved.

**Comment by taariq** [comment]
Closing as resolved.
