### ISSUE TITLE
Node exporter endpoint for Pigeon metrics

### ISSUE THREAD

**Issue by aditya-manit** [palomachain/paloma#1083]
### Summary
I would like to request the implementation of a Prometheus-style node exporter endpoint for Pigeon metrics. This would enable us to monitor our nodes more effectively by leveraging Prometheus for data aggregation and alerting.

### Detailed Explanation
Prometheus is a widely used monitoring tool that collects metrics from configured targets at given intervals, evaluates rule expressions, displays results, and can trigger alerts if some conditions are observed to be true. Integrating Prometheus-style metrics collection into Pigeon would greatly enhance our ability to monitor node health, performance, and reliability in real-time.

### Specific Metrics Needed
We can include pigeon metrics, similar to those provided by the `palomad q metrix` command for validators, formatted in a Prometheus-compatible way:

- **val_address**: The validator's address
- **success_rate**: Rate of successful operations or transactions
- **execution_time**: Time taken to execute operations or transactions
- **fee**: Fees associated with transactions or operations
- **feature_set**: A numerical representation of the available features or capabilities

An example of the current metric output in JSON format is provided below:

```json
{
  "val_metrics": {
    "val_address": "palomavaloper1cs6trg6chgcw0t8dzjx9tup7emctxxtwk8lxqn",
    "uptime": "0.960000000000000000",
    "success_rate": "0.500000000000000000",
    "execution_time": "0",
    "fee": "0",
    "feature_set": "0.000000000000000000"
  }
}

**Comment by taariq** [comment]
Fixed with https://github.com/palomachain/paloma/pull/1085. Please test it out @aditya-manit when you get a chance.

**Comment by verabehr** [comment]
From KingSuper: 
Yes the api is implemented but I was actually talking about node exporter metrics in that issue, the one that are available at port 26660
Also this one gives an doesnt give anything: https://api-1.paloma.nodes.guru/palomachain/paloma/metrix/params

**Comment by maharifu** [comment]
@taariq This was implemented in https://github.com/palomachain/paloma/pull/1287
