### ISSUE TITLE
exit-code

### ISSUE THREAD

**Issue by erkancamli** [palomachain/paloma#1086]
# What is happening?
When it was time to update, I made the necessary update. However, I encountered the exit-code error and could not solve the problem.

# Paloma and pigeon versions and logs
paloma logs: 

palomad.service: Main process exited, code=exited, status=1/FAILURE
palomad.service: Failed with result 'exit-code'.
palomad.service: Consumed 1.110s CPU time.
palomad.service: Scheduled restart job, restart counter is at 16831.
Stopped Paloma Node.
palomad.service: Consumed 1.110s CPU time.
Started Paloma Node.
failed to load latest version: failed to load store: initial version set to 12215387, but found earlier version 12215280
palomad.service: Main process exited, code=exited, status=1/FAILURE
palomad.service: Failed with result 'exit-code'.
palomad.service: Scheduled restart job, restart counter is at 16832.
Stopped Paloma Node.
Started Paloma Node.
failed to load latest version: failed to load store: initial version set to 12215387, but found earlier version 12215280
palomad.service: Main process exited, code=exited, status=1/FAILURE
palomad.service: Failed with result 'exit-code'.
palomad.service: Scheduled restart job, restart counter is at 16833.
Stopped Paloma Node.
Started Paloma Node.
failed to load latest version: failed to load store: initial version set to 12215387, but found earlier version 12215280
palomad.service: Main process exited, code=exited, status=1/FAILURE
palomad.service: Failed with result 'exit-code'.

Pigeon Logs:
4 19:43:14 vmi913085.contaboserver.net systemd[1]: pigeond.service: Failed with result 'exit-code'.
Feb 14 19:43:19 vmi913085.contaboserver.net systemd[1]: pigeond.service: Scheduled restart job, restart counter is at 3.
Feb 14 19:43:19 vmi913085.contaboserver.net systemd[1]: Stopped Pigeon daemon.
Feb 14 19:43:19 vmi913085.contaboserver.net systemd[1]: Started Pigeon daemon.
Feb 14 19:43:19 vmi913085.contaboserver.net pigeon[837834]: *coo! coo!*
Feb 14 19:43:19 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:19+01:00" level=info msg="app info" PID=837834 commit=fbfa8a6a7b1b8fe503dca7a73cc2b5690c9a1d23 version=v1.10.2
Feb 14 19:43:19 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:19+01:00" level=info msg="No signing key collection provided, falling back to using validator key for signing"
Feb 14 19:43:19 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:19+01:00" level=info msg="Starting healthcheck server"
Feb 14 19:43:19 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:19+01:00" level=info msg="Client: Status"
Feb 14 19:43:19 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:19+01:00" level=error msg=Nope err="post failed: Post \"http://localhost:26657\": dial tcp 127.0.0.1:26657: connect: connection refused"
Feb 14 19:43:19 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:19+01:00" level=error msg=Nope error="post failed: Post \"http://localhost:26657\": dial tcp 127.0.0.1:26657: connect: connection refused" x-correlation-id=cn6gjho7kvm0mhhnpto0
Feb 14 19:43:19 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:19+01:00" level=error msg="waiting for paloma to start running" error="base error: paloma is down\nwrapped error: post failed: Post \"http://localhost:26657\": dial tcp 127.0.0.1:26657: connect: connection refused"
Feb 14 19:43:24 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:24+01:00" level=info msg="Client: Status"
Feb 14 19:43:24 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:24+01:00" level=error msg=Nope err="post failed: Post \"http://localhost:26657\": dial tcp 127.0.0.1:26657: connect: connection refused"
Feb 14 19:43:24 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:24+01:00" level=error msg=Nope error="post failed: Post \"http://localhost:26657\": dial tcp 127.0.0.1:26657: connect: connection refused" x-correlation-id=cn6gjho7kvm0mhhnpto0
Feb 14 19:43:24 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:24+01:00" level=error msg="waiting for paloma to start running" error="base error: paloma is down\nwrapped error: post failed: Post \"http://localhost:26657\": dial tcp 127.0.0.1:26657: connect: connection refused"
Feb 14 19:43:29 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:29+01:00" level=info msg="Client: Status"
Feb 14 19:43:29 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:29+01:00" level=error msg=Nope err="post failed: Post \"http://localhost:26657\": dial tcp 127.0.0.1:26657: connect: connection refused"
Feb 14 19:43:29 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:29+01:00" level=error msg=Nope error="post failed: Post \"http://localhost:26657\": dial tcp 127.0.0.1:26657: connect: connection refused" x-correlation-id=cn6gjho7kvm0mhhnpto0
Feb 14 19:43:29 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:29+01:00" level=error msg="waiting for paloma to start running" error="base error: paloma is down\nwrapped error: post failed: Post \"http://localhost:26657\": dial tcp 127.0.0.1:26657: connect: connection refused"
Feb 14 19:43:34 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:34+01:00" level=info msg="Client: Status"
Feb 14 19:43:34 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:34+01:00" level=error msg=Nope err="post failed: Post \"http://localhost:26657\": dial tcp 127.0.0.1:26657: connect: connection refused"
Feb 14 19:43:34 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:34+01:00" level=error msg=Nope error="post failed: Post \"http://localhost:26657\": dial tcp 127.0.0.1:26657: connect: connection refused" x-correlation-id=cn6gjho7kvm0mhhnpto0
Feb 14 19:43:34 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:34+01:00" level=error msg="waiting for paloma to start running" error="base error: paloma is down\nwrapped error: post failed: Post \"http://localhost:26657\": dial tcp 127.0.0.1:26657: connect: connection refused"
Feb 14 19:43:39 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:39+01:00" level=info msg="Client: Status"
Feb 14 19:43:39 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:39+01:00" level=error msg=Nope err="post failed: Post \"http://localhost:26657\": dial tcp 127.0.0.1:26657: connect: connection refused"
Feb 14 19:43:39 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:39+01:00" level=error msg=Nope error="post failed: Post \"http://localhost:26657\": dial tcp 127.0.0.1:26657: connect: connection refused" x-correlation-id=cn6gjho7kvm0mhhnpto0
Feb 14 19:43:39 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:39+01:00" level=error msg="waiting for paloma to start running" error="base error: paloma is down\nwrapped error: post failed: Post \"http://localhost:26657\": dial tcp 127.0.0.1:26657: connect: connection refused"
Feb 14 19:43:44 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:44+01:00" level=info msg="Client: Status"
Feb 14 19:43:44 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:44+01:00" level=error msg=Nope err="post failed: Post \"http://localhost:26657\": dial tcp 127.0.0.1:26657: connect: connection refused"
Feb 14 19:43:44 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:44+01:00" level=error msg=Nope error="post failed: Post \"http://localhost:26657\": dial tcp 127.0.0.1:26657: connect: connection refused" x-correlation-id=cn6gjho7kvm0mhhnpto0
Feb 14 19:43:44 vmi913085.contaboserver.net pigeon[837834]: time="2024-02-14T19:43:44+01:00" level=error msg="waiting for paloma to start running" error="base error: paloma is down\nwrapped error: post failed: Post \"http://localhost:26657\": dial tcp 127.0.0.1:26657: connect: connection refused"

# How to reproduce?
I encountered this error after doing the latest update.

**Comment by taariq** [comment]
What version of pigeon and paloma are you running?

**Comment by erkancamli** [comment]
oot@vmi913085:~# palomad version
v1.12.1
root@vmi913085:~# pigeon version
App version: v1.10.2
Build commit hash: fbfa8a6a7b1b8fe503dca7a73cc2b5690c9a1d23
root@vmi913085:~#

**Comment by verabehr** [comment]
@erkancamli will you confirm that you are running palomad v1.12.1 with commit 53de2d0fe43950f197fda42e4813b28861f69ed1 https://github.com/palomachain/paloma/releases/tag/v1.12.1. The binary was rebuilt on release day.

**Comment by erkancamli** [comment]
> @erkancamli will you confirm that you are running palomad v1.12.1 with commit [53de2d0](https://github.com/palomachain/paloma/commit/53de2d0fe43950f197fda42e4813b28861f69ed1) https://github.com/palomachain/paloma/releases/tag/v1.12.1. The binary was rebuilt on release day.

Yes, the version you specified is installed

**Comment by byte-bandit** [comment]
It looks like there's some versioning mismatch going on. We had to re-draft the release of `v1.12.1` of Paloma due to a showstopper bug. That included re-creating the `v1.12.1` tag, which also changed the history. That's not a great thing to do, and we're going to solve this in a different manner in the future.

For now, I suggest you delete your local copy of `v1.12.1`, fetch the latest changes, make a fresh checkout and build. Let us know if the error persists afterwards.

**Comment by taariq** [comment]
Closing as fixed.
