### ISSUE TITLE
salomonval jail reason

### ISSUE THREAD

**Issue by salihayer** [palomachain/paloma#1093]
Last login: Tue Mar 19 16:56:43 2024 from 94.54.61.248
root@vmi1191487:~# palomad q valset get-validator-jail-reason palomavaloper1ljg6ed0pzc3xpqtareyfp6h4fpngs7nwqryqup
reason: No evidence supplied for contentious message 468536

**Comment by taariq** [comment]
Closing as we have upgraded to Cosmos SDK 0.50.5
