### ISSUE TITLE
BUG: height=15422850 ERR CONSENSUS FAILURE!!! err="+2/3 committed an invalid block: wrong Block.Header.AppHash

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#1106]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

The Following block created apphash: https://paloma.explorers.guru/block/15422850. The only included four txes were  the following:
 
A log letting paloma know that there was an error attesting to a message:
```
{2 items
"tx":{3 items
"body":{5 items
"messages":[1 item
0:{5 items
"@type":string"/palomachain.paloma.paloma.MsgAddStatusUpdate"
"status":string"error attesting messages"
"level":string"LEVEL_ERROR"
"metadata":{2 items
"creator":string"paloma1t5a905wfcv5kl0zn33ejnv9dkcjnerqy2teqat"
"signers":[1 item
0:string"paloma1t5a905wfcv5kl0zn33ejnv9dkcjnerqy2teqat"
]
}
"args":[1 item
0:{2 items
"key":string"error"
"value":string"there are 1 errors in the group: error 1: rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: message id 501170 does not exist [cosmos/cosmos-sdk@v0.50.5/baseapp/baseapp.go:1011] with gas used: '390971': unknown request "
}
]
}
]
```

```
8:03PM INF received complete proposal block hash=F30D4858551A0FC07E580C1DCF7CBEF8B9AE9A2FEAF07941D46D3C122A0220D7 height=15422850 module=consensus
8:03PM ERR CONSENSUS FAILURE!!! err="+2/3 committed an invalid block: wrong Block.Header.AppHash.  Expected 15177849470752FFAA86416EDDACDA21DCCFF61D14F9BC43D52880A2C6CCAE37, got C2658F993BFBDF61B966B9804C404A68C4CCBDAFB24AD164A7FA109471D93804" module=consensus stack="goroutine 1252 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x5e\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()\n\t/root/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:800 +0x46\npanic({0x2ee1ae0?, 0xc0035007a0?})\n\t/usr/local/go/src/runtime/panic.go:770 +0x132\ngithub.com/cometbft/cometbft/consensus.(*State).finalizeCommit(0xc0012e6008, 0xeb5582)\n\t/root/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:1712 +0x1045\ngithub.com/cometbft/cometbft/consensus.(*State).tryFinalizeCommit(0xc0012e6008, 0xeb5582)\n\t/root/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:1681 +0x2e8\ngithub.com/cometbft/cometbft/consensus.(*State).handleCompleteProposal(0xc0012e6008, 0xeb5582)\n\t/root/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:2050 +0x372\ngithub.com/cometbft/cometbft/consensus.(*State).handleMsg(0xc0012e6008, {{0x3d89800, 0xc0055d4258}, {0xc00160b2c0, 0x28}})\n\t/root/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:909 +0x178\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine(0xc0012e6008, 0x0)\n\t/root/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:835 +0x3f1\ncreated by github.com/cometbft/cometbft/consensus.(*State).OnStart in goroutine 405\n\t/root/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:397 +0x10c\n"
```

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

paloma: 1.13.0
pigeon : v1.11.0
Build commit hash: f13949705a1ab41fcc4da48d6d1da35742dfd3dc

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Sync from pokachu Snapshot.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

1. Cosmwasm messages do not cause apphash. This may require an upgrade to CometBFT.

**Comment by erkancamli** [comment]
7:02PM ERR Stopping peer for error err="reactor validation error: wrong Block.Header.AppHash.  Expected 15177849470752FFAA86416EDDACDA21DCCFF61D14F9BC43D52880A2C6CCAE37, got C2658F993BFBDF61B966B9804C404A68C4CCBDAFB24AD164A7FA109471D93804" module=p2p peer="Peer{MConn{94.131.109.218:26656} 72be9ddf94f2b6085164b3ed1eeecd7bb6c302b0 out}"
7:02PM INF service stop impl=MConn{94.131.109.218:26656} module=p2p msg="Stopping MConnection service" peer=72be9ddf94f2b6085164b3ed1eeecd7bb6c302b0@94.131.109.218:26656
7:02PM ERR Stopping peer for error err="read tcp 135.181.250.158:51812->94.131.109.218:26656: use of closed network connection" module=p2p peer="Peer{MConn{94.131.109.218:26656} 72be9ddf94f2b6085164b3ed1eeecd7bb6c302b0 out}"
7:02PM INF service stop impl="Peer{MConn{94.131.109.218:26656} 72be9ddf94f2b6085164b3ed1eeecd7bb6c302b0 out}" module=p2p msg="Stopping Peer service" peer=72be9ddf94f2b6085164b3ed1eeecd7bb6c302b0@94.131.109.218:26656
7:02PM ERR error while stopping peer error="already stopped" module=p2p
7:02PM INF Reconnecting to peer addr=72be9ddf94f2b6085164b3ed1eeecd7bb6c302b0@94.131.109.218:26656 module=p2p
7:02PM INF service start impl="Peer{MConn{37.221.192.235:60756} a54c6cabc297455140a9193a25340f2592b9af9d out}" module=p2p msg="Starting Peer service" peer=a54c6cabc297455140a9193a25340f2592b9af9d@37.221.192.235:60756
7:02PM INF service start impl=MConn{37.221.192.235:60756} module=p2p msg="Starting MConnection service" peer=a54c6cabc297455140a9193a25340f2592b9af9d@37.221.192.235:60756
7:02PM INF service start impl="Peer{MConn{94.131.109.218:26656} 72be9ddf94f2b6085164b3ed1eeecd7bb6c302b0 out}" module=p2p msg="Starting Peer service" peer=72be9ddf94f2b6085164b3ed1eeecd7bb6c302b0@94.131.109.218:26656
7:02PM INF service start impl=MConn{94.131.109.218:26656} module=p2p msg="Starting MConnection service" peer=72be9ddf94f2b6085164b3ed1eeecd7bb6c302b0@94.131.109.218:26656
7:02PM ERR Error in validation err="wrong Block.Header.AppHash.  Expected 15177849470752FFAA86416EDDACDA21DCCFF61D14F9BC43D52880A2C6CCAE37, got C2658F993BFBDF61B966B9804C404A68C4CCBDAFB24AD164A7FA109471D93804" module=blocksync
7:02PM ERR Stopping peer for error err="reactor validation error: wrong Block.Header.AppHash.  Expected 15177849470752FFAA86416EDDACDA21DCCFF61D14F9BC43D52880A2C6CCAE37, got C2658F993BFBDF61B966B9804C404A68C4CCBDAFB24AD164A7FA109471D93804" module=p2p peer="Peer{MConn{65.109.61.125:12156} a7abe3888b1916b3f8b04d6b2a1f24ee31add160 out}"
7:02PM INF service stop impl=MConn{65.109.61.125:12156} module=p2p msg="Stopping MConnection service" peer=a7abe3888b1916b3f8b04d6b2a1f24ee31add160@65.109.61.125:12156
7:02PM ERR Stopping peer for error err="read tcp 135.181.250.158:54862->65.109.61.125:12156: use of closed network connection" module=p2p peer="Peer{MConn{65.109.61.125:12156} a7abe3888b1916b3f8b04d6b2a1f24ee31add160 out}"
7:02PM INF service stop impl="Peer{MConn{65.109.61.125:12156} a7abe3888b1916b3f8b04d6b2a1f24ee31add160 out}" module=p2p msg="Stopping Peer service" peer=a7abe3888b1916b3f8b04d6b2a1f24ee31add160@65.109.61.125:12156
7:02PM ERR error while stopping peer error="already stopped" module=p2p
7:02PM INF Reconnecting to peer addr=a7abe3888b1916b3f8b04d6b2a1f24ee31add160@65.109.61.125:12156 module=p2p
7:02PM ERR Stopping peer for error err="reactor validation error: wrong Block.Header.AppHash.  Expected 15177849470752FFAA86416EDDACDA21DCCFF61D14F9BC43D52880A2C6CCAE37, got C2658F993BFBDF61B966B9804C404A68C4CCBDAFB24AD164A7FA109471D93804" module=p2p peer="Peer{MConn{95.214.52.144:10656} 16f0d09580054101394ea08bbb48b1ad5bb91a27 out}"
7:02PM INF service stop impl=MConn{95.214.52.144:10656} module=p2p msg="Stopping MConnection service" peer=16f0d09580054101394ea08bbb48b1ad5bb91a27@95.214.52.144:10656
7:02PM ERR Stopping peer for error err="read tcp 135.181.250.158:58372->95.214.52.144:10656: use of closed network connection" module=p2p peer="Peer{MConn{95.214.52.144:10656} 16f0d09580054101394ea08bbb48b1ad5bb91a27 out}"
7:02PM ERR error while stopping peer error="already stopped" module=p2p
7:02PM INF service stop impl="Peer{MConn{95.214.52.144:10656} 16f0d09580054101394ea08bbb48b1ad5bb91a27 out}" module=p2p msg="Stopping Peer service" peer=16f0d09580054101394ea08bbb48b1ad5bb91a27@95.214.52.144:10656
7:02PM INF Reconnecting to peer addr=16f0d09580054101394ea08bbb48b1ad5bb91a27@95.214.52.144:10656 module=p2p
7:02PM INF service start impl="Peer{MConn{65.109.61.125:12156} a7abe3888b1916b3f8b04d6b2a1f24ee31add160 out}" module=p2p msg="Starting Peer service" peer=a7abe3888b1916b3f8b04d6b2a1f24ee31add160@65.109.61.125:12156
7:02PM INF service start impl=MConn{65.109.61.125:12156} module=p2p msg="Starting MConnection service" peer=a7abe3888b1916b3f8b04d6b2a1f24ee31add160@65.109.61.125:12156
7:02PM INF service start impl="Peer{MConn{95.214.52.144:10656} 16f0d09580054101394ea08bbb48b1ad5bb91a27 out}" module=p2p msg="Starting Peer service" peer=16f0d09580054101394ea08bbb48b1ad5bb91a27@95.214.52.144:10656
7:02PM INF service start impl=MConn{95.214.52.144:10656} module=p2p msg="Starting MConnection service" peer=16f0d09580054101394ea08bbb48b1ad5bb91a27@95.214.52.144:10656
7:02PM ERR Error in validation err="wrong Block.Header.AppHash.  Expected 15177849470752FFAA86416EDDACDA21DCCFF61D14F9BC43D52880A2C6CCAE37, got C2658F993BFBDF61B966B9804C404A68C4CCBDAFB24AD164A7FA109471D93804" module=blocksync
7:02PM ERR Stopping peer for error err="reactor validation error: wrong Block.Header.AppHash.  Expected 15177849470752FFAA86416EDDACDA21DCCFF61D14F9BC43D52880A2C6CCAE37, got C2658F993BFBDF61B966B9804C404A68C4CCBDAFB24AD164A7FA109471D93804" module=p2p peer="Peer{MConn{116.203.96.4:11056} c661f79077218b4c0169284ddbe17abcf413b362 out}"
7:02PM INF service stop impl=MConn{116.203.96.4:11056} module=p2p msg="Stopping MConnection service" peer=c661f79077218b4c0169284ddbe17abcf413b362@116.203.96.4:11056
7:02PM ERR Stopping peer for error err="read tcp 135.181.250.158:33596->116.203.96.4:11056: use of closed network connection" module=p2p peer="Peer{MConn{116.203.96.4:11056} c661f79077218b4c0169284ddbe17abcf413b362 out}"
7:02PM ERR error while stopping peer error="already stopped" module=p2p
7:02PM INF Reconnecting to peer addr=c661f79077218b4c0169284ddbe17abcf413b362@116.203.96.4:11056 module=p2p
7:02PM INF service stop impl="Peer{MConn{116.203.96.4:11056} c661f79077218b4c0169284ddbe17abcf413b362 out}" module=p2p msg="Stopping Peer service" peer=c661f79077218b4c0169284ddbe17abcf413b362@116.203.96.4:11056
7:02PM ERR Stopping peer for error err="reactor validation error: wrong Block.Header.AppHash.  Expected 15177849470752FFAA86416EDDACDA21DCCFF61D14F9BC43D52880A2C6CCAE37, got C2658F993BFBDF61B966B9804C404A68C4CCBDAFB24AD164A7FA109471D93804" module=p2p peer="Peer{MConn{65.108.201.240:12156} 2ec242edb345943ee474e1c04b032f46a9bffded out}"
7:02PM INF service stop impl=MConn{65.108.201.240:12156} module=p2p msg="Stopping MConnection service" peer=2ec242edb345943ee474e1c04b032f46a9bffded@65.108.201.240:12156
7:02PM ERR Stopping peer for error err="read tcp 135.181.250.158:54390->65.108.201.240:12156: use of closed network connection" module=p2p peer="Peer{MConn{65.108.201.240:12156} 2ec242edb345943ee474e1c04b032f46a9bffded out}"
7:02PM INF service stop impl="Peer{MConn{65.108.201.240:12156} 2ec242edb345943ee474e1c04b032f46a9bffded out}" module=p2p msg="Stopping Peer service" peer=2ec242edb345943ee474e1c04b032f46a9bffded@65.108.201.240:12156
7:02PM ERR error while stopping peer error="already stopped" module=p2p
7:02PM INF Reconnecting to peer addr=2ec242edb345943ee474e1c04b032f46a9bffded@65.108.201.240:12156 module=p2p
7:02PM INF service start impl="Peer{MConn{65.108.201.240:12156} 2ec242edb345943ee474e1c04b032f46a9bffded out}" module=p2p msg="Starting Peer service" peer=2ec242edb345943ee474e1c04b032f46a9bffded@65.108.201.240:12156
7:02PM INF service start impl=MConn{65.108.201.240:12156} module=p2p msg="Starting MConnection service" peer=2ec242edb345943ee474e1c04b032f46a9bffded@65.108.201.240:12156
7:02PM INF service start impl="Peer{MConn{116.203.96.4:11056} c661f79077218b4c0169284ddbe17abcf413b362 out}" module=p2p msg="Starting Peer service" peer=c661f79077218b4c0169284ddbe17abcf413b362@116.203.96.4:11056
7:02PM INF service start impl=MConn{116.203.96.4:11056} module=p2p msg="Starting MConnection service" peer=c661f79077218b4c0169284ddbe17abcf413b362@116.203.96.4:11056
7:02PM ERR Error in validation err="wrong Block.Header.AppHash.  Expected 15177849470752FFAA86416EDDACDA21DCCFF61D14F9BC43D52880A2C6CCAE37, got C2658F993BFBDF61B966B9804C404A68C4CCBDAFB24AD164A7FA109471D93804" module=blocksync
7:02PM ERR Stopping peer for error err="reactor validation error: wrong Block.Header.AppHash.  Expected 15177849470752FFAA86416EDDACDA21DCCFF61D14F9BC43D52880A2C6CCAE37, got C2658F993BFBDF61B966B9804C404A68C4CCBDAFB24AD164A7FA109471D93804" module=p2p peer="Peer{MConn{198.244.228.162:54056} a9a0a77dfd05b42b14461c57e8a1f252c7deeef3 out}"
7:02PM INF service stop impl=MConn{198.244.228.162:54056} module=p2p msg="Stopping MConnection service" peer=a9a0a77dfd05b42b14461c57e8a1f252c7deeef3@198.244.228.162:54056
7:02PM ERR Stopping peer for error err="read tcp 135.181.250.158:43418->198.244.228.162:54056: use of closed network connection" module=p2p peer="Peer{MConn{198.244.228.162:54056} a9a0a77dfd05b42b14461c57e8a1f252c7deeef3 out}"
7:02PM ERR error while stopping peer error="already stopped" module=p2p
7:02PM INF service stop impl="Peer{MConn{198.244.228.162:54056} a9a0a77dfd05b42b14461c57e8a1f252c7deeef3 out}" module=p2p msg="Stopping Peer service" peer=a9a0a77dfd05b42b14461c57e8a1f252c7deeef3@198.244.228.162:54056
7:02PM INF Reconnecting to peer addr=a9a0a77dfd05b42b14461c57e8a1f252c7deeef3@198.244.228.162:54056 module=p2p
7:02PM ERR Stopping peer for error err="reactor validation error: wrong Block.Header.AppHash.  Expected 15177849470752FFAA86416EDDACDA21DCCFF61D14F9BC43D52880A2C6CCAE37, got C2658F993BFBDF61B966B9804C404A68C4CCBDAFB24AD164A7FA109471D93804" module=p2p peer="Peer{MConn{37.221.192.235:60756} a54c6cabc297455140a9193a25340f2592b9af9d out}"
7:02PM INF service stop impl=MConn{37.221.192.235:60756} module=p2p msg="Stopping MConnection service" peer=a54c6cabc297455140a9193a25340f2592b9af9d@37.221.192.235:60756
7:02PM ERR Stopping peer for error err="read tcp 135.181.250.158:41336->37.221.192.235:60756: use of closed network connection" module=p2p peer="Peer{MConn{37.221.192.235:60756} a54c6cabc297455140a9193a25340f2592b9af9d out}"
7:02PM INF service stop impl="Peer{MConn{37.221.192.235:60756} a54c6cabc297455140a9193a25340f2592b9af9d out}" module=p2p msg="Stopping Peer service" peer=a54c6cabc297455140a9193a25340f2592b9af9d@37.221.192.235:60756
7:02PM ERR error while stopping peer error="already stopped" module=p2p
7:02PM INF Reconnecting to peer addr=a54c6cabc297455140a9193a25340f2592b9af9d@37.221.192.235:60756 module=p2p
7:02PM INF service start impl="Peer{MConn{37.221.192.235:60756} a54c6cabc297455140a9193a25340f2592b9af9d out}" module=p2p msg="Starting Peer service" peer=a54c6cabc297455140a9193a25340f2592b9af9d@37.221.192.235:60756
7:02PM INF service start impl=MConn{37.221.192.235:60756} module=p2p msg="Starting MConnection service" peer=a54c6cabc297455140a9193a25340f2592b9af9d@37.221.192.235:60756
7:02PM INF service start impl="Peer{MConn{198.244.228.162:54056} a9a0a77dfd05b42b14461c57e8a1f252c7deeef3 out}" module=p2p msg="Starting Peer service" peer=a9a0a77dfd05b42b14461c57e8a1f252c7deeef3@198.244.228.162:54056
7:02PM INF service start impl=MConn{198.244.228.162:54056} module=p2p msg="Starting MConnection service" peer=a9a0a77dfd05b42b14461c57e8a1f252c7deeef3@198.244.228.162:54056
7:02PM ERR Error in validation err="wrong Block.Header.AppHash.  Expected 15177849470752FFAA86416EDDACDA21DCCFF61D14F9BC43D52880A2C6CCAE37, got C2658F993BFBDF61B966B9804C404A68C4CCBDAFB24AD164A7FA109471D93804" module=blocksync
7:02PM ERR Stopping peer for error err="reactor validation error: wrong Block.Header.AppHash.  Expected 15177849470752FFAA86416EDDACDA21DCCFF61D14F9BC43D52880A2C6CCAE37, got C2658F993BFBDF61B966B9804C404A68C4CCBDAFB24AD164A7FA109471D93804" module=p2p peer="Peer{MConn{65.108.201.240:12156} 2ec242edb345943ee474e1c04b032f46a9bffded out}"
7:02PM INF service stop impl=MConn{65.108.201.240:12156} module=p2p msg="Stopping MConnection service" peer=2ec242edb345943ee474e1c04b032f46a9bffded@65.108.201.240:12156
7:02PM INF service stop impl="Peer{MConn{65.108.201.240:12156} 2ec242edb345943ee474e1c04b032f46a9bffded out}" module=p2p msg="Stopping Peer service" peer=2ec242edb345943ee474e1c04b032f46a9bffded@65.108.201.240:12156
7:02PM ERR Stopping peer for error err="reactor validation error: wrong Block.Header.AppHash.  Expected 15177849470752FFAA86416EDDACDA21DCCFF61D14F9BC43D52880A2C6CCAE37, got C2658F993BFBDF61B966B9804C404A68C4CCBDAFB24AD164A7FA109471D93804" module=p2p peer="Peer{MConn{65.109.61.125:12156} a7abe3888b1916b3f8b04d6b2a1f24ee31add160 out}"

**Comment by taariq** [comment]
@erkancamli which block did it apphash? I am looking for this line: 
```
8:03PM INF received complete proposal block hash=F......7 **height=15422850** module=consensus
8:03PM ERR CONSENSUS FAILURE!!! err="+2/3 committed an invalid block: wrong Block.Header.AppHash.  ```
```

**Comment by taariq** [comment]
Thank you @erkancamli

**Comment by taariq** [comment]
Fixed with https://github.com/palomachain/paloma/pull/1140
