### ISSUE TITLE
BUG: [Cosmos v0.50.5] failed to load latest version: failed to load store: Value missing for key after chain restart

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#1121]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

**SEVEN VALIDATORS with the same error:** 

**validator 1:** 
failed to load latest version: failed to load store: Value missing for key [0 0 0 0 0 241 183 176 0 0 0 1] corresponding to nodeKey 730000000000f1b7b000000001 [/home/paloma/go/pkg/mod/cosmossdk.io/store@v1.0.2/rootmulti/store.go:255]

**Validator 2:** 
failed to load latest version: failed to load store: Value missing for key [0 0 0 0 0 241 183 176 0 0 0 1] corresponding to nodeKey 730000000000f1b7b000000001 [/home/runner/go/pkg/mod/cosmossdk.io/store@v1.0.2/rootmulti/store.go:255]

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

palomad version v1.13.1

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Upgrading at Chain Halt.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

No key not foun

**Comment by byte-bandit** [comment]
Emitted from here https://github.com/cosmos/cosmos-sdk/blob/2a199f57c5902b4a0ba368d74b344148772500c7/store/rootmulti/store.go#L253

**Comment by taariq** [comment]
This was due to bad migration of iavl 1.0.3 from the v0. version.

**Comment by taariq** [comment]
Fixed with https://github.com/palomachain/paloma/pull/1116
