### ISSUE TITLE
Check correct wasm library version on start

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#1122]
# Background

We currently have no check for the correct wasm lib version on start. It is easy to miss but super important to keep the chain in sync: https://github.com/CosmWasm/wasmd/blob/main/x/wasm/module.go#L224. 

# Done when

- [x] The correct wasm library version is checked on start

**Comment by taariq** [comment]
Fixed with https://github.com/palomachain/paloma/pull/1123
