### ISSUE TITLE
Turnstone EVM deposit and withdrawal

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#115]
Background:
https://www.notion.so/volumefi/EPIC-05-06-Paloma-s-smart-contract-3d91b9a340d24d6ea5e5030dcc9efcf7
https://www.notion.so/volumefi/EPIC-05-13-Paloma-Goes-to-Ethereum-for-Remote-Execution-cdc9588ae14d445bb7e324c68580c356#191ad5ee299c48df8a68db76f99ccad9

### Deposit
- [ ] following the epic's structure users can deposit funds and it is associated with the job id that they have provided
- [ ] a query endpoint to get the funds in the job id
- [ ] a query endpoint to get the customer's funds in total and broken down per job

### Withdrawal
customers can withdraw their money by following the epic's https://www.notion.so/volumefi/EPIC-05-06-Paloma-s-smart-contract-3d91b9a340d24d6ea5e5030dcc9efcf7 requirements

### Please break this down into multiple smaller PRs

**Comment by Vizualni** [comment]
This is something that we don't need right now. Once we do need it and requirements are clear we will create new tickets.
