### ISSUE TITLE
BUG: Validator is showing in active set, but not signing any blocks after upgrade to Paloma v1.13.3

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#1150]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

BUG: Validator is showing in active set, but not signing any blocks after upgrade to Paloma v1.13.3
Paloma Logs:
https://gist.github.com/pcheliniy/5de28dfdeb927073d965456ce474d72a paloma logs

Pigeon Logs:
https://gist.github.com/pcheliniy/2f1d4d0f4dbb8170f69de91ef4beead7 pigeon logs

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

Paloma: v1.13.3
commit: 1ba2ba70804f490ba2512a00506265cf7b40d51e

Pigeon: 1.11.0

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Not able to reproduce. Validator shows as active: https://paloma.explorers.guru/validator/palomavaloper1p4r04ek0jnngegmw76rpx66xu9ep0kuzvcwxyy

But is not signing.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Active validators must sign.

**Comment by taariq** [comment]
Closing as fixed by @pcheliniy

**Comment by pcheliniy** [comment]
It was a my mistake and not really a problem, I messed up with node keys, during all this cleanups / inits.
