### ISSUE TITLE
BUG: Unable to relay across Ethereum mainnet  due to Gas/fee setting

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#1151]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Messages on Ethereum are not being relayed due to this error (retrieved from message `errorData`). Other chains were not tested yet. 

```
both gasPrice and (maxFeePerGas or maxPriorityFeePerGas) specified
```

This happens across multiple pigeons and therefore doesn't seem to be a pigeon setup issue. According to @webelf101 _It looks like protocol is trying to send a tx with the option. Either gasPrice or maxFeePerGas & maxPriorityFeePerGas should be set. For ethereum mainnet, we need to masFeePerGas & maxPriorityFeePerGas because it is tx-type is 2._

Also FYI, the message was put into the queue 2 times again it seems before being processed. The second message results in a "consensus not achieved" error. 

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

Paloma v1.13.3
Pigeon 1.11.0

https://gist.github.com/verabehr/40d03a3a0262435e920b3583d0e8b5ec 

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

1. log into the bots-server
2. `cd ~/app/curve-twap-dca-bot-script`
3. `python3 bot_set_paloma.py`
This creates a message that should be relayed on Ethereum main

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Messages are succesfully relayed by pigeons with correct EVM gas estimates.

**Comment by verabehr** [comment]
moving to Paloma https://github.com/VolumeFi/paloma/issues/1488
