### ISSUE TITLE
BUG: When attempting State Sync: INF error from light block request from primary, removing... error="post failed: Post context deadline exceeded" height=16015222 module=light 

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#1156]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

 When i try to perform the state sync @vishal-kanna gets the following error at block height https://paloma.explorers.guru/block/16015222

4:55PM INF service start impl=MConn{79.143.179.196:26656} module=p2p msg="Starting MConnection service" peer=2c6772b11c1f9eff2a923eb2bf808543cdd501c5@79.143.179.196:26656
4:55PM INF VerifyHeader hash=E09E858425AB15CA88E085DBA3644DB8B4ED0E8501E1530D8F63A418955E86DA height=16015001 module=light
4:56PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=3 numToDial=7
4:56PM INF We need more addresses. Sending pexRequest to random peer module=pex peer="Peer{MConn{209.182.239.169:26656} 7eae755c119f538e0dc99f3c37289de628bc9526 out}"
4:56PM INF error from light block request from primary, removing... error="post failed: Post \"http://79.143.179.196:26657\": context deadline exceeded" height=16015222 module=light primary=http{http://2c6772b11c1f9eff2a923eb2bf808543cdd501c5@79.143.179.196:26657}
4:56PM ERR error on light block request from witness, removing... error="post failed: Post \"http://79.143.179.196:26657\": context deadline exceeded" module=light primary=http{http://2c6772b11c1f9eff2a923eb2bf808543cdd501c5@79.143.179.196:26657}

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

Paloma v1.13.3
Pigeon v1.11.1

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Statesync Paloma.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Context deadlines do not get exceeded for state sync.

**Comment by taariq** [comment]
@vishal-kanna are you able to add any further logs via gist?

**Comment by vishal-kanna** [comment]
@taariq Here is the gist link https://gist.github.com/vishal-kanna/1adcf7004bce737ba443d992d8743a59

**Comment by taariq** [comment]
> @taariq Here is the gist link https://gist.github.com/vishal-kanna/1adcf7004bce737ba443d992d8743a59

Thanks @vishal-kanna. The view here is that the peer providing the header is slow and that it maybe appropriate to remove them from persistent peers. We'll keep an eye on this on.

**Comment by vishal-kanna** [comment]
Okay @taariq

**Comment by vishal-kanna** [comment]
@taariq I think this issue can be closed.
