### ISSUE TITLE
bug: what is happening

### ISSUE THREAD

**Issue by ppnv** [palomachain/paloma#1162]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

9:44AM INF finalized block block_app_hash=79C222E4DD548F78E40FFB0FC81CDF4115D5C1EDA7CBC7557C3745599D331AF0 height=16609219 module=state num_txs_res=5 num_val_updates=0
9:44AM INF executed block app_hash=79C222E4DD548F78E40FFB0FC81CDF4115D5C1EDA7CBC7557C3745599D331AF0 height=16609219 module=state
9:44AM INF committed state block_app_hash=8DF02B798912FF3685C09C2554D6A7904E7EEB9FC544C08059FB21F86C5D6B2B height=16609219 module=state
9:44AM INF indexed block events height=16609219 module=txindex
9:44AM ERR error while adding message evidence. error="message id 22271 does not exist" module=x/palomaconsensus
9:44AM ERR error while adding message evidence. error="message id 22271 does not exist" module=x/palomaconsensus
9:44AM INF Timed out dur=963.830111 height=16609220 module=consensus round=0 step=RoundStepNewHeight
9:44AM INF received proposal module=consensus proposal="Proposal{16609220/0 (773823E7F69C65E5935DB495AB75D34D3AD7D1FDF8CC15F6F810A662559FDFD0:1:4F956AD66E89, -1) 903DF19E2367 @ 2024-05-06T07:44:16.28364339Z}" proposer=9E09C665D5DF24EAC5D6D6068BE1CD80FAB93781
9:44AM INF received complete proposal block hash=773823E7F69C65E5935DB495AB75D34D3AD7D1FDF8CC15F6F810A662559FDFD0 height=16609220 module=consensus
9:44AM INF finalizing commit of block hash=773823E7F69C65E5935DB495AB75D34D3AD7D1FDF8CC15F6F810A662559FDFD0 height=16609220 module=consensus num_txs=3 root=79C222E4DD548F78E40FFB0FC81CDF4115D5C1EDA7CBC7557C3745599D331AF0
9:44AM INF added message evidence. chain-reference-id=matic-main chain-type=evm message-id=22275 module=x/palomaconsensus queue-type-name=evm/matic-main/validators-balances validator=palomavaloper1tdw23fpnxh2uk3djtteh7eaydymrfgnaepkpkz
9:44AM INF added message evidence. chain-reference-id=eth-main chain-type=evm message-id=22273 module=x/palomaconsensus queue-type-name=evm/eth-main/validators-balances validator=palomavaloper1s0lankh33kprer2l22nank5rvsuh9ksafx3mze
9:44AM INF added message evidence. chain-reference-id=bnb-main chain-type=evm message-id=22272 module=x/palomaconsensus queue-type-name=evm/bnb-main/validators-balances validator=palomavaloper1kludne80z0tcq9t7j9fqa630fechsjhxc324tt
9:44AM INF abci-validator-size module=x/palomaconsensus
9:44AM ERR Consensus not achieved. error="evm: consensus not achieved" component=attest-validator-balances distribution={} module=x/evm msg-id=22272 msg-nonce="\x00\x00\x00\x00\x00\x00W\x00" total-shares=1285305458449622 total-votes=742996796623339
9:44AM ERR Consensus not achieved. error="evm: consensus not achieved" component=attest-validator-balances distribution={} module=x/evm msg-id=22273 msg-nonce="\x00\x00\x00\x00\x00\x00W\x01" total-shares=1285305458449622 total-votes=398344021768094
9:44AM ERR Consensus not achieved. error="evm: consensus not achieved" component=attest-validator-balances distribution={} module=x/evm msg-id=22274 msg-nonce="\x00\x00\x00\x00\x00\x00W\x02" total-shares=1285305458449622 total-votes=303701651984764
9:44AM ERR Consensus not achieved. error="evm: consensus not achieved" component=attest-validator-balances distribution={} module=x/evm msg-id=22275 msg-nonce="\x00\x00\x00\x00\x00\x00W\x03" total-shares=1285305458449622 total-votes=277030256750326
9:44AM ERR Consensus not achieved. error="evm: consensus not achieved" component=attest-validator-balances distribution={} module=x/evm msg-id=22276 msg-nonce="\x00\x00\x00\x00\x00\x00W\x04" total-shares=1285305458449622 total-votes=170308073714840
9:44AM INF trying to deploy smart contract to EVM chain chain-reference-id=arbitrum-main module=x/evm smart-contract-id=1
9:44AM INF trying to deploy smart contract to EVM chain chain-reference-id=base-main module=x/evm smart-contract-id=1
9:44AM INF trying to deploy smart contract to EVM chain chain-reference-id=blast-main module=x/evm smart-contract-id=1
9:44AM INF trying to deploy smart contract to EVM chain chain-reference-id=bnb-main module=x/evm smart-contract-id=1
9:44AM INF trying to deploy smart contract to EVM chain chain-reference-id=eth-main module=x/evm smart-contract-id=1
9:44AM INF trying to deploy smart contract to EVM chain chain-reference-id=gnosis-main module=x/evm smart-contract-id=1
9:44AM INF trying to deploy smart contract to EVM chain chain-reference-id=matic-main module=x/evm smart-contract-id=1
9:44AM INF trying to deploy smart contract to EVM chain chain-reference-id=op-main module=x/evm smart-contract-id=1
9:44AM INF trying to deploy smart contract to all chains module=x/evm smart-contract-id=1
9:44AM INF finalized block block_app_hash=51FFBF4A572641925D2067244A1BCCFB04A827B41C65F772CB833CB64198C57F height=16609220 module=state num_txs_res=3 num_val_updates=0
9:44AM INF executed block app_hash=51FFBF4A572641925D2067244A1BCCFB04A827B41C65F772CB833CB64198C57F height=16609220 module=state
9:44AM ERR error while adding message evidence. error="message id 22271 does not exist" module=x/palomaconsensus
9:44AM INF committed state block_app_hash=79C222E4DD548F78E40FFB0FC81CDF4115D5C1EDA7CBC7557C3745599D331AF0 height=16609220 module=state
9:44AM INF indexed block events height=16609220 module=txindex

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

root@Ubuntu-2204-jammy-amd64-base:~# palomad version
v1.13.4
root@Ubuntu-2204-jammy-amd64-base:~# pigeon version
App version: v1.11.2
Build commit hash: 41e04f5c470715e46b9cdfe9a5105ec4fd840e84

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Did not do anything)
The errors appeared on their own after the latest updates (after some time)

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Мalidator goes to jail

**Comment by taariq** [comment]
Thank you @ppnv. Closing as currently working, but we'll re-open as needed.
