### ISSUE TITLE
BUG: Apphash on block 21627396 do we still have non-determinism in Paloma?

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#1249]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

KingSuper Apphashed on [block 21627396](https://paloma.explorers.guru/block/21627396)

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

commit: b58105b63c456560fa0efd1d6973bfd963d00989
cosmos_sdk_version: v0.50.6
go: go version go1.22.2 linux/amd64
name: paloma
server_name: palomad
version: v1.15.6

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

NO repro

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Non-determinism resolved.

**Comment by maharifu** [comment]
The last block they signed before getting apphash error was https://paloma.explorers.guru/block/21627372 so their problems might have started a bit earlier.

This was also the only validator to report apphash error in this version.

**Comment by taariq** [comment]
Closing as won't fix.
