### ISSUE TITLE
bug: No evidence supplied for contentious message 248883

### ISSUE THREAD

**Issue by salihayer** [palomachain/paloma#1264]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

{I am constantly being jailbroken. When I question the reason for jailbreaking, I get the following answer.
No evidence supplied for contentious message 248883}

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

{root@vmi1191487:~# palomad version v1.15.7
root@vmi1191487:~# pigeon version
App version: v1.12.4
Build commit hash: 738bf5dbebfa818de80150ba38b2ab0b95df0166

root@vmi1191487:~# journalctl -u pigeond.service -f -n 100
Insufficient watch descriptors available. Reverting to -n.
-- Logs begin at Sat 2024-08-17 08:47:06 CEST, end at Sat 2024-08-17 14:09:02 CEST. --
Aug 17 14:08:02 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:02+02:00" level=info msg="Client: Status" status="&{{{8 11 0} 705cf3cfe4f75345bc23b>
Aug 17 14:08:02 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:02+02:00" level=info msg="checking if validator is staking"
Aug 17 14:08:02 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:02+02:00" level=info msg="validator is staking"
Aug 17 14:08:03 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:03+02:00" level=error msg="incorrect chain" chain-reference-id=matic-main error="Bl>
Aug 17 14:08:03 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:03+02:00" level=warning msg="Chain infos changed. Building processors..." error="ch>
Aug 17 14:08:03 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:03+02:00" level=error msg="Failed to execute process: BlockByHash: not found" compo>
Aug 17 14:08:03 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:03+02:00" level=info msg="relayer loop"
Aug 17 14:08:07 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:07+02:00" level=info msg="Client: Status"
Aug 17 14:08:07 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:07+02:00" level=info msg="Client: Status" status="&{{{8 11 0} 705cf3cfe4f75345bc23b>
Aug 17 14:08:07 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:07+02:00" level=info msg="Client: Status" status="&{{{8 11 0} 705cf3cfe4f75345bc23b>
Aug 17 14:08:07 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:07+02:00" level=info msg="checking if validator is staking"
Aug 17 14:08:07 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:07+02:00" level=info msg="validator is staking"
Aug 17 14:08:12 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:12+02:00" level=info msg="Client: Status"
Aug 17 14:08:12 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:12+02:00" level=info msg="Client: Status" status="&{{{8 11 0} 705cf3cfe4f75345bc23b>
Aug 17 14:08:12 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:12+02:00" level=info msg="Client: Status" status="&{{{8 11 0} 705cf3cfe4f75345bc23b>
Aug 17 14:08:12 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:12+02:00" level=info msg="checking if validator is staking"
Aug 17 14:08:12 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:12+02:00" level=info msg="validator is staking"
Aug 17 14:08:12 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:12+02:00" level=error msg="incorrect chain" chain-reference-id=matic-main error="Bl>
Aug 17 14:08:12 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:12+02:00" level=error msg="BlockByHash: not found"
Aug 17 14:08:12 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:12+02:00" level=error msg="Failed to execute process: BlockByHash: not found" compo>
Aug 17 14:08:12 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:12+02:00" level=warning msg="Chain infos changed. Building processors..." error="ch>
Aug 17 14:08:12 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:12+02:00" level=info msg="signer loop"
Aug 17 14:08:17 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:17+02:00" level=info msg="Client: Status"
Aug 17 14:08:17 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:17+02:00" level=info msg="Client: Status" status="&{{{8 11 0} 705cf3cfe4f75345bc23b>
Aug 17 14:08:17 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:17+02:00" level=info msg="Client: Status" status="&{{{8 11 0} 705cf3cfe4f75345bc23b>
Aug 17 14:08:17 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:17+02:00" level=info msg="checking if validator is staking"
Aug 17 14:08:17 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:17+02:00" level=info msg="validator is staking"
Aug 17 14:08:22 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:22+02:00" level=info msg="Client: Status"
Aug 17 14:08:22 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:22+02:00" level=info msg="Client: Status" status="&{{{8 11 0} 705cf3cfe4f75345bc23b>
Aug 17 14:08:22 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:22+02:00" level=info msg="Client: Status" status="&{{{8 11 0} 705cf3cfe4f75345bc23b>
Aug 17 14:08:22 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:22+02:00" level=info msg="checking if validator is staking"
Aug 17 14:08:22 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:22+02:00" level=info msg="validator is staking"
Aug 17 14:08:27 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:27+02:00" level=error msg="incorrect chain" chain-reference-id=matic-main error="Bl>
Aug 17 14:08:27 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:27+02:00" level=warning msg="Chain infos changed. Building processors..." error="ch>
Aug 17 14:08:27 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:27+02:00" level=error msg="Failed to execute process: BlockByHash: 504 Gateway Time>
Aug 17 14:08:27 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:27+02:00" level=info msg="event watcher loop" x-correlation-id=cr095evr90be3o9rpqm0
Aug 17 14:08:27 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:27+02:00" level=info msg="Client: Status"
Aug 17 14:08:27 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:27+02:00" level=info msg="Client: Status" status="&{{{8 11 0} 705cf3cfe4f75345bc23b>
Aug 17 14:08:27 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:27+02:00" level=info msg="Client: Status" status="&{{{8 11 0} 705cf3cfe4f75345bc23b>
Aug 17 14:08:27 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:27+02:00" level=info msg="checking if validator is staking"
Aug 17 14:08:27 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:27+02:00" level=info msg="validator is staking"
Aug 17 14:08:27 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:27+02:00" level=info msg="Client: Status"

root@vmi1191487:~# journalctl -fu palomad -o cat
Insufficient watch descriptors available. Reverting to -n.
2:12PM INF trying to deploy smart contract to EVM chain chain-reference-id=bnb-main module=x/evm smart-contract-id=3
2:12PM INF trying to deploy smart contract to EVM chain chain-reference-id=eth-main module=x/evm smart-contract-id=3
2:12PM INF trying to deploy smart contract to EVM chain chain-reference-id=gnosis-main module=x/evm smart-contract-id=3
2:12PM INF trying to deploy smart contract to EVM chain chain-reference-id=matic-main module=x/evm smart-contract-id=3
2:12PM INF trying to deploy smart contract to EVM chain chain-reference-id=op-main module=x/evm smart-contract-id=3
2:12PM INF trying to deploy smart contract to all chains module=x/evm smart-contract-id=3
2:12PM INF finalized block block_app_hash=DC9318E26BE4FA541907673D0C526FF1525B6349A3990B291366A00DD34066A5 height=22165833 module=state num_txs_res=2 num_val_>
2:12PM INF executed block app_hash=DC9318E26BE4FA541907673D0C526FF1525B6349A3990B291366A00DD34066A5 height=22165833 module=state
2:12PM INF committed state block_app_hash=7325B8AED631646B10D57A538F7C746A7330AD3408D79DC57C82BB10F7829993 height=22165833 module=state
2:12PM INF indexed block events height=22165833 module=txindex

My Gnosois RPC: https://lb.nodies.app/v1/d8a9e41bdce243879808c31086d52cfb

root@vmi1191487:~# sudo journalctl -u palomad --since "60 minutes ago" | grep 248883 | grep chain-reference-id
Aug 17 12:44:40 vmi1191487.contaboserver.net palomad[96791]: 12:44PM INF added message evidence. chain-reference-id=gnosis-main chain-type=evm message-id=248883 module=x/palomaconsensus queue-type-name=evm/gnosis-main/validators-balances validator=palomavaloper10d4g6m6tv9y6yr7xn3jkpdz9jek95lc3pkmln4}

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

{WRITE YOUR ANSWER HERE}

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

{WRITE YOUR ANSWER HERE}

**Comment by taariq** [comment]
Please complete all fields in the ticket. It's how we are able to debug.

Also, please add details about the GNOSIS RPC provider you are using.

# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

{WRITE YOUR ANSWER HERE}

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

{WRITE YOUR ANSWER HERE}


# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>


{WRITE YOUR ANSWER HERE}


# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

{WRITE YOUR ANSWER HERE}

**Comment by byte-bandit** [comment]
> Aug 17 14:08:12 vmi1191487.contaboserver.net pigeon[270957]: time="2024-08-17T14:08:12+02:00" level=error msg="incorrect chain" chain-reference-id=matic-main

I'm not convinced this is the culprit, but it'll create other problems for sure. I'd start by making you do not see any error messages like this. Looks like your RPC provider for `matic` wasn't able to sync with the reference block.

**Comment by salihayer** [comment]
I changed matic RPC
