### ISSUE TITLE
bug: node goes to jail because of Gnosis RPC

### ISSUE THREAD

**Issue by cosmoscats** [palomachain/paloma#1265]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

My node goes into jail all the time. When I look at the logs, the reason is that the node is going into jail because of RPC Gnosis.

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

palomad version v1.15.7
pigeon version App version: v1.12.4 Build commit hash: 738bf5dbebfa818de80150ba38b2ab0b95df0166

nano config.yaml
gnosis-main:
    chain-id: 100
    base-rpc-url: ${GNOSIS_RPC_URL}
    keyring-pass-env-name: GNOSIS_PASSWORD
    signing-key: ${GNOSIS_SIGNING_KEY}
    keyring-dir: /home/0/paloma/.pigeon/keys/evm/gnosis-main
    gas-adjustment: 2
    tx-type: 2

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

i just need to unjail and wait for some time and after a while, node goes into jail.
palomad tx slashing unjail --from cc --chain-id=tumbler --fees=3100ugrain

[paloma-log-251659.txt](https://github.com/user-attachments/files/16657092/paloma-log-251659.txt)

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

**Comment by cosmoscats** [comment]
Paloma RPC i have tried: Nodies, Liquify, Dwellir, Chainnodes, drpc, 1rpc.

**Comment by byte-bandit** [comment]
What is the reported jail reason? `palomad q valset get-validator-jail-reason $ADDRESS`

**Comment by cosmoscats** [comment]
> @cosmoscats, also, what's the balance on your GNOSIS address?

you can check it here
its 10XDAI
https://gnosisscan.io/address/0xB66D86b4f926F97D946466027d950552890b3cb0

**Comment by cosmoscats** [comment]
> What is the reported jail reason? `palomad q valset get-validator-jail-reason $ADDRESS`

it shows always problem with Gnosis RPC
i will let you know exactly when next jail will occure.

Today i have changed Gnosis RPC to blastapi & changed gas adjustment to 4 and so far its working good
I will let you know

**Comment by taariq** [comment]
Okay @cosmoscats. We'll close. this. Please re-open if you are still having issues.
