### ISSUE TITLE
bug: pigeon issue leads to jailing on v2.0.0 Failed to execute process: BlockByHash: we can't execute this request

### ISSUE THREAD

**Issue by aditya-manit** [palomachain/paloma#1266]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

`time="2024-08-19T08:50:56Z" level=error msg="Failed to execute process: BlockByHash: we can't execute this request" component=procmon error="BlockByHash: we can't execute this request" process="[Skyway] Sign batches" x-correlation-id=cr1gejh4dbnif281t4ag`

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

App version: v2.0.0
Build commit hash: 45d2fc941ba906f88a9318fada1021a7f0ec054a

**Comment by byte-bandit** [comment]
This is an RPC provider issue.

**Comment by taariq** [comment]
Closing as RPC issue.
