### ISSUE TITLE
Paloma validators are getting jailed

### ISSUE THREAD

**Issue by maharifu** [palomachain/paloma#1299]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Since around last Friday, 20/09 Validators are getting jailed for failing to provide evidence on message attestation. There are some validators reporting RPC issues on the logs, but it doesn't explain the amount of validators being jailed.

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

Started on Paloma/Pigeon v2.2.1 and continues on v2.2.2.

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

{WRITE YOUR ANSWER HERE}

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Pigeons provide evidence for message attestation and do not get jailed.

**Comment by taariq** [comment]
Fied with https://github.com/palomachain/pigeon/pull/441
