### ISSUE TITLE
Keep Alive Failure: out of gas in location: WritePerByte; gasWanted: 128769, gasUsed: 133474: out of gas

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#1305]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Keep Alive Failure: out of gas in location: WritePerByte; gasWanted: 128769, gasUsed: 133474: out of gas
See https://paloma.explorers.guru/transaction/B9FB761043481C3178CC5131630E94FB996555E529C2736C21E09ACE48C914F9?height=24462541

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

Paloma v2.2.2 and Pigeon 2.2.2

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Paloma Pigeon sending Keep Alive messages

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Keep alives do not run out of gas.

**Comment by taariq** [comment]
Fixed with https://github.com/palomachain/pigeon/pull/445

**Comment by maharifu** [comment]
@taariq This was not fixed in the PR. I will revert these changes in the next PR.

The gas-adjustment value is already configurable on pigeon's `config.yaml`. The default value is 3.0, but we should set it to be higher now. I'll adjust it in our validator.

**Comment by maharifu** [comment]
> @maharifu do all validators need to adjust?

@taariq 
Where is this error coming from? I assumed it was our own validator. If not, they need to check the `paloma.gas-adjustment` setting in pigeon config and set it to be a bit higher. Other validators might have a different setting altogether.

**Comment by taariq** [comment]
Good. I'll let the pigeons know. Thank you!
