### ISSUE TITLE
Fork astroport-core to palomadex and upgrade to cosmwasm 1.0.0

### ISSUE THREAD

**Issue by measure-fi** [palomachain/paloma#137]
[EPIC: Astroport Migration](https://www.notion.so/volumefi/EPIC-05-20-Astroport-Migration-to-PalomaDex-to-replace-Palomaswap-5d5105879c484ba2b904da2728773320)

# Background

We need to fork astroport and make it usable on Paloma. This ticket just covers raw version upgrade and related cleanup

# Done when

These packages/contracts are migrated:

- https://github.com/palomachain/palomadex/pull/1
- https://github.com/palomachain/palomadex/pull/2
- https://github.com/palomachain/palomadex/pull/3
- https://github.com/palomachain/palomadex/pull/4
- https://github.com/palomachain/palomadex/pull/5
- https://github.com/palomachain/palomadex/pull/6
- https://github.com/palomachain/palomadex/pull/7
- https://github.com/palomachain/palomadex/pull/8
- https://github.com/palomachain/palomadex/pull/9
- https://github.com/palomachain/palomadex/pull/10
- https://github.com/palomachain/palomadex/pull/11
- https://github.com/palomachain/palomadex/pull/12
- https://github.com/palomachain/palomadex/pull/13
- https://github.com/palomachain/palomadex/pull/14
- https://github.com/palomachain/palomadex/pull/15
- https://github.com/palomachain/palomadex/pull/16

**Comment by taariq** [comment]
@verabehr we added tokenomics so that PalomDEX will have its own token.

**Comment by measure-fi** [comment]
Core migration done. Remaining work broken out into

- https://github.com/palomachain/paloma/issues/163
- https://github.com/palomachain/paloma/issues/164
