### ISSUE TITLE
Validate that palomadex algorithm matches terraswap

### ISSUE THREAD

**Issue by measure-fi** [palomachain/paloma#138]
[EPIC-05-20](https://www.notion.so/volumefi/EPIC-05-20-Astroport-Migration-to-PalomaDex-to-replace-Palomaswap-5d5105879c484ba2b904da2728773320)

# Background

We have made the decision to use ported astroport code instead of ported terraswap code, we need to verify that the new code is doing what we want (matches uniswap).

# Done when

- [ ] a careful manual review of palomadex
- [ ] the validation is justified
- [ ] automated testing ensures these match (optional?)

**Comment by taariq** [comment]
Closing. We are Astroport focused.
