### ISSUE TITLE
bug: unable to find shared library libwasmvm.x86_64.so

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#141]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

When tagging a new release, the binary requires that `libwasmvm.x86_64.so` shared library exists on the machine. 

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

```Dockerfile
FROM ubuntu
COPY ./palomad /paloamd
RUN ./palomad
```

run this dockerfile and take the palomad binary from the release page here on github and it will fail saying that it couldn't load the shared library

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Ideally, the shared library should be (somehow) embedded into the binary or if that fails the shared library should be a part of the release

**Comment by Vizualni** [comment]
Related ticket: #143

**Comment by taariq** [comment]
@Vizualni what's the status of this issue?

**Comment by Vizualni** [comment]
This is still open.

**Comment by taariq** [comment]
This needs to move to Volume.

**Comment by verabehr** [comment]
moved to Volume
