### ISSUE TITLE
Make a decision to choose the underlying database

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#144]
# Background

Copy & paste from Discord:

> @mm a note from @brianosaurus RE: Switch from LevelDB to RocksDB
> The DB was causing a lot of GC, so we moved over to badger first and rocks later. Googling around badger has reports of being faster however this crazy guy (https://github.com/faddat) says rocks is faster. He's totally brilliant - hates IBC! Ha! So do I
> GitHub
> faddat - Overview
> Notional Validators in Cosmos: Coding our way to the top of the validator sets - faddat
> Image
> The pointer issue matters because people periodically hook their local nodes up with the testnet (and sync).

Currently we are on (go)leveldb. The other possibilities are RocksDB and Badger. We should make the analysis to figure out which one is the best for us.

# Done when

- [x] a decision was made to which database to choose

**Comment by taariq** [comment]
Closing. NO change needed.
