### ISSUE TITLE
Consensus module batching to save gas

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#145]
# Background

Given that gas on Etherium is quite expensive we should implement batching of arbitrary items in the consensus module. It should be optional and not every queue item should require. E.g. for now the only usecase is to batch items for the evm arbitrary logic execution.

# Proposal

Instead of simply batching jobs by the time they have arrived, we should give our users a bit more freedom so they could define a minimum batch size they want to be a part of. If there are only 4 jobs in the queue and one of the jobs has a minimum batch size parameter set to 5, they wouldn't be a part of the current batch. If those 3 other jobs have minimum batch size set to <=3, then all those 3 would be a part of a new queue. Given the nature of our scheduler, our customer's jobs could be spawned every couple of minutes and it might be too expensive for them to be "alone" in the batch if they are the only one. With this, we give them control so they can choose the minimum batch size which is the best case for them and how much they are willing to pay for gas.
If one job was too long in the queue because no queue was found, then we give the user control to either: _cancel the job_ or _add it to any available queue of any size_. 
 

# Done when

- [ ] there are new methods in a consensus module that are supporting batching

**Comment by jtremback** [comment]
It's important to keep in mind that the gas savings that are gained by batching are those that are associated with bridge overhead, mostly validator signature evaluation. You might want to think about how much signature evaluation costs in comparison to typical jobs. If the majority of gas costs are incurred by the jobs themselves, this is less useful. 

Another thing to think about is how valuable a typical job is. If the job is very valuable, then gas cost does not matter as much.

Another thing to think about is how timely a typical job must be. If it must be very timely, then the user will not want to risk having to wait for a batch.

I personally would skip this batching idea until you have more information on how useful it would be.

**Comment by jtremback** [comment]
That being said, it seems relatively simple and well suited to the use case.

**Comment by taariq** [comment]
@Vizualni I align here that we may be overoptimizing ahead of getting everything else we need to get done. Although the risk of losing course for Friday is low, let's leave this for after we conclude the current effort. It's a nice-to-have, but not critical and maybe not clear how it will be best used in this moment.

**Comment by Vizualni** [comment]
This is done.
