### ISSUE TITLE
Remove version information from file names in releases

### ISSUE THREAD

**Issue by measure-fi** [palomachain/paloma#148]
# Background

Currently releases include the version in the file name:

```
https://github.com/palomachain/paloma/releases/download/v0.0.1-alphawasmd4/paloma_0.0.1-alphawasmd4_Linux_x86_64.tar.gz
```

I would like to download the latest release generically:

```
wget https://github.com/palomachain/paloma/releases/download/latest/paloma_linux_x86_64.tar.gz
```

# Done when

- [ ] A new release is cut with this scheme
- [ ] Documentation is updated.

**Comment by taariq** [comment]
Closing as wont' fix fo rnow.
