### ISSUE TITLE
Add support for prometheus for Sparrow

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#156]
# Background

We need to give visibility to our validators so they can track the general health of the Sparrow they are running. That way, they can build up their own alarms based on Sparrow's metrics. For example, if Sparrow cannot connect to a certain EVM for some arbitrary reason, they should have a way of knowing this by using metrics that Sparrow is generating and should be able to provide their own alarms. 

# Done when

- [x] prometheus is imported to Sparrow
- [x] critical pieces of code have metrics surrounding them

**Comment by taariq** [comment]
Closing for now.
