### ISSUE TITLE
Add Vyper Logo to the CCC landing page

### ISSUE THREAD

**Issue by drakedukes** [palomachain/paloma#169]
## Description

Please add the below attached logo to the Cross Chain Coalition partners on the Volume site. 

![vyper-logo-transparent](https://user-images.githubusercontent.com/106191376/170728772-b5ea6408-03cb-408c-8867-d66d95d26871.svg)

## What is this needed for

Cause Taariq wants it :)

## Desired launch date

When Possible

## Additional context

None

**Comment by verabehr** [comment]
won't do
