### ISSUE TITLE
Kallisto Front-end. Add Liquidity

### ISSUE THREAD

**Issue by joycehermosilla** [palomachain/paloma#171]
**1.3.2 ADD LIQUIDITY:**
The user will be able to add Liquidity with the tokens of the pool and also with stable coins like: WETH, stETH, USDT, wBTC, DAI, USDC, cDAI, cUSDT, renBTC, FRAX, MIM, alETH.

User can choose between the tokens that he/she has balance ONLY. The tokens will be ordered from higher to lower balances.

****If the user selects a token that is not in the Pool, Kallisto will calculate the best route for swap.

**Button/CTA:**

**If user didn't input any amount button will show: "Enter an amount"** https://www.figma.com/file/H6AoLtZVyRcxCTmm37JtW0/Kallisto?node-id=2445%3A918
**If user input an amount but is not enough balance will show: "Insufficient Amount"** https://www.figma.com/file/H6AoLtZVyRcxCTmm37JtW0/Kallisto?node-id=2445%3A919
**If user input an amount and the balance is enough will show: "Add Liquidity"** https://www.figma.com/file/H6AoLtZVyRcxCTmm37JtW0/Kallisto?node-id=2445%3A925

**1.3.3 CONFIRM ADD LIQUIDITY**
https://www.figma.com/file/H6AoLtZVyRcxCTmm37JtW0/Kallisto?node-id=2472%3A911

A user that presses Add Liquidity will be redirected to a Confirmation view with the details of the deposit.

Acceptance Criteria:

Show amount in token selected, token selected, EDIT button, % of the Pool.
If the user selects a token that is needed to do a swap we will show a Swapping disclaimer.

**Comment by verabehr** [comment]
As per Strategy Sunday, if we can't land the best swapping feature by Friday, we will leave it out, so we can launch the vault on Friday.
