### ISSUE TITLE
Kallisto Curve APY Chase Smart contract

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#176]
Background: https://www.notion.so/volumefi/EPIC-05-20-Kallisto-Curve-dynamic-APY-chaser-vault-e532201ab17242eb841f468975dda421

Done when

- [ ]  we have a Vyper contract with the functions specified
- [x]  tests for all functions in the contract
- [x]  documentation of the functions and tests - see example from Sommelier https://github.com/VolumeFi/cellars

**Comment by taariq** [comment]
@wc117 This ticket does not include the flashloan attack mitigation work you are doing right now. That will require a separate ticket. Please create one accordingly in the same format above.
