### ISSUE TITLE
Kallisto make fee scheduler for Curve APY Chaser vault

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#180]
### Background
https://www.notion.so/volumefi/EPIC-06-03-Scheduler-for-Kallisto-Curve-APY-Chaser-vault-ed42c2cf33414f00b3b56d34bf101f84 Make fee story

### Done when

- [ ] script and cron job are set up with logging
- [ ] script was tested
- [ ] code is commented

**Comment by rootedbox** [comment]
I've created a repo to support this https://github.com/kallisto-finance/update_pool

**Comment by verabehr** [comment]
This is no longer applicable. Will close this ticket as won't do.
