### ISSUE TITLE
Need to add these 3 logos to the Cross Chain House Party Digital Banner for Luma (Flipp, Kadena, CoinFX)

### ISSUE THREAD

**Issue by drakedukes** [palomachain/paloma#186]
## Description

Need to add these 3 logos to the Cross Chain House Party Digital Banner for Luma (Flipp, Kadena, CoinFX)

## What is this needed for

They all paid money to be added lol

## Desired launch date

EOD Friday or Monday morning

## Additional context

[PHLIPIO-LOGO-WHITE.pdf](https://github.com/palomachain/paloma/files/8828817/PHLIPIO-LOGO-WHITE.pdf)
![CoinFX Logo](https://user-images.githubusercontent.com/106191376/171767623-169f3a52-1e76-43db-8081-30d127abcb8d.jpg)
![Kadena logo](https://user-images.githubusercontent.com/106191376/171767624-b1818449-546e-41e8-bacb-077d1bb5c94d.jpg)

**Comment by drakedukes** [comment]
[PHLIPIO-LOGO-WHITE.pdf](https://github.com/palomachain/paloma/files/8828819/PHLIPIO-LOGO-WHITE.pdf)

**Comment by joycehermosilla** [comment]
@verabehr Logos Images:
![Phlip io](https://user-images.githubusercontent.com/22323189/171901794-752c52ad-c220-448b-9d40-0ce73ddc05d1.png
![Kadena](https://user-images.githubusercontent.com/22323189/171901806-36c5c151-0c9d-4228-8334-b86dba2ff536.png)
)
![Coinfx](https://user-images.githubusercontent.com/22323189/171901848-881ee60e-7cb5-40a2-bd3f-601490a2213b.png)

**Comment by drakedukes** [comment]
@verabehr @joycehermosilla where can i find the updated banner for this? Need to swap it out on the Luma link with the 3 new logos.
