### ISSUE TITLE
Valset support for EVM chains

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#189]
# Background

Valset for EVM requires that we always send them which does not work the same for cosmos for which Valsets were originally written. We need to add support for the EVM chains as well and use github.com/palomachain/turnstone-evm which has this written down.

# Done when

- [x] a checkpointing logic for valsets is written down both in Paloma and Sparrow
  - [x] a new query endpoint in paloma to get the valset info
- [x] Valsets are sent on every request to turnstone-evm when upading valsets and when running arbitrary logic calls

**Comment by taariq** [comment]
@Vizualni I would recommend checking https://github.com/PeggyJV/gravity-bridge/pull/401 for some ides on how others have handled multi EVM messaging
