### ISSUE TITLE
Clarify workflow for resetting palomad

### ISSUE THREAD

**Issue by measure-fi** [palomachain/paloma#202]
# Background

Expected workflow (per @taariq) is
```
rm -r .paloma/data && service palomad restart
```

This currently deletes `priv_validator_state.json`, which causes the service to fail upon restart. This may simply be a documentation issue.

# Done when

- [ ] it is easy to restart a service after blowing away the db.

**Comment by verabehr** [comment]
`palomad tendermint unsafe-reset-all` is the command that we've been using instead which works
