### ISSUE TITLE
Create a faucet for testnet

### ISSUE THREAD

**Issue by measure-fi** [palomachain/paloma#205]
https://www.notion.so/volumefi/EPIC-06-17-Paloma-Public-Testnest-1-d11ce23143c7475a9157acd224933d81

# Background

The current workflow is to reach out to whoever's running the "main node" and ask them for grain. It needs to be significantly easier.
https://www.notion.so/volumefi/EPIC-06-24-Faucet-for-Paloma-1143e7e3e3a841dc8aa9e2f93cff3c73

# Done when

- [x] grain can be handed out on testnet as if it were candy without human involvement
- [ ] FE has the Paloma colors and logo

**Comment by verabehr** [comment]
Terra implemented a fork of the original Cosmos faucet - https://github.com/terra-money/faucet. This should give us all we need. Osmosis also has a faucet, but more complicated features, that we don't need atm.

**Comment by measure-fi** [comment]
Current backend updates: https://github.com/palomachain/pyfaucet/commit/3964581

**Comment by measure-fi** [comment]
@Vizualni writes: it's working now

🎉
