### ISSUE TITLE
Cross Chain Weekly #3

### ISSUE THREAD

**Issue by drakedukes** [palomachain/paloma#206]
## Description

_A clear and concise description of what you need._
Change # to #3. And add Kadena, CoinFX and Phlip logos.

## What is this needed for
Cross Chain Weekly Newsletter #3 

_Explain why this is needed._
Another Wednesday morning send! 

## Desired launch date
June 8th before 9am CT

_Provide target launch date._

## Additional context

_Add any other context, links to assets here._
![CCC3](https://user-images.githubusercontent.com/106191376/172476214-31a97630-f318-44b1-8685-6f37a4b30c89.png)

**Comment by verabehr** [comment]
Joyce did this already 💨 😃
