### ISSUE TITLE
bug: turnstone-evm readme events section is not up to date

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#217]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Turnstone-evm readme is not showing real events that it's emitting.

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

https://github.com/palomachain/turnstone-evm#events

Check the events heading. It doesn't match what the code does.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

It should document events that turnstone-evm is actually emitting.

**Comment by verabehr** [comment]
@Vizualni @webelf101 should this be closed? I see status is done

**Comment by Vizualni** [comment]
Yep. @webelf101 feel free to close the github issue once you are done with it :)
