### ISSUE TITLE
Add validation that EVM arbitrary logic call can't exceed 20kb.

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#219]
# Background

There needs to be a limit and we are setting it to 20kb.

# Done when

- [ ] there is a check in ValidateBasic to fail if the size is greater than 20kb

**Comment by verabehr** [comment]
@Vizualni Is this still open?

**Comment by Vizualni** [comment]
@verabehr yep.

**Comment by verabehr** [comment]
moved to Volume
