### ISSUE TITLE
Add artefact caching on github for Go builds & tests

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#22]
# Background

Currently, when running tests, go needs to download all dependencies. This takes about 1min and 40seconds on our CI. 

# Proposed solution

Add [action/cache](https://github.com/actions/cache) in between multiple runs to speed up the tests.

**Comment by taariq** [comment]
@mszuyev maybe good optimization for speed.

**Comment by verabehr** [comment]
Moved to Volume
