### ISSUE TITLE
As a user, I want to know that 1,000,000 uGrains == 1 Grain

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#224]
# Background

Currently, we do not have a clear way to show that 1 GRAN = 1,000,000 uGrains
Suggest we add the base denom as uGRAINS

# Done when

- [ ] create denom for uGRAINS to represent 1 / 1,000,000 tokens
- [x] confirm that 1 GRAIN = 1,000,000 uGrains

**Comment by measure-fi** [comment]
Via @Vizualni 

> I don't think that we can define the minimum prefix denom, but rather the cosmos sdk will take care of the conversion. I had though that we need to define this in the genesis file, but seeing that you folks were already using ugrain and that it works it seems that we don't need to make any changes.
