### ISSUE TITLE
Contract for Minting NFT's for testnet

### ISSUE THREAD

**Issue by measure-fi** [palomachain/paloma#230]
[Egg Epic](https://www.notion.so/volumefi/EPIC-06-24-Paloma-Egg-mint-7ebae048c20b4150ad16e51646001ceb)

# Background
https://www.notion.so/volumefi/EPIC-06-24-Paloma-Egg-mint-7ebae048c20b4150ad16e51646001ceb
Create a contract for calling the ETH egg minting contract.

# Done when

- https://github.com/palomachain/palomadex/pull/30

**Comment by taariq** [comment]
@measure-fi we need to update the cost of using the contract from 100,000 GRAINs to 1 GRAIN.
