### ISSUE TITLE
Propagate kallisto statistics to redis/frontend

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#235]
As Kallisto team, I want the monitor.py script to be run every 5 minutes, so the performance numbers of the vault are stored in redis and are accessible to the FE. 
Acceptance Criteria
* Cron job that runs every 5 minutes on the Kallisto server
* cron job executes https://github.com/VolumeFi/volume_ds/blob/main/scripts/monitor.py
   * note that the script runs with pipenv shell - see https://github.com/VolumeFi/volume_ds#how-to-run-the-python-code

**Comment by rootedbox** [comment]
currently getting the following 

rootedbox@terra-services:~/service/volume_ds/scripts$ /home/rootedbox/.pyenv/shims/pipenv run python ./monitor.py
Loading .env environment variables...
/home/rootedbox/service/volume_ds/volume_ds /home/rootedbox/service/volume_ds
0x214ed7f6ac72582ccf97305a65a28e869db6615eb6e4a2b98a3f557456037192 failed invalid syntax (<string>, line 1)
0xc7829fb20ac4b4ca50257bcd622092f4400c8662b6df4f5a7224f683bee2d581 failed name 'false' is not defined
0x63c888612d1f01f289a3b61f2e0d9f00f30ba9c9409da091db1b03a6128d499d failed name 'false' is not defined
0x3e1bc954ef4bfa24a5b016c6f66745aec72c60bf68722cf8b5954484a0bc201a failed name 'false' is not defined
0x2e66bce4fc876537f31655e98ef21a7bf239175ebcfede17c29c89f2c1803720 failed name 'false' is not defined
0xa7362577f8378cc35445d2e8ff11bd6395a5a94c861758df084e22df3ae72838 failed name 'false' is not defined
0x71505cbea3122cef3772631b630794510b69902aa12419bd2b7c541f2dfaa45a failed name 'true' is not defined
0x290166d82d144424c62dcf5c10c3b5b0a28ea091a6b300832a99bae0a4b5ee37 failed name 'true' is not defined
0x791572c84d4ad6b16085c59e6443329446ae5945bb60d33cc215dff83f062995 failed name 'false' is not defined
0x4432eca5e8ad34bda61ba5df8ac99f431ffc01ad699b4bde8286974395fbdb3b failed name 'false' is not defined
0x338d40dfcbede5ee6c77ddea37fd3291199a0111b73c711650ad8a2ad17f7c04 failed name 'false' is not defined
0x7db8e196ad6ad2793486d6ec547a2e204831ee1205a79dd73e5af674b11b8932 failed name 'false' is not defined
0x1efa36fb9b113a3e6faf89ce840431b8a9801d941b9f8a016ef45ff5247a14c6 failed name 'false' is not defined
0x8f24b864179743259bb90ab3d7427504d074bd62569ac272a8e2440a14972b20 failed name 'false' is not defined
0x9fb4f37c8a5b08c438035627ea0bbbf79406484aba4bae5ac9abfed3e9c879fa failed name 'false' is not defined
0xb2b72fe0797a61addf726aa0ab00e453480f19da73356daf026a560c1228772f failed name 'true' is not defined
0xe0afbf7f43161251b0aaf21ea0c748214321db5d3b304fd6c8ee8c84b135b03d failed name 'false' is not defined
Traceback (most recent call last):
  File "/home/rootedbox/service/volume_ds/scripts/./monitor.py", line 141, in <module>
    parsed_txs = get_txs(VAULT_ADDRESS)
  File "/home/rootedbox/service/volume_ds/scripts/./monitor.py", line 55, in get_txs
    parsed_txs['token_decimal'] = parsed_txs['token'].apply(lambda x: 10**token_decimals[x])
  File "/home/rootedbox/.local/share/virtualenvs/volume_ds-aUHxqsEC/lib/python3.10/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/home/rootedbox/.local/share/virtualenvs/volume_ds-aUHxqsEC/lib/python3.10/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/home/rootedbox/.local/share/virtualenvs/volume_ds-aUHxqsEC/lib/python3.10/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/home/rootedbox/service/volume_ds/scripts/./monitor.py", line 55, in <lambda>
    parsed_txs['token_decimal'] = parsed_txs['token'].apply(lambda x: 10**token_decimals[x])
KeyError: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48'

**Comment by rootedbox** [comment]
@fieldtheory123

**Comment by rootedbox** [comment]
Up and running with cron.
