### ISSUE TITLE
Update testnet with new values

### ISSUE THREAD

**Issue by measure-fi** [palomachain/paloma#246]
# Background

We have a laundry list of items which need to go into the new testnet.

# Done when

- [x]  New Validator Set whitelist (internal only - Taariq, Chase, Jason, Vera)
- [x]  updated genesis file with starting grains for Volume users and validators
    - [x]  5 Billion GRAINs at genesis
    - [x]  250MM Grains each to control network
        - [x]  Jason Address
        - [x]  Vera Address
        - [x]  Chase Address
        - [x]  Taariq Address
- [x]  Server Size: 16 GB RAM
- [x]  Starting Addrbook: Post to Github
    - [https://github.com/palomachain/testnet/blob/master/passerina/addrbook.json](https://github.com/palomachain/testnet/blob/master/passerina/addrbook.json)
- [x]  Faucet: 500MM
    - [x]  Faucet: 100,000 GRAINs
    - [x]  CLI faucet
    - [x]  Faucet Front-end

**Comment by taariq** [comment]
@measure-fi can we do another checklist for today's testnet?
1.  Updated Chain-ID to be announced at genesis
2. Updated Validator Minimum for staking: 1 GRAIN
3. Updated Denoms for GRAINs:  1 GRAIN == 1,000,000 ugrain

**Comment by measure-fi** [comment]
@taariq https://github.com/palomachain/paloma/issues/247
