### ISSUE TITLE
Communicate with the EVM from the CosmWasm smart contract

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#262]
# Background

We want our smart contracts to be able to communicate with the outside world. This issue will allow us to define any arbitrary smart contract on EVM (networks that we support) and to execute them using Paloma.
This way of defining any arbitrary smart contract is temporary only, as developers should refer to jobs defined in paloma (once there are jobs). Right now, this is something for us to play with and see the limitations.

# Done when
- [x] https://github.com/palomachain/palomadex/pull/29
- [x] we can call an EVM smart contract from our own CosmWasm smart contracts

**Comment by measure-fi** [comment]
@Vizualni Is this done?

**Comment by Vizualni** [comment]
> @Vizualni Is this done?

I'd say so. If you are happy with how things are looking on the rust side of things, you are free to close this.
