### ISSUE TITLE
Volume website - updates needed for launch

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#271]
- [x]  In the investor logos the Solana is not the right size and New Form is another color. Please replace logos for: https://drive.google.com/drive/u/1/folders/1Z6bHl-dQjNsLNVLQSJADoJurmbwN9TpF
- [x]  Crosschain Coalition logos. Please use: https://drive.google.com/drive/u/0/folders/1nLtQnSFmyPi2INKJ8Sv9yho-FeOU8o_N Please add 70% opacity.
- [x]  Cross-chain Weekly. We need to connect the button "Subscribe" to the database of the Newsletter.
- [x]  Update Taariq and Vera picture to: https://drive.google.com/drive/u/0/folders/19zthOR0m-7QDEbZefpIabIGNtTTsEtWn

**Comment by joycehermosilla** [comment]
@verabehr @wdev733 here are: https://drive.google.com/drive/u/0/folders/19zthOR0m-7QDEbZefpIabIGNtTTsEtWn
