### ISSUE TITLE
Default EVM chains to add to default genesis

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#294]
# Background

Adding starting EVM chains to genesis file.

# Done when

- [x] genesis state for EVM module supports adding EVMs to it
- [x] genesis state with starting smart contract info is made
- [ ] when `Avalanche, Harmony, xDai, Moonbeam, Aurora, Ethereum, Optimism, Arbitrum, Fantom, and Polygon` are added to default genesis

**Comment by taariq** [comment]
This is awesome. 
1. We will upgrade the Vyper contract and then deploy them.
