### ISSUE TITLE
Gas management - first step

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#298]
# Background

Paloma's pigeons will spend their own $ to execute commands on external chains and on paloma as well. Given that they are servicing paloma's customers and customers are paying paloma to do this, paloma should keep track of the gas that's being spent by the pigeons so that paloma can return pigeons their gas $ back.

# Done when

- [ ] during the attestation for events, log the gas that was spend by the validator
- [ ] when running the tx in the paloma which are used for the "business" work only (things like signing messages, sending attestaiton proofs,.etc) we should keep track of the gas spent

# Not part of this ticket

- [ ] sending $$ to validator's wallets

**Comment by verabehr** [comment]
Closing until we restart
