### ISSUE TITLE
As a User I want to be sure that my JOB (message) has been submitted to the Network for Consensu so that it will be executed.

### ISSUE THREAD

**Issue by nikolasschoppmeier** [palomachain/paloma#3]
1. **Acceptance Criteria**
    1. Some sort of logic to assign Jobs to Validators (TBD) 
    2. Ability to keep track of which jobs are active and which ones are inactive
    3. Given a list of active jobs find jobs which need to get executed next

**Comment by taariq** [comment]
Closing as delivered.
