### ISSUE TITLE
bug: block range is too wide error running pigeon v0.2.5-prealpha

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#314]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Running pigeon v0.2.5-prealpha intermittently gives the following error 
`level=error msg="error while trying to relay messages" err="there are 200 errors in the group:` ....`error 156: there are 1 errors in the group:\nerror  1: block range is too wide\n\nerror 157: there are 1 errors in the group:\nerror  1: block range is too wide\n\n`...

EVM endpoint: https://rpc.ankr.com/eth
validator: newbird
running node on Linode.com server with Ubuntu 22.04 LTS

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

run pigeon with systemd

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

no errors?

**Comment by Vizualni** [comment]
This was fixed with https://github.com/palomachain/pigeon/pull/42.
