### ISSUE TITLE
No contact code at given address

### ISSUE THREAD

**Issue by D-Elektra** [palomachain/paloma#316]
First, it was quite stable. 
<img width="1155" alt="Снимок экрана 2022-07-09 в 7 42 00 AM" src="https://user-images.githubusercontent.com/87807935/178084455-ea66e0a6-ff0d-4e9c-a9aa-dcf751195b47.png">

But now every hour I get this and have to restart the pigeon

<img width="1145" alt="Снимок экрана 2022-07-09 в 7 57 15 AM" src="https://user-images.githubusercontent.com/87807935/178084544-ab57c4a8-0e7c-4b30-9e1b-f0fe654e9a50.png">

**Comment by taariq** [comment]
Pigeon exits on this error.

**Comment by D-Elektra** [comment]
What might cause it? And how to prevent it?

**Comment by verabehr** [comment]
we have moved on from this error - closing
