### ISSUE TITLE
bug: "can not add field \"signer\"" && "no contract code at given address"

### ISSUE THREAD

**Issue by andrii1890** [palomachain/paloma#318]
its starting from:
*chirp chirp*
time="2022-07-09T11:23:36Z" level=info msg="starting relayer"
time="2022-07-09T11:23:46Z" level=info msg="relayer loop"
time="2022-07-09T11:23:46Z" level=info msg="messages to sign" message-ids="[]" processor-chain-id=eth-main queue-name="EVM:eth-main:evm-turnstone-message"
time="2022-07-09T11:23:46Z" level=info msg="relaying messages" messages-to-relay="[1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99 101 103 105 107 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179 181 183 185 187 189 191 193 195 197 199 201 203 205 207 209 211 213 215 217 219 221 223 225 227 229 231 233 235 237 239 241 243 245 247 249 251 253 255 257 259 261 263 265 267 269 271 273 275 277 279 281 283 285 287 289 291 293 295 297 299 301 303 305 307 309 311 313 315 317 319 321 323 325 327 329 331 333 335 337 339 341 343 345 347 349 351 353 355 357 359 361 363 365 367 369 371 373 375 377 379 381 383 385 387 389 391 393 395 397 399]" processor-chain-id=eth-main queue-name="EVM:eth-main:evm-turnstone-message"
time="2022-07-09T11:23:46Z" level=info msg=processing msg-id=1 processor-chain-id=eth-main queue-name="EVM:eth-main:evm-turnstone-message"
time="2022-07-09T11:23:46Z" level=info msg="suggested gas price" arguments="[{{[0x5b466c5a56EcaD0eeA2AeedE2F07B3E29433Dba4] [4294967296] 7362} [28 114013943974811241044562098422999270537321466651144900111117918115973783665788 1654046723923993781997456517898973377652027574667822055496338558915476175150]} {[] [] 1}]" chain-id=1 contract-addr=0x0000000000000000000000000000000000000000 gas-adjustments=0 method=update_valset signing-addr=0x11b6c349D67244e2d62D1CB2f8460226b492CcEb suggested-gas-price=2975167732555623
time="2022-07-09T11:23:46Z" level=info msg="executing tx" logrus_error="can not add field \"signer\"" arguments="[{{[0x5b466c5a56EcaD0eeA2AeedE2F07B3E29433Dba4] [4294967296] 7362} [28 114013943974811241044562098422999270537321466651144900111117918115973783665788 1654046723923993781997456517898973377652027574667822055496338558915476175150]} {[] [] 1}]" chain-id=1 contract-addr=0x0000000000000000000000000000000000000000 from=0x11b6c349D67244e2d62D1CB2f8460226b492CcEb gas-adjustments=0 gas-limit=0 gas-price=2975167732555623 method=update_valset nonce=0 signing-addr=0x11b6c349D67244e2d62D1CB2f8460226b492CcEb
time="2022-07-09T11:23:46Z" level=info msg=processing msg-id=3 processor-chain-id=eth-main queue-name="EVM:eth-main:evm-turnstone-message"
time="2022-07-09T11:23:46Z" level=info msg="suggested gas price" arguments="[{{[0x5b466c5a56EcaD0eeA2AeedE2F07B3E29433Dba4] [4294967296] 7362} [28 71216039469225309068738709998279726467546539376093188808203398004543041274596 18587963085448530327091923875974763577911082575662195983429589761917997849135]} {[] [] 2}]" chain-id=1 contract-addr=0x0000000000000000000000000000000000000000 gas-adjustments=0 method=update_valset signing-addr=0x11b6c349D67244e2d62D1CB2f8460226b492CcEb suggested-gas-price=2975175865316470
time="2022-07-09T11:23:46Z" level=info msg="executing tx" logrus_error="can not add field \"signer\"" arguments="[{{[0x5b466c5a56EcaD0eeA2AeedE2F07B3E29433Dba4] [4294967296] 7362} [28 71216039469225309068738709998279726467546539376093188808203398004543041274596 18587963085448530327091923875974763577911082575662195983429589761917997849135]} {[] [] 2}]" chain-id=1 contract-addr=0x0000000000000000000000000000000000000000 from=0x11b6c349D67244e2d62D1CB2f8460226b492CcEb gas-adjustments=0 gas-limit=0 gas-price=2975175865316470 method=update_valset nonce=0 signing-addr=0x11b6c349D67244e2d62D1CB2f8460226b492CcEb
time="2022-07-09T11:23:46Z" level=info msg=processing msg-id=5 processor-chain-id=eth-main queue-name="EVM:eth-main:evm-turnstone-message"
time="2022-07-09T11:23:47Z" level=info msg="suggested gas price" arguments="[{{[0x5b466c5a56EcaD0eeA2AeedE2F07B3E29433Dba4] [4294967296] 7362} [27 97263308363348244215385702757975328630830008515546542071732038989110632835726 21728780340349952864075215441687553430926774062043538903231517942467434707057]} {[] [] 3}]" chain-id=1 contract-addr=0x0000000000000000000000000000000000000000 gas-adjustments=0 method=update_valset signing-addr=0x11b6c349D67244e2d62D1CB2f8460226b492CcEb suggested-gas-price=2975183998077317
time="2022-07-09T11:23:47Z" level=info msg="executing tx" logrus_error="can not add field \"signer\"" arguments="[{{[0x5b466c5a56EcaD0eeA2AeedE2F07B3E29433Dba4] [4294967296] 7362} [27 97263308363348244215385702757975328630830008515546542071732038989110632835726 21728780340349952864075215441687553430926774062043538903231517942467434707057]} {[] [] 3}]" chain-id=1 contract-addr=0x0000000000000000000000000000000000000000 from=0x11b6c349D67244e2d62D1CB2f8460226b492CcEb gas-adjustments=0 gas-limit=0 gas-price=2975183998077317 method=update_valset nonce=0 signing-addr=0x11b6c349D67244e2d62D1CB2f8460226b492CcEb
time="2022-07-09T11:23:47Z" level=info msg=processing msg-id=7 processor-chain-id=eth-main queue-name="EVM:eth-main:evm-turnstone-message"

after 1 min it's crash:

time="2022-07-09T11:28:19Z" level=error msg="error relaying messages" err="there are 100 errors in the group:\nerror  
1: no contract code at given address\nerror  
2: no contract code at given address\nerror  
3: no contract code at given address\nerror 
.......
error 97: no contract code at given address
error 98: no contract code at given address
error 99: no contract code at given address
error 100: no contract code at given address
wrapped error: unrecoverable error
goroutine 1 [running]:
main.main()
        /app/cmd/pigeon/main.go:5 +0x45

**Comment by Vizualni** [comment]
Thanks for reporting. This was fixed in https://github.com/palomachain/pigeon/pull/42
