### ISSUE TITLE
bug: periodically pigeon fall down

### ISSUE THREAD

**Issue by VitaValeriya** [palomachain/paloma#319]
periodically pigeon fall down with this errors:
![no contract code at given address](https://user-images.githubusercontent.com/103098993/178103889-76de463f-b955-4d69-9e6c-323d8aabbb88.png)
Then I restart the pigeon and it works for a while:
![Безымянный](https://user-images.githubusercontent.com/103098993/178104036-42ad1430-84c4-45a5-91e2-472c957e8c89.png)
Then crashes again with the same error.
I use Endpoint Etherium mainnet on Alchemy

**Comment by CoreDov** [comment]
Its known issue. Paloma team now fixing this problem. Wait for announcement in telegram)

**Comment by Vizualni** [comment]
Hey @VitaValeriya . Thanks for reporting. Please try with version v0.3.2 and if this happens again, feel free to open a new issue with a bit more context :)
