### ISSUE TITLE
Feature: EVM ABI and bytecode-hex file requests for palomad governance EVM commands

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#322]
# Background

As a user, when I am proposing a new smart contract with the CLI command ```palomad tx gov submit-proposal evm propose-new-smart-contract ```, I want to be able to reference a file for my abi.json and bytecode-hex instead of pasting the entire abi and bytecode into the line command so that my CLI commands are cleaner and easier to build and then review.

# Done when

- [ ] Implement file input handling for abi and bytecode hex inputs for palomad evm governance commands.

**Comment by verabehr** [comment]
complete
