### ISSUE TITLE
faucet is not working 

### ISSUE THREAD

**Issue by NataliiaS27** [palomachain/paloma#323]
https://faucet.palomaswap.com/ - The site doesn't load at all, just a white screen
I would be grateful for test tokens to create a validator paloma194ta89asausdmdcqtg8tdttkk9lkzxsqkcz75h

**Comment by taariq** [comment]
@rootedbox

**Comment by verabehr** [comment]
This has been fixed

**Comment by verabehr** [comment]
site is back up, but node is not yet synced, keeping open for now
