### ISSUE TITLE
Add TVL to the Kallisto API

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#325]
### Background
https://www.notion.so/volumefi/EPIC-07-15-Correct-and-improved-rewards-for-Kallisto-Curve-APY-chaser-f1bf30f1ca984496bcd3aeb62126fd2e#2c71813f4c474b57839c2fb6aab1c85f

### Done when

- [ ] FE TVL number comes from the update_pool script calculation

**Comment by taariq** [comment]
Closing as won't add.
