### ISSUE TITLE
Upgrade app.go with upgrade handler using the semver of the current app

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#329]
# Background

TODO:

https://github.com/palomachain/paloma/blob/d9731ff5c2caf4f81ad6d8c15dd5f80544ae0e61/app/app.go#L350-L352

s/palomad/app.Version()/ simplified

# Done when

- [ ] a list of items, when checked, this ticket should be considered to be finished

**Comment by verabehr** [comment]
moved to Volume
