### ISSUE TITLE
pigeon bug "relayer loop"

### ISSUE THREAD

**Issue by andrii1890** [palomachain/paloma#330]
Hi. I use different port from default, in pigeon config.yaml  base-rpc-url: http://127.0.0.1:10657
but get such error

paloma@node05:~$ pigeon start
*chirp chirp*
INFO[0000]/app/relayer/start.go:21 github.com/palomachain/pigeon/relayer.(*Relayer).Start() starting relayer
INFO[0010]/app/relayer/start.go:49 github.com/palomachain/pigeon/relayer.(*Relayer).Start() relayer loop
INFO[0020]/app/relayer/start.go:49 github.com/palomachain/pigeon/relayer.(*Relayer).Start() relayer loop
INFO[0030]/app/relayer/start.go:49 github.com/palomachain/pigeon/relayer.(*Relayer).Start() relayer loop
INFO[0040]/app/relayer/start.go:49 github.com/palomachain/pigeon/relayer.(*Relayer).Start() relayer loop
INFO[0050]/app/relayer/start.go:49 github.com/palomachain/pigeon/relayer.(*Relayer).Start() relayer loop
INFO[0060]/app/relayer/start.go:49 github.com/palomachain/pigeon/relayer.(*Relayer).Start() relayer loop
INFO[0070]/app/relayer/start.go:49 github.com/palomachain/pigeon/relayer.(*Relayer).Start() relayer loop
INFO[0080]/app/relayer/start.go:49 github.com/palomachain/pigeon/relayer.(*Relayer).Start() relayer loop
INFO[0090]/app/relayer/start.go:49 github.com/palomachain/pigeon/relayer.(*Relayer).Start() relayer loop
INFO[0100]/app/relayer/start.go:49 github.com/palomachain/pigeon/relayer.(*Relayer).Start() relayer loop
INFO[0110]/app/relayer/start.go:49 github.com/palomachain/pigeon/relayer.(*Relayer).Start() relayer loop
INFO[0120]/app/relayer/start.go:49 github.com/palomachain/pigeon/relayer.(*Relayer).Start() relayer loop
Error: post failed: Post "http://127.0.0.1:10657": EOF
panic: post failed: Post "http://127.0.0.1:10657": EOF

goroutine 1 [running]:
main.main()
        /app/cmd/pigeon/main.go:22 +0x85

palomad listen on 10657 port

paloma@node05: sudo ss -tulpn | grep paloma
tcp   LISTEN 0      4096       127.0.0.1:10657      0.0.0.0:*    users:(("palomad",pid=70351,fd=50))
tcp   LISTEN 0      4096       127.0.0.1:10060      0.0.0.0:*    users:(("palomad",pid=70351,fd=51))
tcp   LISTEN 0      4096               *:10656            *:*    users:(("palomad",pid=70351,fd=52))
tcp   LISTEN 0      4096               *:10090            *:*    users:(("palomad",pid=70351,fd=62))
tcp   LISTEN 0      4096               *:10091            *:*    users:(("palomad",pid=70351,fd=14))
paloma@node05:~$

**Comment by Vizualni** [comment]
Please follow the structure of a bug report: https://github.com/palomachain/paloma/issues/new?assignees=&labels=bug&template=bug_report.md&title=bug%3A+what+is+happening. Provide your config files as well.

**Comment by Vizualni** [comment]
Doesn't really seem to be pigeon related. Closing this as there is not enough context.
