### ISSUE TITLE
bug: Main process exited, code=exited, status=2/INVALIDARGUMENT

### ISSUE THREAD

**Issue by mesahin001** [palomachain/paloma#339]
# Pigeon service crashes sometimes with this error and than starts itself:

Jul 22 21:12:19 vmd94125.contaboserver.net pigeon[19154]: wrapped error: unrecoverable error
Jul 22 21:12:19 vmd94125.contaboserver.net pigeon[19154]: goroutine 1 [running]:
Jul 22 21:12:19 vmd94125.contaboserver.net pigeon[19154]: main.main()
Jul 22 21:12:19 vmd94125.contaboserver.net pigeon[19154]:         /app/cmd/pigeon/main.go:22 +0x85
Jul 22 21:12:19 vmd94125.contaboserver.net systemd[1]: pigeond.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 22 21:12:19 vmd94125.contaboserver.net systemd[1]: pigeond.service: Failed with result 'exit-code'.
Jul 22 21:12:25 vmd94125.contaboserver.net systemd[1]: pigeond.service: Scheduled restart job, restart counter is at 21.
Jul 22 21:12:25 vmd94125.contaboserver.net systemd[1]: Stopped Pigeon daemon.
Jul 22 21:12:25 vmd94125.contaboserver.net systemd[1]: Started Pigeon daemon.
Jul 22 21:12:25 vmd94125.contaboserver.net pigeon[19653]: *chirp chirp*

**Comment by taariq** [comment]
@mesahin001 what version of palomad and what version pigeon are you running?

**Comment by mesahin001** [comment]
> @mesahin001 what version of palomad and what version pigeon are you running?

palomad version: v0.3.0-alpha
pigeon version: App version: v0.3.1 - Build commit hash: 624fe0ba69c23ee379963087e7f985c635a76ea7

**Comment by taariq** [comment]
I was able to repro this as well with the following version:

palomad version: v0.3.0-alpha
pigeon version: App version: v0.3.1 - Build commit hash: 624fe0ba69c23ee379963087e7f985c635a76ea7

```
Jul 23 06:33:29 vultr pigeon[76426]: error 97: insufficient funds for transfer
Jul 23 06:33:29 vultr pigeon[76426]: error 98: insufficient funds for transfer
Jul 23 06:33:29 vultr pigeon[76426]: error 99: insufficient funds for transfer
Jul 23 06:33:29 vultr pigeon[76426]: error 100: insufficient funds for transfer
Jul 23 06:33:29 vultr pigeon[76426]: wrapped error: unrecoverable error
Jul 23 06:33:29 vultr pigeon[76426]: goroutine 1 [running]:
Jul 23 06:33:29 vultr pigeon[76426]: main.main()
Jul 23 06:33:29 vultr pigeon[76426]:         /app/cmd/pigeon/main.go:22 +0x85
Jul 23 06:33:29 vultr systemd[1]: pigeond.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 23 06:33:29 vultr systemd[1]: pigeond.service: Failed with result 'exit-code'.
Jul 23 06:33:29 vultr systemd[1]: pigeond.service: Consumed 6min 29.346s CPU time.
Jul 23 06:33:34 vultr systemd[1]: pigeond.service: Scheduled restart job, restart counter is at 64.
Jul 23 06:33:34 vultr systemd[1]: Stopped Pigeon daemon.
Jul 23 06:33:34 vultr systemd[1]: pigeond.service: Consumed 6min 29.346s CPU time.
Jul 23 06:33:34 vultr systemd[1]: Started Pigeon daemon.
Jul 23 06:33:34 vultr pigeon[81912]: *chirp chirp*
Jul 23 06:33:34 vultr pigeon[81912]: time="2022-07-23T06:33:34Z" level=info msg="starting relayer" func="github.com/palomachain/pigeon/relayer.(*Relayer).Start" file="/app/relayer/start.go:21"
Jul 23 06:33:45 vultr pigeon[81912]: time="2022-07-23T06:33:45Z" level=info msg="relayer loop" func="github.com/palomachain/pigeon/relayer.(*Relayer).Start" file="/app/relayer/start.go:49"
Jul 23 06:33:45 vultr pigeon[81912]: Error: post failed: Post "http://localhost:26657": read tcp [::1]:43544->[::1]:26657: read: connection reset by peer
Jul 23 06:33:45 vultr pigeon[81912]: panic: post failed: Post "http://localhost:26657": read tcp [::1]:43544->[::1]:26657: read: connection reset by peer
Jul 23 06:33:45 vultr pigeon[81912]: goroutine 1 [running]:
Jul 23 06:33:45 vultr pigeon[81912]: main.main()
Jul 23 06:33:45 vultr pigeon[81912]:         /app/cmd/pigeon/main.go:22 +0x85
Jul 23 06:33:45 vultr systemd[1]: pigeond.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 23 06:33:45 vultr systemd[1]: pigeond.service: Failed with result 'exit-code'.
Jul 23 06:33:45 vultr systemd[1]: pigeond.service: Consumed 1.438s CPU time.
Jul 23 06:33:50 vultr systemd[1]: pigeond.service: Scheduled restart job, restart counter is at 65.
Jul 23 06:33:50 vultr systemd[1]: Stopped Pigeon daemon.
Jul 23 06:33:50 vultr systemd[1]: pigeond.service: Consumed 1.438s CPU time.
Jul 23 06:33:50 vultr systemd[1]: Started Pigeon daemon.
Jul 23 06:33:51 vultr pigeon[81921]: *chirp chirp*P

```

**Comment by Vizualni** [comment]
> # Pigeon service crashes sometimes with this error and than starts itself:
> Jul 22 21:12:19 vmd94125.contaboserver.net pigeon[19154]: wrapped error: unrecoverable error Jul 22 21:12:19 vmd94125.contaboserver.net pigeon[19154]: goroutine 1 [running]: Jul 22 21:12:19 vmd94125.contaboserver.net pigeon[19154]: main.main() Jul 22 21:12:19 vmd94125.contaboserver.net pigeon[19154]: /app/cmd/pigeon/main.go:22 +0x85 Jul 22 21:12:19 vmd94125.contaboserver.net systemd[1]: pigeond.service: Main process exited, code=exited, status=2/INVALIDARGUMENT Jul 22 21:12:19 vmd94125.contaboserver.net systemd[1]: pigeond.service: Failed with result 'exit-code'. Jul 22 21:12:25 vmd94125.contaboserver.net systemd[1]: pigeond.service: Scheduled restart job, restart counter is at 21. Jul 22 21:12:25 vmd94125.contaboserver.net systemd[1]: Stopped Pigeon daemon. Jul 22 21:12:25 vmd94125.contaboserver.net systemd[1]: Started Pigeon daemon. Jul 22 21:12:25 vmd94125.contaboserver.net pigeon[19653]: _chirp chirp_

Could you please start your pigeon with "LOG_LEVEL=debug" and print a bit more lines before the "unrecoverable" error comes to screen?

**Comment by Vizualni** [comment]
cc @mesahin001

**Comment by mesahin001** [comment]
[pigeon_log.txt](https://github.com/palomachain/paloma/files/9181484/pigeon_log.txt)

**Comment by verabehr** [comment]
we have moved on from this error - closing
