### ISSUE TITLE
error while getting consensus queue: consensus queue not implemented for queueTypeName EVM:eth-main:evm-turnstone-message module=x/consensus

### ISSUE THREAD

**Issue by nvlong95** [palomachain/paloma#340]
screenshot [https://i.imgur.com/Rvzgd2h.png](url)
what is that error?i don't know, my validator is active

**Comment by taariq** [comment]
> screenshot [https://i.imgur.com/Rvzgd2h.png](url) what is that error?i don't know, my validator is active

What version of Paloma and Pigeon are you using?

**Comment by taariq** [comment]
User is on older version of Pigeon and needs to upgrade.

**Comment by taariq** [comment]
User is on older version of Pigeon and needs to upgrade.
