### ISSUE TITLE
Bug: insufficient funds for transfer in pigeon with sufficient ETH in Wallet

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#342]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

**Error:**  insufficient funds for transfer in pigeon with sufficient ETH in Wallet at https://etherscan.io/address/0xaa68A2D797105dca15C1C65035c4E953a8C73927. Might be related to issue https://github.com/palomachain/paloma/issues/339

palomad version: v0.3.0-alpha
pigeon version: App version: v0.3.1 - Build commit hash: 624fe0ba69c23ee379963087e7f985c635a76ea7
chainInfos:
- address: [0xaa68A2D797105dca15C1C65035c4E953a8C73927](https://etherscan.io/address/0xaa68A2D797105dca15C1C65035c4E953a8C73927)
  chainReferenceID: eth-main
  chainType: EVM
  pubkey: qmii15cQXcoVwcZQNcTpU6jHOSc=
- address: 0x7e24006Be85DbEf1d8BFBa862Cc9aF9F269D35aF
  chainReferenceID: eth-main
  chainType: EVM
  pubkey: fiQAa+hdvvHYv7qGLMmvnyadNa8=

Error logs:
```
Jul 23 06:33:29 pigeon[76426]: error 97: insufficient funds for transfer
Jul 23 06:33:29 pigeon[76426]: error 98: insufficient funds for transfer
Jul 23 06:33:29 pigeon[76426]: error 99: insufficient funds for transfer
Jul 23 06:33:29 pigeon[76426]: error 100: insufficient funds for transfer
```

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Run Paloma and Pigeon. No messages sent into the network.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Funds in ETH wallet should be sufficient for valset transaction

**Comment by Vizualni** [comment]
I've checked your balance and it is zero. Your pigeon is still using `0x7e24006Be85DbEf1d8BFBa862Cc9aF9F269D35aF` address

**Comment by taariq** [comment]
Thanks. I guess I funded the WRONG address!
