### ISSUE TITLE
EGGdex - NFT Eggs gallery

### ISSUE THREAD

**Issue by joycehermosilla** [palomachain/paloma#349]
As a user of Paloma, I want to land on the website and access a gallery of the NFT Eggs

The user will direct from the Menu to "Paloma Eggs"

The landing page is under construction. Should be ready by the end of this week.

While is there no Landing Page the first view with being this one:https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=862%3A15

Each egg has a number and while hovering on top of the image the user will be able to see the address of the owner + a button that redirects to Open Sea or Magic Eden

*** By now no eggs have been release so we need to show all eggs as hiding ***
We want to show all eggs hiding, and show a count down to the next release.
The eggs that are next to the count down should be an Egg gif that you will find here: https://drive.google.com/drive/u/1/folders/11DXGougR0kf7lln9k9IjoZJjQhHGOHOd

Images here: https://drive.google.com/drive/u/1/folders/11DXGougR0kf7lln9k9IjoZJjQhHGOHOd

**Comment by verabehr** [comment]
This is outdated
