### ISSUE TITLE
Implement simple zero collision for job distribution across pigeons

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#354]
# Background

All pigeons are querying the same queue and are getting the same results back. All of them are trying to submit them at once. Implement way for them to know which job belongs to whom.

# Done when

- [x] pigeons know which jobs belong to them

**Comment by taariq** [comment]
@Vizualni Let's weight job assignment by stake?

**Comment by taariq** [comment]
@Vizualni Let's weight job assignment by stake?

**Comment by Vizualni** [comment]
> @Vizualni Let's weight job assignment by stake?

I'd rather not. Then the network will become slow because it would wait on a single/few pigeons to deliver those messages. I am trying to distribute the jobs equally on the whole network rather than creating a bottlenecks.
