### ISSUE TITLE
As creators of the chain, we want to have the right slashing parameters in place so that malicious behavior on the validator side is prevented, while risk for them is low enough to they remain engaged and are motivated to stake.

### ISSUE THREAD

**Issue by nikolasschoppmeier** [palomachain/paloma#36]
As Volume, we want to have the right slashing parameters in place so that malicious behavior on the validator side is prevented, while risk for them is low enough to they remain engaged and are motivated to stake.

### Slashing amounts / parameters / punishments

- 5% for signing a fake validator set or message, double sign, etc.
    - Will only be slashed once, then the validator should be jailed
- 5% for failure to sign a message or validator set
    - Will only be slashed once, then the validator should be jailed
        - 
- 1% for a downtime of 10k blocks (~13h)
    - → Jailing is very important in this case (as it preserves network uptime)
- Jailing

**Comment by taariq** [comment]
Closing as shipped.
