### ISSUE TITLE
Deploy volume DNS from the devops repo

### ISSUE THREAD

**Issue by measure-fi** [palomachain/paloma#360]
[Basic DevOps EPIC](https://www.notion.so/volumefi/EPIC-08-05-Basic-devops-940a4f2f0f04477faccb256f3a3a2a69)

## Background

We need at least a list of all of our servers, as well as a versioned location explaining our DNS. This should go in a private devops repo.

## Done When

- [ ] machines not on DNS accounted for in a big list of ansible machines
- [ ] DNS configuration exported to repo
- [ ] we can run a script to ensure DNS settings

**Comment by taariq** [comment]
Closing as not needed right now.
