### ISSUE TITLE
Add systemctl configurations to the devops repo

### ISSUE THREAD

**Issue by measure-fi** [palomachain/paloma#362]
[Basic DevOps EPIC](https://www.notion.so/volumefi/EPIC-08-05-Basic-devops-940a4f2f0f04477faccb256f3a3a2a69)

## Background

We'd like to be keeping track of what services are running where. This can evolve, but at present every machine should have:

```diff
diff old_logrotate.conf /etc/logrotate.conf
5,6c5,6
< # rotate log files weekly
< weekly
---
> # rotate log files daily
> daily
12,13c12,13
< # keep 4 weeks worth of backlogs
< rotate 4
---
> # keep 2 weeks worth of backlogs
> rotate 14
```

It's possible we want
```
/etc/systemd/journald.conf
...
Storage=persistent
```

and then we want know what systemd files we added.

**Comment by taariq** [comment]
Closing as no need right now.
