### ISSUE TITLE
Upgrade Paloma to use Cosmos-sdk 0.46.1

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#363]
[Solana Solo Machine EPIC](https://www.notion.so/volumefi/EPIC-07-22-Paloma-and-Solana-Solo-Machine-Bridge-17d01e06446644a7b3ba6ea9b62058e7)

# Background

As the title says.

# Done when

- [ ] a list of items, when checked, this ticket should be considered to be finished

**Comment by verabehr** [comment]
duplicate issue
