### ISSUE TITLE
As a User, I want to be able to execute a smart contract from one cosmos chain to another.

### ISSUE THREAD

**Issue by nikolasschoppmeier** [palomachain/paloma#37]
### Acceptance Criteria
    1. Functional UX
    2. Mainnet
    3. Basic functionality in place:
        1. Ability to define host chain
        2. Ability to define target chain
        3. Ability to submit payload
        4. Ability to execute

- [x] https://github.com/VolumeFi/cronchain/issues/30
- [x] https://github.com/VolumeFi/cronchain/issues/31
- [x] https://github.com/VolumeFi/cronchain/issues/34
- [x] https://github.com/VolumeFi/cronchain/issues/32
- [x] https://github.com/VolumeFi/cronchain/issues/38
- [x] https://github.com/VolumeFi/cronchain/issues/35

**Comment by taariq** [comment]
Closing as shipped.
