### ISSUE TITLE
Pigeon should verify the external chain info on every loop

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#378]
# Background

If a validator restarts palomad with a new version while pigeon is sleeping in the main loop, the pigeon will not notice that the chain went offline for a second while it could already have a new state. This is important, because currently pigeon sends the new chain info only when pigeon starts. This only impacts the testnet where we are not so gentle with deployments.
# Done when

- [ ] a list of items, when checked, this ticket should be considered to be finished

**Comment by verabehr** [comment]
this was done
