### ISSUE TITLE
Move data transformation from Pigeon to Paloma when sending data to EVM

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#379]
# Background

Currently, Pigeon is the one that takes the data and from the Pigeon and transforms it to bytecode. We want Pigeon to be quite dumb as it should only send messages to target chain. Messages coming to Pigeon which are ready for sending, should come in a bytecode format. That way we hold our logic on a single place only, which happens to be Paloma.

# Done when

- [ ] Pigeon  is not transforming the incoming data, it's only forwarding it to target chain
- [ ] Paloma is doing the transformation

**Comment by verabehr** [comment]
closing until we get back to this
