### ISSUE TITLE
Paloma verify the attestation TX data

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#380]
# Related issues

- https://github.com/palomachain/paloma/issues/379

# Background

When attesting to events coming from Pigeon for EVM type of events, we receive serialized TX bytes in case of success. That same TX object contains the payload that was sent as a bytecode. We want to verify the actual data against the message we sent. To do that, it becomes easier if we solve https://github.com/palomachain/paloma/issues/379 first as Paloma would be the bearer of the actual bytecode.

# Done when

- [ ] Paloma can verify the TX data against the message

**Comment by taariq** [comment]
Moved to https://github.com/VolumeFi/paloma/issues/43
