### ISSUE TITLE
Pigeon bug

### ISSUE THREAD

**Issue by andrii1890** [palomachain/paloma#404]
# What is happening?
<details>
  <summary>Pigeon bug after update</summary>
<i></i>
</details>
pigeon version:

App version: v0.5.0
Build commit hash: f4065bdbe2a2a99538ed8ca7556eefcebd85afcc

paloma version:
version: v0.6.1
commit: 9f8f4d9d8a7f8e4da0903bd6bdfcd943ebace004
build_tags: ""
go: go version go1.18.3 linux/amd64

after update got this

time="2022-08-15T15:27:03Z" level=error msg="error while trying to keep pigeon alive" error="timed out after: 600000000000; timed out after waiting for tx to get included in the block"
time="2022-08-15T15:27:09Z" level=error msg="error while trying to keep pigeon alive" error="rpc error: code = InvalidArgument desc = account sequence mismatch, expected 909, got 908: incorrect account sequence: invalid request"
time="2022-08-15T15:27:15Z" level=error msg="error while trying to keep pigeon alive" error="rpc error: code = InvalidArgument desc = account sequence mismatch, expected 909, got 908: incorrect account sequence: invalid request"
time="2022-08-15T15:27:21Z" level=error msg="error while trying to keep pigeon alive" error="rpc error: code = InvalidArgument desc = account sequence mismatch, expected 909, got 908: incorrect account sequence: invalid request"
time="2022-08-15T15:27:39Z" level=error msg="error while trying to keep pigeon alive" error="rpc error: code = InvalidArgument desc = account sequence mismatch, expected 909, got 908: incorrect account sequence: invalid request"
time="2022-08-15T15:28:03Z" level=info msg="relayer loop"

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Just update pigeon from 0.4.0 to 0.5.0

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

{WRITE YOUR ANSWER HERE}

**Comment by taariq** [comment]
Fixed with #409 #411 #412 #413
