### ISSUE TITLE
Add /health endpoint(s) and related service

### ISSUE THREAD

**Issue by measure-fi** [palomachain/paloma#408]
# Background

Our web services can go down with no visibility. This issue was created directly in response to palomachain.com being down.

# Done when

- [ ] `palomachain.com` has a `palomachain.com/health` endpoint
- [ ] We have a service which periodically pings `palomachain.com/health`
  - It looks like we can use https://github.com/prometheus/blackbox_exporter#readme for this.
- [ ] Add other targets? (these should be broken into separate issues)
  - faucet. The health check could even send the faucet account some grain
- [ ] And reports success/failure to prometheus
- [ ] We have an alert (or at least a dashboard) that fires when stuff is down

**Comment by Vizualni** [comment]
Have you considered using https://uptimerobot.com/pricing/ or any other service that does this (free tier does what we want)? Do we have any alerts on the Prometheus node? What if Prometheus node goes down?

**Comment by measure-fi** [comment]
@Vizualni I have, I think it more relates to our mid to long-term devops plans. In this case I think it's a more important near-term goal to thread all these pieces together, it builds team competency in the tools, and there are a number of other things we might want to monitor/alert on. Definitely the uptime of the monitoring system will quickly become a priority if we start actually using it.

(also this issue has been prioritized, if not formally, as "low")

Happy to have a discussion about what our mid-term devops plans look like.
