### ISSUE TITLE
Pigeon query for external chain info to figure out if it needs to send external chain info

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#415]
# Background

Pigeons are sending external chain info updates every minute. We should add a logic on pigeon to send this only when there is a discrepancy between what pigeon knows and what paloma knows.

# Done when

- [ ] pigeon knows if it should send external chain info to paloma

**Comment by taariq** [comment]
Good way to lower the network comms traffic.

**Comment by taariq** [comment]
Closing and moved to https://github.com/VolumeFi/paloma/issues/20
