### ISSUE TITLE
As a Pigeon user, i want to be able to import keys from bep39 mnemonic from Palomad Keys

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#416]
# Background
As a Pigeon user, i want to be able to import keys from bep39 mnemonic like we do in paloma keys add --recover so that I am able to import my palomad bep39 mnemonic got generate my ethereum private key so that I can use the same bep39 mnemonic for any EVM and Cosmos chain. Referenced from https://t.me/palomachain/21528

# Done when
**Acceptance Criteria**
- [ ]  Allow paloma keys add --recover to be use bep39 mnemonic to import paloma cosmos keys into EVM chains and generate EVM public keys using the palomad private key.

**Comment by verabehr** [comment]
@taariq ok to close for now?

**Comment by taariq** [comment]
yessss. okay to close.
