### ISSUE TITLE
pigeon evm keys list no longer works

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#417]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

pigeon evm keys list no longer works. Returns error.
```pigeon evm keys list
Error: accepts 1 arg(s), received 0```

Also ```pigeon evm keys list ~/.pigeon/keys/``` returns empty.

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>


pigeon evm keys list
Error: accepts 1 arg(s), received 0


# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Should return list of EVM keys.

**Comment by Vizualni** [comment]
@taariq please send your pigeon config file

**Comment by Vizualni** [comment]
@taariq I've sshed to your machine and took a look into the config. You should have used `pigeon evm keys list ~/.pigeon/keys/evm/eth-main`

**Comment by taariq** [comment]
Thanks!
