### ISSUE TITLE
BUG: Validator is re-jailed after unjail and restarting pigeon. Multiple reports.

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#420]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Pigeon fails with error that validator is jailed after unjail of validator and restart of paloma and pigeon:

Pigeon log files: https://gist.github.com/ERNcrypto/a840e8677496f7c4cf598f7677c102ea
pigeon configuration: https://gist.github.com/ERNcrypto/e8bdfb41873e027bc54982de120e8a54
Validator: palomavaloper1am3k7czusdcewv55nhaugu2drn38af9464n65p 
Versions: pigeon v0.6.1 and palomad v0.7.0 

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

1. Unjail tx on palomad
2. Restart pigeon
3. Vadliator jailed after five minutes.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

1. Unjail tx on palomad
2. Restart pigeon
3. Validator pigeon recognized as active by paloma and network. Pigeon joins to reach consensus.

**Comment by VitaValeriya** [comment]
I have the same problem:

**Comment by VitaValeriya** [comment]
I have the same problem (Unjail, Restart pigeon, jailed again after five minutes).
Pigeon log files: https://gist.github.com/VitaValeriya/5cd24b9744dd3bf86ba2c60fb53d0a07
Pigeon configuration: https://gist.github.com/VitaValeriya/9a3d48077b6c2342e481749094658539
Validator: palomavaloper1espezfvhuagml6g0flw8jj6ajs2wud4ctwe5m0
Versions: pigeon v0.6.1 and palomad v0.7.0

**Comment by D-Elektra** [comment]
Log of pigeon 
<img width="1369" alt="Снимок экрана 2022-08-21 в 7 54 40 AM" src="https://user-images.githubusercontent.com/87807935/185845340-9d6449c4-883b-4989-a868-88982042491a.png">

**Comment by Vizualni** [comment]
Hey @D-Elektra and @VitaValeriya . Thanks for your reports. Could you please start pigeon with `PIGEON_LOG_LEVEL=debug` environment variable and paste the logs here?

**Comment by D-Elektra** [comment]
> Hey @D-Elektra and @VitaValeriya . Thanks for your reports. Could you please start pigeon with `PIGEON_LOG_LEVEL=debug` environment variable and paste the logs here?

pigeon start PIGEON_LOG_LEVEL=debug environment
*chirp chirp*
Enter keyring passphrase:
INFO[0002] starting relayer                             
INFO[0004] updating external chain infos                
INFO[0004] sending account info to paloma                acc-address=0x0Ba5F0e6BDbc820EC58BC44f9c96A8A515Fb8Cfc chain-reference-id=eth-main chain-type=EVM
ERRO[0010] couldn't update external chain info           err="rpc error: code = InvalidArgument desc = account sequence mismatch, expected 1493, got 1492: incorrect account sequence: invalid request"
Error: rpc error: code = InvalidArgument desc = account sequence mismatch, expected 1493, got 1492: incorrect account sequence: invalid request

**Comment by Vizualni** [comment]
Hey @D-Elektra . You'd need to run it like this:
`PIGEON_LOG_LEVEL=debug pigeon start`

**Comment by D-Elektra** [comment]
@Vizualni nothing different
PIGEON_LOG_LEVEL=debug pigeon start
*chirp chirp*
Enter keyring passphrase:
INFO[0007] starting relayer
INFO[0009] updating external chain infos
INFO[0009] sending account info to paloma                acc-address=0x0Ba5F0e6BDbc820EC58BC44f9c96A8A515Fb8Cfc chain-reference-id=eth-main chain-type=EVM
ERRO[0609] couldn't update external chain info           err="timed out after: 600000000000; timed out after waiting for tx to get included in the block"
Error: timed out after: 600000000000; timed out after waiting for tx to get included in the block

**Comment by VitaValeriya** [comment]
> Hey @D-Elektra . You'd need to run it like this: `PIGEON_LOG_LEVEL=debug pigeon start` and not like this `pigeon start PIGEON_LOG_LEVEL=debug environment `

root@v609073:~# PIGEON_LOG_LEVEL=debug pigeon start
*chirp chirp*
panic: unable to locate keyring ENV variable

goroutine 1 [running]:
github.com/palomachain/pigeon/config.KeyringPassword(...)
        /app/config/config.go:70
github.com/palomachain/pigeon/app.PalomaClient()
        /app/app/app.go:124 +0x2fb
github.com/palomachain/pigeon/app.Relayer()
        /app/app/app.go:56 +0x45
main.glob..func14(0x2381ac0, {0x14a2bc5?, 0x0?, 0x0?})
        /app/cmd/pigeon/cmd_start.go:22 +0x8c
github.com/spf13/cobra.(*Command).execute(0x2381ac0, {0x2445330, 0x0, 0x0})
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x2381840)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /app/cmd/pigeon/main.go:32 +0xbb

**Comment by taariq** [comment]
@VitaValeriya That's a keyring ENV variable problem. You'll need to make sure your ENV variables are set. Please check your variables.

**Comment by taariq** [comment]
@D-Elektra @VitaValeriya Please add gist of your pigeon logs after this change. Please set gas adjustment to 2.0 in your .pigeon/config.yaml and unjail and restart your pigeons   gas-adjustment: 2.0

**Comment by taariq** [comment]
@Vizualni after restart with `pigeons gas-adjustment: 2.0` https://gist.github.com/ERNcrypto/1e0f4c4fc9791ab9cb9aea9278b126c0

**Comment by vbloher** [comment]
I have the same behavior here.

Validator: palomavaloper1kludne80z0tcq9t7j9fqa630fechsjhxc324tt

Binary versions: 
- pigeon v0.6.1
- palomad v0.7.0

Gas config:
- gas-adjustment: 2
- gas-prices: 0.01ugrain

Pigeon configuration: https://gist.github.com/vbloher/e93c263771139dab2f2bb2be05cead7c#file-pigeon_config-yaml
Pigeon logs: https://gist.github.com/vbloher/e93c263771139dab2f2bb2be05cead7c#file-pigeon_logs-log

In explorer I see that tx "Add External Chain Info For Validator" was successfully included in block - https://paloma.explorers.guru/transaction/C039519AA132B53AC17E77ECAD2EE1418EA413EDA194B3872C786064BADC94C9

**Comment by taariq** [comment]
@D-Elektra @VitaValeriya @vbloher will you please report your `[tx index]` value in your  .paloma/config/config.toml?

**Comment by vbloher** [comment]
> @D-Elektra @VitaValeriya @vbloher will you please report your `[tx index]` value in your .paloma/config/config.toml?

Exactly! I have tx_indexer="null".. 
Set the parameter value to default - kv. Looks like everything goes well now

**Comment by taariq** [comment]
Closing as resolved. Paloma PIgeons misconfigured their settings in config.toml.
