### ISSUE TITLE
bug: misleading docs on the palomadocs page

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#422]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

On the docs page https://palomachain.github.io/paloma-docs/guide/maintain/node/join-a-network.html#set-up-a-local-private-network it says that we need to add our own validator to gentx, which is not the case when joining the mainnet.

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

See https://palomachain.github.io/paloma-docs/guide/maintain/node/join-a-network.html#set-up-a-local-private-network

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

We can drop this paragraph

**Comment by verabehr** [comment]
I'm not sure I understand. In the description it says `....which is not the case when joining the mainnet.`. The instructions in the section referenced are for creating a private new testnet though

**Comment by Vizualni** [comment]
> I'm not sure I understand. In the description it says `....which is not the case when joining the mainnet.`. The instructions in the section referenced are for creating a private new testnet though


I see. The page is very confusing. It mentions testnet under the mainnet section. Maybe we should move this to a testnet section instead?

**Comment by verabehr** [comment]
yes, I'll review and update
