### ISSUE TITLE
bug?: validator is getting jailed because pigeon balance is too low when it shouldn't

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#428]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

My validator is getting jailed because my ETH balance is too low. However, my ETH balance according to Etherscan is above the threshold. 

validator: palomavaloper18d4cfq63h4a9cz49d86pr84hpang7yvq04tyc6

my wallet: https://etherscan.io/address/0xE12f475763598Aa093EA0A8F0F9cB7CAA11502bC

grep of logs searching for my valoper and my valcons addresses. (I unjailed myself a few times)
<img width="1126" alt="Screen Shot 2022-08-22 at 8 10 50 PM" src="https://user-images.githubusercontent.com/19958639/186041280-8915da6a-1dc4-4789-85ab-8b2cf5723a5f.png">
<img width="1430" alt="Screen Shot 2022-08-22 at 8 11 14 PM" src="https://user-images.githubusercontent.com/19958639/186041282-440de19d-7a18-4977-88b6-2209293f8b50.png">

video of my last unjail attempt. Note it takes about 30 minutes for me to get jailed after starting up. 
https://drive.google.com/file/d/1HAlsACHP5KZimckikEB0SwDjALuewAsB/view?usp=sharing

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Unclear. It may be user error

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

{WRITE YOUR ANSWER HERE}

**Comment by Vizualni** [comment]
Please paste your pigeon config file and related env variables which do not contain any passwords. This looks like the eth address is not linked properly with your validator

**Comment by Vizualni** [comment]
@verabehr your systemd config for pigeon still points to your old address so the pigeon didn't even know that your eth address [0xE12f475763598Aa093EA0A8F0F9cB7CAA11502bC](https://etherscan.io/address/0xE12f475763598Aa093EA0A8F0F9cB7CAA11502bC) exists. Closing this for now.

<img width="530" alt="Screenshot 2022-08-23 at 08 57 52" src="https://user-images.githubusercontent.com/454988/186091627-c98486ef-750c-4f9c-a8df-81f6d220d86f.png">

**Comment by verabehr** [comment]
aah  of course, thank you.
