### ISSUE TITLE
Pigeons experiencing Account Sequence Mismatch Errors on Cosmos

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#429]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Pigeon is unable to execute tx in Cosmos block because pigeon restart and message send is faster than Cosmos ability to process the prior tx into the block. We will need to optimize txes from pigeons so that pigeons are not sending messages. See the log here: https://gist.github.com/ERNcrypto/e7fc4b75757cdec2cb0309c2a0dc2c51

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Pigeon restart and send tx to Paloma before block is confirmed will result in Account sequence mismatch errors.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Pigeon restart should check for pending messages from pigeon that are not yet included in a block and then send the message. Also, we may want to optimize for faster block times for Paloma.

**Comment by ERNcrypto** [comment]
First we found problems with Alchemy https://gist.github.com/ERNcrypto/4ff8a1df4b49ef907fc3304fa27deb0e

Then we changed Alchemy and found a new problem with Cosmos (Stopping pigeon and Paloma. Restart Paloma. Unjail. Then START pigeon did not help)
https://gist.github.com/ERNcrypto/4c26d3328fbc728f5e2ccfc3c3c881c7

**Comment by verabehr** [comment]
From Matija: Honestly, this is the cosmos's core behaviour and there isn't anything that I can do. It usually works for me once my client (either palomad or pigeon) is able to send one tx over, then things kind of sync.

**Comment by taariq** [comment]
Closing as won't fix.
