### ISSUE TITLE
Pigeon is being jailed with 0.1 ETH minimum balance, but is jailed due to having exact amount

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#430]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

```root@localhost:~# journalctl -u palomad.service -n 1000 | grep 'palomavaloper1am3k7czusdcewv55nhaugu2drn38af9464n65p'```

Returns the following error:
```
Aug 23 15:53:17 localhost palomad[4066606]: 3:53PM INF jailing a validator module=x/valset reason="not enough funds in the target chain (eth-main). Has 100000000000000000. Min required: 100000000000000000." val-addr=palomavaloper1am3k7czusdcewv55nhaugu2drn38af9464n65p
```

Balance on Eth:
https://etherscan.io/address/0xee83770168d4ee756e74562c17bded88091519d0 shows 0.1 ETH.

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Pigeons with exactly 0.1 ETH are jailed.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Balance check for pigeon ETH balance jail should be less than 0.1 ETH not 0.1 ETH exactly.

**Comment by Vizualni** [comment]
Fixed. Closing
