### ISSUE TITLE
As a pigeon, I want the minimum balance check to be 0.05ETH and subject to governance

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#432]
# Background
Pigeons are using up their valset updates of 0.1 ETH and being jailed. As such, we want to lower the threshold for jailing while still refunding pigeons. We would like to lower the default threshold for pigeon to be active from 0.1 ETH to LESS THAN 0.05 ETH.

# Done when
- [ ] Update minimum ETH required to be in the validator set  0.05 ETH or MORE.

**Comment by taariq** [comment]
@Vizualni is this okay to ship in th enext release?

**Comment by Vizualni** [comment]
> @Vizualni is this okay to ship in th enext release?

Yep! We will ship it.

**Comment by Vizualni** [comment]
This is done. Closing
