### ISSUE TITLE
Pigeon Error starting healtcheck server" error="listen tcp 127.0.0.1:5757: bind: address already in use"

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#445]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Pigeon service restart job networking error: 

Aug 26 18:06:57 vmi655239.contaboserver.net systemd[1]: pigeond.service: Scheduled restart job, restart counter is at 1130.
Aug 26 18:06:57 vmi655239.contaboserver.net systemd[1]: Stopped Pigeon daemon.
Aug 26 18:06:58 vmi655239.contaboserver.net systemd[1]: Started Pigeon daemon.
Aug 26 18:06:58 vmi655239.contaboserver.net pigeon[2659663]: *chirp chirp*
Aug 26 18:06:58 vmi655239.contaboserver.net pigeon[2659663]: time="2022-08-26T18:06:58+02:00" level=info msg="app info" PID=2659663 commit=7af3c7f8ff8c5523a53f496c988ade5c5e9e105f version=v0.7.0
Aug 26 18:06:58 vmi655239.contaboserver.net pigeon[2659663]: time="2022-08-26T18:06:58+02:00" level=info msg="Starting healthcheck server"
Aug 26 18:06:58 vmi655239.contaboserver.net pigeon[2659663]: time="2022-08-26T18:06:58+02:00" level=error msg="error starting healtcheck server" error="listen tcp 127.0.0.1:5757: bind: address already in use"
Aug 26 18:06:58 vmi655239.contaboserver.net pigeon[2659663]: panic: listen tcp 127.0.0.1:5757: bind: address already in use
Aug 26 18:06:58 vmi655239.contaboserver.net pigeon[2659663]: goroutine 27 [running]:
Aug 26 18:06:58 vmi655239.contaboserver.net pigeon[2659663]: github.com/palomachain/pigeon/health.StartHTTPServer({0x183e688?, 0xc0001fbec0}, 0x0?, 0x0?, {0x18256d4, 0x6}, {0x18304c0, 0x28})
Aug 26 18:06:58 vmi655239.contaboserver.net pigeon[2659663]:         /app/health/server.go:49 +0x315
Aug 26 18:06:58 vmi655239.contaboserver.net pigeon[2659663]: main.glob..func15.1()
Aug 26 18:06:58 vmi655239.contaboserver.net pigeon[2659663]:         /app/cmd/pigeon/cmd_start.go:36 +0x69
Aug 26 18:06:58 vmi655239.contaboserver.net pigeon[2659663]: created by main.glob..func15
Aug 26 18:06:58 vmi655239.contaboserver.net pigeon[2659663]:         /app/cmd/pigeon/cmd_start.go:35 +0x32b
Aug 26 18:06:58 vmi655239.contaboserver.net systemd[1]: pigeond.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

re-start pigeon

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Pigeon restart should not

**Comment by D-Elektra** [comment]
GNU nano 4.8                                                             /etc/systemd/system/palomad.service                                                                       
[Unit]
Description=Paloma Blockchain
After=network.target
ConditionPathExists=/usr/local/bin/palomad

[Service]
Type=simple
LimitNOFILE=65535
Restart=always
RestartSec=5
WorkingDirectory=~
ExecStartPre=
ExecStart=/usr/local/bin/palomad start
Environment=PIGEON_HEALTHCHECK_PORT=5757
ExecReload=

[Install]
WantedBy=multi-user.target



  GNU nano 4.8                                                                  /root/.pigeon/config.yaml                                                                            
loop-timeout: 5s
health-check-port: 5757

paloma:
  chain-id: paloma-testnet-9
  call-timeout: 20s
  keyring-dir: ~/.paloma
  keyring-pass-env-name: PALOMA_KEYRING_PASS
  keyring-type: os
  signing-key: ${VALIDATOR}
  base-rpc-url: http://localhost:26657
  gas-adjustment: 2.0
  gas-prices: 0.001ugrain
  account-prefix: paloma

evm:
  eth-main:
    chain-id: 1
    base-rpc-url: ${ETH_RPC_URL}
    keyring-pass-env-name: ETH_PASSWORD
    signing-key: ${ETH_SIGNING_KEY}
    keyring-dir: ~/.pigeon/keys/evm/eth-main

**Comment by Vizualni** [comment]
This is a user error. Something is already listening on port 5757 on your machine. You can change it to something else in pigeon config, but then you must update the PIGEON_HEALTHCHECK_PORT environment variable to match it. Closing this.

**Comment by D-Elektra** [comment]
root@vmi655239:~# sudo ss -tulpn
Netid         State          Recv-Q         Send-Q                 Local Address:Port                   Peer Address:Port         Process                                            
udp           UNCONN         0              0                      127.0.0.53%lo:53                          0.0.0.0:*             users:(("systemd-resolve",pid=361,fd=12))         
tcp           LISTEN         0              4096                       127.0.0.1:6060                        0.0.0.0:*             users:(("palomad",pid=2592170,fd=33))             
tcp           LISTEN         0              4096                   127.0.0.53%lo:53                          0.0.0.0:*             users:(("systemd-resolve",pid=361,fd=13))         
tcp           LISTEN         0              128                          0.0.0.0:22                          0.0.0.0:*             users:(("sshd",pid=433,fd=3))                     
tcp           LISTEN         0              4096                       127.0.0.1:5757                        0.0.0.0:*             users:(("pigeon",pid=2585025,fd=8))               
tcp           LISTEN         0              4096                       127.0.0.1:26657                       0.0.0.0:*             users:(("palomad",pid=2592170,fd=34))             
tcp           LISTEN         0              128                             [::]:22                             [::]:*             users:(("sshd",pid=433,fd=4))                     
tcp           LISTEN         0              4096                               *:26656                             *:*             users:(("palomad",pid=2592170,fd=35))             
tcp           LISTEN         0              4096                               *:9090                              *:*             users:(("palomad",pid=2592170,fd=38))             
tcp           LISTEN         0              4096                               *:9091                              *:*             users:(("palomad",pid=2592170,fd=40))

**Comment by Vizualni** [comment]
> tcp LISTEN 0 4096 127.0.0.1:5757 0.0.0.0:* users:(("pigeon",pid=2585025,fd=8))

Exactly. You already have a pigeon that's listening on that port, thus the error you are seeing is coming from a different one that can't come alive because that port is already taken.
