### ISSUE TITLE
Cosmwasm/paloma compass contract

### ISSUE THREAD

**Issue by measure-fi** [palomachain/paloma#447]
[Solana Solo Bridge EPIC](https://www.notion.so/volumefi/EPIC-07-22-Paloma-and-Solana-Solo-Machine-Bridge-17d01e06446644a7b3ba6ea9b62058e7)

## Background

We need a version of compass that can run on paloma

https://github.com/palomachain/compass-evm/blob/master/contracts/Turnstone.vy

# Done when

- [ ] it's done

**Comment by Vizualni** [comment]
I am sorry. A compass that runs on paloma?

**Comment by Vizualni** [comment]
Why is there a turnstone label here?

**Comment by measure-fi** [comment]
> I am sorry. A compass that runs on paloma?

That is what was requested at some point. If it's something we ever want I'd rather do it now just to get all the compassing done at once.

> Why is there a turnstone label here?

I've been tagging everything solo bridge related with turnstone and in retrospect I probably could have made my own lable.
