### ISSUE TITLE
bug: exite code

### ISSUE THREAD

**Issue by erkancamli** [palomachain/paloma#449]
=["“d363f84a8f40e655812436be4f0c8b3fc3543805@173.255.229.106:26656"] module=p2p
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]: 11:09AM ERR Error in peer's address err="invalid address (“d363f84a8f40e655812436be4f0c8b3fc3543805@173.255.229.106:26656): encoding/hex: invalid byte: U+00E2 'â'" module=p2p
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]: Error: could not add peers from persistent_peers field: invalid address (“d363f84a8f40e655812436be4f0c8b3fc3543805@173.255.229.106:26656): encoding/hex: invalid byte: U+00E2 'â'
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]: Usage:
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:   palomad start [flags]
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]: Flags:
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --abci string                                     specify abci transport (socket | grpc) (default "socket")
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --address string                                  Listen address (default "tcp://0.0.0.0:26658")
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --consensus.create_empty_blocks                   set this to false to only produce blocks when there are txs or when the AppHash changes (default true)
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --consensus.create_empty_blocks_interval string   the possible interval between empty blocks (default "0s")
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --consensus.double_sign_check_height int          how many blocks to look back to check existence of the node's consensus votes before joining consensus
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --cpu-profile string                              Enable CPU profiling and write to the provided file
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --db_backend string                               database backend: goleveldb | cleveldb | boltdb | rocksdb | badgerdb (default "goleveldb")
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --db_dir string                                   database directory (default "data")Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --fast_sync                                       fast blockchain syncing (default true)
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --genesis_hash bytesHex                           optional SHA-256 hash of the genesis file
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --grpc-only                                       Start the node in gRPC query only mode (no Tendermint process is started)
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --grpc-web.address string                         The gRPC-Web server address to listen on (default "0.0.0.0:9091")
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --grpc-web.enable                                 Define if the gRPC-Web server should be enabled. (Note: gRPC must also be enabled.) (default true)
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --grpc.address string                             the gRPC server address to listen on (default "0.0.0.0:9090")
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --grpc.enable                                     Define if the gRPC server should be enabled (default true)
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --halt-height uint                                Block height at which to gracefully halt the chain and shutdown the node
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --halt-time uint                                  Minimum block time (in Unix seconds) at which to gracefully halt the chain and shutdown the node
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:   -h, --help                                            help for start
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --inter-block-cache                               Enable inter-block caching (default true)
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --inv-check-period uint                           Assert registered invariants every N blocks
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --min-retain-blocks uint                          Minimum block height offset during ABCI commit to prune Tendermint blocks
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --minimum-gas-prices string                       Minimum gas prices to accept for transactions; Any fee in a tx must meet this minimum (e.g. 0.01photino;0.0001stake)
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --moniker string                                  node name (default "vmi913085.contaboserver.net")
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --p2p.laddr string                                node listen address. (0.0.0.0:0 means any interface, any port) (default "tcp://0.0.0.0:26656")
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --p2p.persistent_peers string                     comma-delimited ID@host:port persistent peers
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --p2p.pex                                         enable/disable Peer-Exchange (default true)
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --p2p.private_peer_ids string                     comma-delimited private peer IDs
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --p2p.seed_mode                                   enable/disable seed mode
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --p2p.seeds string                                comma-delimited ID@host:port seed nodes
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --p2p.unconditional_peer_ids string               comma-delimited IDs of unconditional peers
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --p2p.upnp                                        enable/disable UPNP port forwardingAug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --priv_validator_laddr string                     socket address to listen on for connections from external priv_validator process
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --proxy_app string                                proxy app address, or one of: 'kvstore', 'persistent_kvstore', 'counter', 'e2e' or 'noop' for local testing. (default "tcp://127.0.0.1:26658")
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --pruning string                                  Pruning strategy (default|nothing|everything|custom) (default "default")
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --pruning-interval uint                           Height interval at which pruned heights are removed from disk (ignored if pruning is not 'custom')
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --pruning-keep-every uint                         Offset heights to keep on disk after 'keep-every' (ignored if pruning is not 'custom')Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --pruning-keep-recent uint                        Number of recent heights to keep on disk (ignored if pruning is not 'custom')
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --rpc.grpc_laddr string                           GRPC listen address (BroadcastTx only). Port required
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --rpc.laddr string                                RPC listen address. Port required (default "tcp://127.0.0.1:26657")
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --rpc.pprof_laddr string                          pprof listen address (https://golang.org/pkg/net/http/pprof)
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --rpc.unsafe                                      enabled unsafe rpc methods
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --state-sync.snapshot-interval uint               State sync snapshot interval
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --state-sync.snapshot-keep-recent uint32          State sync snapshot to keep (default 2)
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --trace-store string                              Enable KVStore tracing to an output file
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --transport string                                Transport protocol: socket, grpc (default "socket")
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --unsafe-skip-upgrades ints                       Skip a set of upgrade heights to continue the old binary
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --with-tendermint                                 Run abci app embedded in-process with tendermint (default true)
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --x-crisis-skip-assert-invariants                 Skip x/crisis invariants check on startup
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]: Global Flags:
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --home string         directory for config and data (default "/root/.paloma")
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --log_format string   The logging format (json|plain) (default "plain")
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
Aug 28 11:09:14 vmi913085.contaboserver.net systemd[1]: palomad.service: Main process exited, code=exited, status=1/FAILURE
Aug 28 11:09:14 vmi913085.contaboserver.net palomad[1725080]:       --trace               print out full stack trace on errors
Aug 28 11:09:14 vmi913085.contaboserver.net systemd[1]: palomad.service: Failed with result 'exit-code'.

**Comment by taariq** [comment]
Closing as linked to the old paloma-testnet-9
