### ISSUE TITLE
BUG: Unable to create validator. panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#450]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

When creating a validator on Paloma-testnet-10

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x14eb83f]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/staking/client/cli.newBuildCreateValidatorMsg({{0xc0012c9590, 0x14, 0x18}, {0x2634ca0, 0xc001361260}, {0x7fff5f70a51e, 0x11}, {0x0, 0x0}, {0x0, ...}, ...}, ...)
        /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/x/staking/client/cli/tx.go:294 +0x15f
github.com/cosmos/cosmos-sdk/x/staking/client/cli.NewCreateValidatorCmd.func1(0xc0012fa500?, {0xc001315080?, 0x15?, 0x16?})
        /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/x/staking/client/cli/tx.go:64 +0x298
github.com/spf13/cobra.(*Command).execute(0xc0012fa500, {0xc001314f20, 0x15, 0x16})
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00124af00)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x23c5990?, {0xc000f15668, 0x14})
        /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/server/cmd/execute.go:36 +0x1eb
main.main()
        /app/cmd/palomad/main.go:75 +0x1b0

bank sends work normally.

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Create validator on paloma-testnet-10

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Staking Validator should be created.

**Comment by vbloher** [comment]
Tried to re-import the key - same behavior

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x14eb83f]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/staking/client/cli.newBuildCreateValidatorMsg({{0xc00016da88, 0x14, 0x18}, {0x2634ca0, 0xc000f58ae0}, {0x7ffe1b00b636, 0x11}, {0x0, 0x0}, {0x0, ...}, ...}, ...)
        /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/x/staking/client/cli/tx.go:294 +0x15f
github.com/cosmos/cosmos-sdk/x/staking/client/cli.NewCreateValidatorCmd.func1(0xc000dbc780?, {0xc000f348f0?, 0xd?, 0xd?})
        /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/x/staking/client/cli/tx.go:64 +0x298
github.com/spf13/cobra.(*Command).execute(0xc000dbc780, {0xc000f34820, 0xd, 0xd})
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000582c80)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x23c5990?, {0xc000135aa0, 0x15})
        /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/server/cmd/execute.go:36 +0x1eb
main.main()
        /app/cmd/palomad/main.go:75 +0x1b0
```

**Comment by erkancamli** [comment]
root@vmi913085:~# journalctl -u palomad.service -f
-- Logs begin at Mon 2022-08-29 05:09:36 CEST. --
Aug 29 11:01:17 vmi913085.contaboserver.net palomad[2002680]:       --unsafe-skip-upgrades ints                       Skip a set of upgrade heights to continue the old binary
Aug 29 11:01:17 vmi913085.contaboserver.net palomad[2002680]:       --with-tendermint                                 Run abci app embedded in-process with tendermint (default true)
Aug 29 11:01:17 vmi913085.contaboserver.net palomad[2002680]:       --x-crisis-skip-assert-invariants                 Skip x/crisis invariants check on startup
Aug 29 11:01:17 vmi913085.contaboserver.net palomad[2002680]: Global Flags:
Aug 29 11:01:17 vmi913085.contaboserver.net palomad[2002680]:       --home string         directory for config and data (default "/root/.paloma")
Aug 29 11:01:17 vmi913085.contaboserver.net palomad[2002680]:       --log_format string   The logging format (json|plain) (default "plain")
Aug 29 11:01:17 vmi913085.contaboserver.net palomad[2002680]:       --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
Aug 29 11:01:17 vmi913085.contaboserver.net palomad[2002680]:       --trace               print out full stack trace on errors
Aug 29 11:01:17 vmi913085.contaboserver.net systemd[1]: palomad.service: Main process exited, code=exited, status=1/FAILURE
Aug 29 11:01:17 vmi913085.contaboserver.net systemd[1]: palomad.service: Failed with result 'exit-code'.

**Comment by taariq** [comment]
Fixed and verified in production.
