### ISSUE TITLE
BLOG - New Paloma Website

### ISSUE THREAD

**Issue by joycehermosilla** [palomachain/paloma#451]
As a user of Paloma, I want to see a new and improved version of the Blog section.

**BLOG main view**
https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=2013%3A561

- [x] Menu item selected. When the user is on the Blog view the Blog button will change to "selected" changing the color to HEX: FF62C4
<img width="707" alt="Captura de pantalla 2022-08-29 a las 11 53 28" src="https://user-images.githubusercontent.com/22323189/187175225-0ebbd585-6a5e-4040-925a-c993f70a363c.png">

- [x] Submenu. We will keep the same sections than the old Paloma blog. 
<img width="628" alt="Captura de pantalla 2022-08-29 a las 11 54 50" src="https://user-images.githubusercontent.com/22323189/187175474-45f879f3-c3a3-4be5-ab92-6e3af2aa8bfd.png">

- [x] As the user scroll on the page we want to keep the top nav bar fixed while scrolling.
<img width="1512" alt="Captura de pantalla 2022-08-29 a las 13 03 54" src="https://user-images.githubusercontent.com/22323189/187187524-f84dd23a-23dd-4c74-9ad7-aba054a2c21c.png">

Prototype: https://www.figma.com/proto/ClniQyKFqN1hSpWizV5O4A/Paloma?page-id=133%3A2&node-id=2013%3A561&viewport=-1592%2C-1411%2C0.3&scaling=min-zoom&starting-point-node-id=2013%3A561

- [x] Submenu while hovering, will change to "selected state" 
<img width="633" alt="Captura de pantalla 2022-08-29 a las 11 58 39" src="https://user-images.githubusercontent.com/22323189/187176188-6f351a3e-8511-4cf5-8e4a-50f0eb1e1cd4.png">

Prototype (hover the 1st section): https://www.figma.com/proto/ClniQyKFqN1hSpWizV5O4A/Paloma?page-id=133%3A2&node-id=2013%3A561&viewport=-992%2C-828%2C0.13&scaling=min-zoom&starting-point-node-id=2013%3A561 

Design: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=2013%3A756

- [x] The Latest: 
Follow designs: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=2013%3A561
<img width="424" alt="Captura de pantalla 2022-08-29 a las 12 18 42" src="https://user-images.githubusercontent.com/22323189/187179682-6e60d7e3-08a3-4653-81bc-9f45fba6043b.png">

- [x] While hovering the box of the blog post should change its color. https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=1903%3A1037

<img width="417" alt="Captura de pantalla 2022-08-29 a las 12 19 41" src="https://user-images.githubusercontent.com/22323189/187179849-d2b461e2-2a00-4b05-acd0-14a8b06a4f50.png">

- [x] The user needs to be able to redirect to the Blog post content by pressing on the image or whatever part of the description. 

- [x] Sections view (Project Updates, AMA, Blockchain Culture)
Please follow the designs: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=2070%3A152

- [x] Section blog post while hovering. While hovering the box of the blog post should change its color as in "The Latest"

- [x]  Section Scroll: When you scroll the content of the Blog we want to keep fixed the top nav bar.
<img width="1512" alt="Captura de pantalla 2022-08-29 a las 13 01 37" src="https://user-images.githubusercontent.com/22323189/187187050-28a0350a-4220-46b7-8d6a-22fc39cfa3bf.png">

Prototype: https://www.figma.com/proto/ClniQyKFqN1hSpWizV5O4A/Paloma?page-id=133%3A2&node-id=2017%3A1195&viewport=-3241%2C-2855%2C0.36&scaling=min-zoom&starting-point-node-id=2013%3A561

- [x] Blog detail view
Please follow designs:https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=2070%3A288
<img width="553" alt="Captura de pantalla 2022-08-29 a las 12 24 47" src="https://user-images.githubusercontent.com/22

323189/187180752-5f12064f-4970-4b72-9259-b6784a9e06fa.png">

- [x] Blog detail scroll.
When you scroll the content of the Blog we want to keep fixed the top nav bar.

<img width="1276" alt="Captura de pantalla 2022-08-29 a las 11 45 18" src="https://user-images.githubusercontent.com/22323189/187183573-85741b14-3328-45eb-9340-b616999dec06.png">

Prototype:https://www.figma.com/proto/ClniQyKFqN1hSpWizV5O4A/Paloma?page-id=133%3A2&node-id=2070%3A288&viewport=-3241%2C-2855%2C0.36&scaling=min-zoom&starting-point-node-id=2013%3A561

Extras:

- [x] User needs to be able to go back to the previous page with the navigation arrows in the explorer.

**Comment by verabehr** [comment]
@joycehermosilla did a first pass and checked of some functional items. Anything with colors, spacing etc I left for you to sign off on. 

@wdev733 

- [ ] Please check again the `Blog - Main View`  screen in the Figma design. There is no banner with title "blog". The submenu sections are directly under the main nav
- [ ] Please check again the content view. The image should be in between fields `intro` and `long text`

**Comment by verabehr** [comment]
@wdev733 (cc @joycehermosilla )on https://paloma-website-kr32735m5-volume.vercel.app/ noticing the following on :

- [ ] Sections view (Project Updates, AMA, Blockchain Culture) - there should be no "blog" back button at the top left
- [ ] the blog detail page font for the long text does not match the figma
- [ ] the Submenu while hovering, will change to "selected state" does not match the prototype https://www.figma.com/proto/ClniQyKFqN1hSpWizV5O4A/Paloma?page-id=133%3A2&node-id=2013%3A561&viewport=-992%2C-828%2C0.13&scaling=min-zoom&starting-point-node-id=2013%3A561

**Comment by joycehermosilla** [comment]
FEEDBACK 14/09:

- [ ] Add the Section "Announcements" to the Blog. Image: https://drive.google.com/drive/u/1/folders/1OEA4oi87F06yySw0BAq5LZ_hloK0BFEH
<img width="316" alt="Captura de pantalla 2022-09-14 a las 10 37 10" src="https://user-images.githubusercontent.com/22323189/190224361-64058448-a42a-4d58-9ed9-64e41be93f6f.png">

- [ ] Remove "Blockchain Culture" section.

- [ ] Change AMAs section to "Events"
<img width="380" alt="Captura de pantalla 2022-09-14 a las 10 38 02" src="https://user-images.githubusercontent.com/22323189/190224461-d8a573d5-4b26-4f58-9038-be35d9109aee.png">
