### ISSUE TITLE
BUG: Pigeons complain couldn't broadcast signatures and process attestation

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#454]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

time="2022-08-29T16:41:03+02:00" level=error msg="couldn't broadcast signatures and process attestation" error="context canceled" message-ids="[56]" queue-name=EVM/eth-main/evm-turnstone-message signed-messages="[map[id:56 signature:[93 0 200 138 30 220 61 252 32 195 234 101 137 195 22 0 240 2 88 3 178 46 23 147 10 43 129 245 193 119 186 188 57 26 3 117 99 210 248 194 11 76 185 237 98 23 96 75 175 101 127 240 188 1 133 209 152 82 158 168 73 209 89 212 1]]]"

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Normal running pigeon

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

signatures should broadcast without problems and valset updates should happen.

**Comment by Vizualni** [comment]
This is not a bug nor an error. The error is "context cancelled" which means that pigeon itself decided that it should stop processing its current context.

**Comment by taariq** [comment]
Thanks!
