### ISSUE TITLE
BUG: Pigeon listen port environment variable is not set when attempting to delegate

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#455]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

pigeon listen port environment variable is not set
but pigeon listen port environment variable is set:
Palomad service https://gist.github.com/VitaValeriya/f3c3e5ba1c6c25f0c894900bf7bd753d
Pigeon config https://gist.github.com/VitaValeriya/9a3d48077b6c2342e481749094658539
Pigeon log https://gist.github.com/VitaValeriya/5cd24b9744dd3bf86ba2c60fb53d0a07

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Delegate should not break on pigeon port setting.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Delegate and all staking module functions should run.

**Comment by Vizualni** [comment]
@taariq requirement number 2 here https://www.notion.so/volumefi/EPIC-08-19-Enforce-pigeons-running-c8020d7156ea4aa68eb32514fce84192 says otherwise. This is not a bug, but rather a new feature request.

**Comment by taariq** [comment]
@Vizualni to confirm: Your conclusion is that that the staking module check on pigeon running IS implemented and that delegation is failing because pigeon is NOT running or that we need to implement taking module client checks on pigeon in order to allow proper functioning? 

All errors are reported from running pigeons and validators who are trying to use the staking module to delegate. Did we ship the **The staking module of Paloma should not be accessible unless pigeon is running** feature?

**Comment by Vizualni** [comment]
Oh sorry @taariq. I misread the description. This is implemented and working per design to answer your question(s). After re-reading the problem statement and those config files I can conclude that this is the user error. User (VitaValeriya) has defined the environment variable correctly in the service file, but when running the command from bash they haven't set the environment variable.
One way to set environment variables in bash when running a process is like this:
`PIGEON_HEALTHCHECK_PORT=5757 palomad tx staking ...`
or:
```
$ export PIGEON_HEALTHCHECK_PORT=5757
$ palomad tx staking ...
```

**Comment by VitaValeriya** [comment]
> $ export PIGEON_HEALTHCHECK_PORT=5757
> $ palomad tx staking ...

Yes, it works.

**Comment by taariq** [comment]
Thanks @Vizualni
