### ISSUE TITLE
EVENTS - New Paloma Website

### ISSUE THREAD

**Issue by joycehermosilla** [palomachain/paloma#457]
As a user of Paloma, I want to keep updated on the next Paloma events.

Please follow the designs:
https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=2077%3A403

- [x] We want to group Upcoming Events and Past Events on one page. So we need to remove the submenu on the Events menu.

- [x] While scrolling we want to have the Top Nav Menu fixed, as in the Blog page.
<img width="1270" alt="Captura de pantalla 2022-08-31 a las 17 14 16" src="https://user-images.githubusercontent.com/22323189/187714501-845f1b78-d6f5-42fb-8a71-1f9450c85f6b.png">

- [x] While hovering I want to see the event box change the color to HEX: F6F2F2
<img width="658" alt="Captura de pantalla 2022-08-31 a las 17 15 26" src="https://user-images.githubusercontent.com/22323189/187714753-444b2110-0229-43c0-9f3e-e0683218714b.png">

**Comment by joycehermosilla** [comment]
01/09 Review:

- [ ] Change the background color of the events detail to HEX F0EBEB
<img width="348" alt="Captura de pantalla 2022-09-01 a las 19 14 08" src="https://user-images.githubusercontent.com/22323189/187973395-88a1fa1f-8cf0-416d-acb2-8c605e72b092.png">

- [ ] Date of the event should be in "Rock Star Regular" HEX: 2C2C2C 12px
- [ ] Add event title
- [ ] Event description in "Rock Star Regular" HEX: 2C2C2C 16 px
- [ ] Registration/Learn more button should be Pink: HEX:F1D1E5
- [ ] While hovering I want to see the event box change the color to HEX: F6F2F2


Past Events: 

- [ ] Change the background color of the events detail to HEX F0EBEB
<img width="348" alt="Captura de pantalla 2022-09-01 a las 19 14 08" src="https://user-images.githubusercontent.com/22323189/187973395-88a1fa1f-8cf0-416d-acb2-8c605e72b092.png">

- [ ] Remove past events description
- [ ] Add past event title

**Comment by verabehr** [comment]
- [ ] @joycehermosilla @wdev733 I noticed that the hand cursor shows for the whole event card not only when I hover over the button. I'm thinking we could actually make the whole area clickable (but still keep the button)? Otherwise, the hand icon should only show when hovering over the button.

**Comment by joycehermosilla** [comment]
> * still

Good catch @verabehr I think we can keep the whole area to be clickable but show only the hand while hovering the button.

**Comment by joycehermosilla** [comment]
- [ ] Each section of the events should be of 336px wide. And events images should be 336x200px.
<img width="328" alt="Captura de pantalla 2022-09-02 a las 13 59 49" src="https://user-images.githubusercontent.com/22323189/188138990-1a87ffea-d4c6-4623-9328-7821c31e9a74.png">

**Comment by verabehr** [comment]
We now have a field called "Title" in storyblok again and the events have been backfilled.

**Comment by joycehermosilla** [comment]
14/09 REVIEW:

- [ ] When we have only 2 events in the "Upcoming section" we should show them one next to each other (as in the photo). Right now when are only 2 we are showing a space in between. 
<img width="588" alt="Captura de pantalla 2022-09-14 a las 9 21 57" src="https://user-images.githubusercontent.com/22323189/190209236-f22950ba-b14f-442a-ac82-2947bab54359.png">

- [ ] Change the date structure: We should show the date as month, day, year ex:"September 14, 2022"
