### ISSUE TITLE
Paloma checks for PIGEON_HEALTHCHECK_PORT even when it is not needed.

### ISSUE THREAD

**Issue by measure-fi** [palomachain/paloma#458]
## What is happening?

When attempting to run the following command:
```
> palomad tx staking unbond $address 10000000000ugrain --from $user --fees 1000000ugrain --chain-id paloma-testnet-10 -y -b block
2022/08/31 20:10:51 pigeon listen port environment variable is not set
```

This happens even when executing with `--node`.

## What is the expected behaviour?

It should just run the unbond command.

**Comment by taariq** [comment]
As per #409 and #452 we still need to clear up the client blockers for palomad staking commands that healthcheck pigeon running by default. This doesn't appear to be a bug, but a feature request to optimize that some staking commands will be blocked by pigeon vs. others. unbonding should not require a pigeon healthcheck. I agree.

**Comment by verabehr** [comment]
closing for now, we may come back to this
