### ISSUE TITLE
As a pigeon, if a valset update has insufficient fee, the transaction should be replace-by-fee 

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#459]
# Background

1. Due to congestion on the target blockchain, validator set updates or any message sent by a pigeon may not have enough fees to be included in the block of the target chain. Today https://etherscan.io/tx/0xe035d3c5edf7fe371f4fec1b7ce5776813291f5b27a9694388b3cb485e4d9fb3 was over 10 hours unconfimred due to a low fee of 8gwei vs. minimum fee of 21 gwei. 
2. Due to the blocked transactions, valset updates continue to be _pending_ state as the last transaction is confirmed. This puts the security of the network at risk if a valset change has occurred.

# Done when
- [ ] valset updates that are more than one pending in a row will receive a replace_by_fee command from a pigeon to unblock the pending transaction with a higher fee. This replace_by_fee will only occur if a check on the previous transaction by a pigeon is shown as still pending on the same output account.

**Comment by verabehr** [comment]
this has not been an issue for a while, closing for now
