### ISSUE TITLE
BUG: Validator has not spent any fees for validator set updates for over 13 days and are active

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#462]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Validator is ACTIVE:
https://paloma.explorers.guru/validator/palomavaloper1p4r04ek0jnngegmw76rpx66xu9ep0kuzvcwxyy

Validator has ETH address that is in the active set. However validator has had no validator set updates in the last 13 days of this ticket.
https://etherscan.io/address/0x1Dd71EE9e7b1CfF10CCb7E12520999c2d4fB45e5

There are other addresses with the same issue:
https://etherscan.io/address/0xee9265b42ec8cecd36063b6f029396bde1e4146c

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Selective ETH addresses have this problem.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

All validator ETH addresses should participate in validator set updates.

**Comment by Vizualni** [comment]
@taariq Do you think you could ask them to send us their pigeon configuration files and all env variables which do not contain sensitive information?
