### ISSUE TITLE
Payload data as byte array

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#464]
# Background
https://www.notion.so/volumefi/EPIC-09-16-Paloma-Handles-Target-Chain-Logic-Call-Construction-from-Cosmwasm-Contracts-2b070ab0762548df82d80aed69db93be

Relevant paloma-rs issue: https://github.com/palomachain/paloma/issues/465

# Done when

- [ ] payload data is not empty and sent in the form the cosmwasm developer constructs it

**Comment by measure-fi** [comment]
@Vizualni Was wondering if you have a good idea of exactly the format you would like to use here. Happy to make up multiple contracts to test.
