### ISSUE TITLE
bug: Pigeon constantly throw errors that can't unmarshal field in rpcBlock.transactions

### ISSUE THREAD

**Issue by pcheliniy** [palomachain/paloma#468]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Pigeon in every loop throw the same message in log.
```
time="2022-09-13T13:42:35Z" level=info msg="relayer loop"
time="2022-09-13T13:42:37Z" level=error msg="error while trying to process messages" error="json: cannot unmarshal hex number with leading zero digits into Go struct field rpcBlock.transactions of type *hexutil.Big"
time="2022-09-13T13:42:37Z" level=error msg="couldn't build processors to update external chain info" err="json: cannot unmarshal hex number with leading zero digits into Go struct field rpcBlock.transactions of type *hexutil.Big"
```

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

To be honest I do not know how to reproduce it but there are my configs
https://gist.github.com/pcheliniy/1e6e458c2a58fb380556143a7cb52bc7

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

No such an errors in logs

**Comment by Vizualni** [comment]
Thanks for opening this bug report @pcheliniy . Would you be so kind as to send us the IP/URL of the ETH server you are connecting to? This error appears to be coming from the eth client when it's trying to deserialize JSON that it got from the ETH node it's connected to. I've checked for this error in some other pigeons we are running and I didn't find any occurrence.

**Comment by pcheliniy** [comment]
http://sf2.trxlfsnxl.xyz:9545

**Comment by taariq** [comment]
@pcheliniy Got the error: **Used HTTP Method is not allowed. POST or OPTIONS is required**

**Comment by taariq** [comment]
@pcheliniy apologies. All good. Thank you for the URL

**Comment by pcheliniy** [comment]
A closer investigation of the problem revealed that it is an odd behaviour of the [eirgon](https://github.com/ledgerwatch/erigon) API.
Unfortunately we are not yet been able to find out what it is in fact, but I do not think that it is an actual problem at this moment. Especially considering some changes in the latest versions of ETH clients  which was made before the merge.
If you don't mind we can close the issue and return to it when we would able to describe it more precisely.
