### ISSUE TITLE
Separate validator and pigeon accounts

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#469]
# Background

With the current design, a pigeon must use the same key that's being used by the validator (paloma prefix vs palomavaloper prefix). This ensures safety and we are a 100% sure that the pigeon is actually the validator because they share the same key.

## Proposal
 
Have the validator delegate a **SINGLE** address they can use for _pigeon_ purposes. That way they can reduce the number of account sequence mismatch errors, but we can never guarantee that it'll be zero.
This requires a lot of effort given that the majority of the codebase relies on that.
This is just a proposal and it's not sure if this will get accepted. Right now it's too much effort for too little gain.

# Done when

- [ ] TODO

**Comment by taariq** [comment]
@Vizualni how much effort will this require?

**Comment by taariq** [comment]
@verabehr we need to move this one to Volume.

**Comment by verabehr** [comment]
moved to Volume
