### ISSUE TITLE
BUG: Paloma crashes with fatal error: unexpected signal during runtime execution signal SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#471]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Paloma crashes with fatal error: unexpected signal during runtime execution
Sep 13 18:04:08 n6d1174 palomad[169399]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f78eef707fb]

Error logs and config files are here: 
https://gist.github.com/kj89/2ac4ee6e2484ab5620f3c81a1948a2a7

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

No repro at this ticket.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

LevelDB should function.

**Comment by k4b3z4** [comment]
Error logs and config from FedNet node:

https://gist.github.com/k4b3z4/19fd601071535117594f5ec7c9ee2597

**Comment by taariq** [comment]
@Vizualni feedback has been that this is LevelDB issue and recommendations are that we switch over to https://dgraph.io/docs/badger/

**Comment by Vizualni** [comment]
@taariq I am seeing that badgerdb is still in experimental phase (can be found in `~/.paloma/config/config.toml`. It doesn't really scream confidence when I read this.

**Comment by taariq** [comment]
Closing as we will stick with leveldb for now. Unsafe reset for validators to fix.

**Comment by taariq** [comment]
We are seeing these again.

**Comment by taariq** [comment]
Closing until we see them again.
