### ISSUE TITLE
Flock number

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#473]
Background:
We want to show the total Community number on the website and track in Mixpanel. The sum of Telegram, Discord, Twitter users.

Done when:
- [x] the total number of Paloma Telegram, Discord (public #general channel), Twitter followers is available as an API to the FE
- [x] the total number of Paloma Telegram, Discord (public #general channel), Twitter followers is piped to Mixpanel

**Comment by rootedbox** [comment]
https://count.palomachain.com
