### ISSUE TITLE
Gas wallet information on external chains

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#481]
# Blocked by

- a wallet smart contract (but I can mock it to test it out)

# Background

We need a way to periodically (and on-demand!) get the job's wallet info. Pigeon should be able to attest to that information by querying the smart contract wallet and providing such evidence.
We also need to store such information in paloma for further logic based on that info.

# Done when

- [ ] pigeons query that information
- [ ] paloma tx endpoint: get job's wallet info on demand
- [ ] paloma: get all currently active job's wallet infos so that pigeons can provide evidence

**Comment by verabehr** [comment]
Closing until we restart this epic
