### ISSUE TITLE
Support for pigeon_gas_fee in paloma & pigeon

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#482]
# Background

Given that pigeons can define their custom fees which they individually want to charge for running jobs, we need to make some changes to core functionalities in both paloma and pigeon codebases.

# Done when

- [ ] config place to define those changes
- [ ] send the new in the "update external chain info" 
- [ ] a common interface across paloma so that external chain information can be extracted and custom pigeon fee is included
- [ ] paloma & pigeon: should be its own ticket, but will write it once I get to it: paloma and pigeon are currently working in a way such that all pigeons can send any message. we need a way so that pigeons can send only those jobs whose fee matches what pigeons are paying for.  This is going to be big ticket because some for of synchronisation between pigeons needs to be made.

**Comment by verabehr** [comment]
closing until we restart this epic
