### ISSUE TITLE
BUG: max fee per gas less than block base fee: address 0xBaE919E4B272193544A9f18aF1fB75F918D2B1F0

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#484]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Daria Kiyan, [Sep 17, 2022 at 9:25:36 AM]:
pigeon[204419]: time="2022-09-17T18:23:14+02:00" level=warning msg="smart contract returned an error" error-message="err: max fee per gas less than block base fee: address 0xBaE919E4B272193544A9f18aF1fB75F918D2B1F0, maxFeePerGas: 9588020124 baseFee: 10033963990 (supplied gas 5225340)" message-id=227 queue-type-name=EVM/eth-main/evm-turnstone-message

1. palomad version
* v0.9.0

2. pigeon version
* App version: v0.8.0
* Build commit hash: 1958b5c988f743c3673c375c0af58947e12df125

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

{WRITE YOUR ANSWER HERE}

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Gas fee estimates should be correct to the base fee.

**Comment by taariq** [comment]
This is the Etherscan address: https://etherscan.io/address/0xBaE919E4B272193544A9f18aF1fB75F918D2B1F0

**Comment by webelf101** [comment]
This is not a bug. She had tried to send a transaction with the fetched gas price and the eth gas price got higher than fetched. So the transaction failed. It is because Ethereum blocks lower gas transactions than the current base gas fee to prevent forever pending transactions with too lower gas prices. So this failure is normal and she didn't pay any gas. I confirmed that she could send a transaction later and it succeeded. I think we can use a higher gas price than fetched one but it will spend needless more gas normally except special cases and it is OK right now.

**Comment by Vizualni** [comment]
That's actually a bug in Pigeon. @webelf101 what's the minimum that we can't go over?

**Comment by webelf101** [comment]
There is not any minimum gas price. The gas price of the next block is calculated from the gas price and usage of the last block by EIP-1559

**Comment by webelf101** [comment]
Block gas size is nearly 30,000,000 and only the transactions with higher than current block gas price can put into the block.
If 15,000,000 gas is used, the gas price of the next block is the same as the last block.
If 0 gas is used, the gas price gets lower 12.5%.
If 30,000,000 (all) gas is used, the gas price gets higher 12.5%.
For example, when 6,633,562 (22.11%) gas is used, the gas price gets lower from 16.567790953Gwei to 15.412679322Gwei (6.97%)
https://etherscan.io/block/15568150
@Vizualni

**Comment by taariq** [comment]
Normal failure due to lower base fee due to changing gas fee market.
