### ISSUE TITLE
bug: No valset updates 

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#488]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Testnet 10, paloma v0.8.1
No valset updates are happening. Last valset 750 was 28 hours ago as of this ticket creation. 
Validator percentages have changed since then. 
The network is still up and running and none of the validators present in 750 are currently jailed or left the network. 

https://docs.google.com/spreadsheets/d/1x0cYMUrPoUwgSjiKJaRu9XXW5oFwWtNHhCp9iMAQEjo/edit#gid=0

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

-

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

We should see valset updates when the percentage share of voting power changes

**Comment by taariq** [comment]
Expected this behavior may did begin possibly after the incorrect proposal for the chain upgrade. We need to have visibility into failed updates .

**Comment by Vizualni** [comment]
This was not buggy behaviour as there were no worthy snapshots. We got one 20 minutes ago https://etherscan.io/address/0x6D727250bd150A9dC006b65b6C7a0D817B02bB2e
