### ISSUE TITLE
Message size limit can allow medium size validators to prevent contract execution

### ISSUE THREAD

**Issue by measure-fi** [palomachain/paloma#491]
## Background

Cosmwasm has a maximum parameter size of 10k. For the compass contract specifically, and perhaps others, the payload will be a list of validators and a signed secondary payload. Currently we plan to use the cost saving measure of not sending more than a necessary number of validators. However this means that if a medium size validator were to pull out, we would need to replace them with more than one other validators. These new validators might push the overall payload size above the limit. Effectively this allows a medium size validator to DOS compass.

## Done when

- [ ] a design to mitigate this issue is proposed/implemented

**Comment by verabehr** [comment]
@measure-fi cc @taariq is this currently an issue on testnet or mainnet with BNB and Polygon as target chains?

**Comment by taariq** [comment]
yessss This is a security issue. We will need to work on this.

**Comment by verabehr** [comment]
moved to Volume
