### ISSUE TITLE
Bug: Failure to be included in a block. Validator Account Error Mismatch while Running Pigeon

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#492]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Validator: https://paloma.explorers.guru/validator/palomavaloper1pmx8m7glpw4pckwzrfflqp4427ynl32wjtzg5x is unable to insert transactions into cosmos blocks and continuously jailed. Unable to keep validator alive.

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Sep 21 14:54:46 rusaptos.node pigeon[1467524]: time="2022-09-21T14:54:46+03:00" level=info msg="relayer loop"
Sep 21 14:54:48 rusaptos.node pigeon[1467524]: time="2022-09-21T14:54:48+03:00" level=info msg="trying to update external chain info"
Sep 21 14:54:48 rusaptos.node pigeon[1467524]: time="2022-09-21T14:54:48+03:00" level=info msg="updating external chain infos"
Sep 21 14:54:48 rusaptos.node pigeon[1467524]: time="2022-09-21T14:54:48+03:00" level=info msg="sending account info to paloma" acc-address=0xfACCC5A327372351210Fa85425162cF9d57fC232 chain-reference-id=eth-main chain-type=EVM
Sep 21 14:54:48 rusaptos.node pigeon[1467524]: time="2022-09-21T14:54:48+03:00" level=info msg="messages to sign" message-ids="[2003]" queue-name=EVM/eth-main/evm-turnstone-message
Sep 21 14:54:48 rusaptos.node pigeon[1467524]: time="2022-09-21T14:54:48+03:00" level=info msg="signed a message" message-id=2003
Sep 21 14:54:48 rusaptos.node pigeon[1467524]: time="2022-09-21T14:54:48+03:00" level=info msg="signed messages" message-ids="[2003]" queue-name=EVM/eth-main/evm-turnstone-message signed-messages="[map[id:2003 signature:[44 224 222 39 2 20 13 125 242 246 176 114 146 216 123 227 99 136 253 129 150 104 182 140 132 253 209 43 219 240 171 232 59 100 226 135 189 227 17 191 78 188 97 157 250 89 199 164 226 246 112 134 55 123 65 79 51 84 170 150 154 124 172 171 1]]]"
Sep 21 14:54:54 rusaptos.node pigeon[1467524]: time="2022-09-21T14:54:54+03:00" level=error msg="couldn't broadcast signatures and process attestation" error="rpc error: code = InvalidArgument desc = account sequence mismatch, expected 147, got 146: incorrect account sequence: invalid request" message-ids="[2003]" queue-name=EVM/eth-main/evm-turnstone-message signed-messages="[map[id:2003 signature:[44 224 222 39 2 20 13 125 242 246 176 114 146 216 123 227 99 136 253 129 150 104 182 140 132 253 209 43 219 240 171 232 59 100 226 135 189 227 17 191 78 188 97 157 250 89 199 164 226 246 112 134 55 123 65 79 51 84 170 150 154 124 172 171 1]]]"
Sep 21 14:54:54 rusaptos.node pigeon[1467524]: time="2022-09-21T14:54:54+03:00" level=error msg="error returned in process loop" err="rpc error: code = InvalidArgument desc = account sequence mismatch, expected 147, got 146: incorrect account sequence: invalid request"
Sep 21 14:55:46 rusaptos.node pigeon[1467524]: time="2022-09-21T14:55:46+03:00" level=info msg="relayer loop"
Sep 21 14:56:46 rusaptos.node pigeon[1467524]: time="2022-09-21T14:56:46+03:00" level=info msg="relayer loop"
Sep 21 14:57:46 rusaptos.node pigeon[1467524]: time="2022-09-21T14:57:46+03:00" level=info msg="relayer loop"
Sep 21 14:58:46 rusaptos.node pigeon[1467524]: time="2022-09-21T14:58:46+03:00" level=info msg="relayer loop"
Sep 21 14:59:46 rusaptos.node pigeon[1467524]: time="2022-09-21T14:59:46+03:00" level=info msg="relayer loop"
Sep 21 15:00:46 rusaptos.node pigeon[1467524]: time="2022-09-21T15:00:46+03:00" level=info msg="relayer loop"
Sep 21 15:01:46 rusaptos.node pigeon[1467524]: time="2022-09-21T15:01:46+03:00" level=info msg="relayer loop"

Sep 21 18:02:38 rusaptos.node pigeon[1467524]: time="2022-09-21T18:02:38+03:00" level=error msg="error providing evidence for messages" error="there are 1 errors in the group:\nerror  1: context canceled\n" messages-to-provide-evidence-for="[2014]" queue-name=EVM/eth-main/validators-balances
Sep 21 18:02:46 rusaptos.node pigeon[1467524]: time="2022-09-21T18:02:46+03:00" level=info msg="relayer loop"
Sep 21 18:03:16 rusaptos.node pigeon[1467524]: time="2022-09-21T18:03:16+03:00" level=error msg="error while trying to keep pigeon alive" error="timed out after: 600000000000; timed out after waiting for tx to get included in the block"

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Transactions should be included in the block and validator should continue as per usual.

**Comment by taariq** [comment]
Further logs when attempting to unjail:

oot@rusaptos:~# palomad tx slashing unjail   --broadcast-mode=block   --from=paloma1pmx8m7glpw4pckwzrfflqp4427ynl32wam45z4   --chain-id=paloma-testnet-10   --gas=auto --fees=100ugrain -s 169
gas estimate: 77685
{"body":{"messages":[{"@type":"/cosmos.slashing.v1beta1.MsgUnjail","validator_addr":"palomavaloper1pmx8m7glpw4pckwzrfflqp4427ynl32wjtzg5x"}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[{"denom":"ugrain","amount":"100"}],"gas_limit":"77685","payer":"","granter":""}},"signatures":[]}

confirm transaction before signing and broadcasting [y/N]: y
Error: RPC error -32603 - Internal error: timed out waiting for tx to be included in a block
root@rusaptos:~# palomad tx slashing unjail   --broadcast-mode=block   --from=paloma1pmx8m7glpw4pckwzrfflqp4427ynl32wam45z4   --chain-id=paloma-testnet-10   --gas=auto --fees=100ugrain
Error: rpc error: code = InvalidArgument desc = account sequence mismatch, expected 170, got 167: incorrect account sequence: invalid request

**Comment by Vizualni** [comment]
There is nothing here that I can do about this. There must be something faulty in the user's setup. What is the pigeon version TC is running? I believe that TC's validator is lagging behind the network, thus they are getting all those account sequence mismatch errors and timeout errors. Maybe they have unstable internet connection. All of these are just wild guesses and none of them may be true.

**Comment by Vizualni** [comment]
TC should try increasing gas-adjustments for paloma in pigeon's config

**Comment by taariq** [comment]
Closing. Thanks @Vizualni
