### ISSUE TITLE
bug: It is possible to run compass-evm through submit_logic_call

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#493]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

compass-evm can call itself through the `submit_logic_call`. Right now I don't see a possible attack vector, but it's better to protect against this.

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Set https://github.com/palomachain/compass-evm/blob/master/contracts/Turnstone.vy#L36 to the address of the compass-evm that's actually running this `submit_logic_call`

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Providing arguments to `submit_logic_call` function in a way that would call itself should be prohibited and should return an error to the caller.

**Comment by taariq** [comment]
@webelf101 what do you need to do in order to delivery on this ticket?

**Comment by taariq** [comment]
@verabehr let's move this to Volume. We will need this one as well.
