### ISSUE TITLE
Eggminting bug: Cosmwasm tx succeeded, but no egg was minted

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#496]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Tx https://paloma.explorers.guru/transaction/134490C94743ED52FA7DA8FC02C4A998BE21792A5D74DB20314CA864D77E3C96
shows that egg mint was a success on Paloma. However, user received no egg in their ETH wallet. Unclear whether all eggs were minted by this transaction.

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Mint egg and not receive ERC721 tx.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Egg should mint or user should receive the error at Cosmos level that all eggs were minted.

**Comment by alipostaci2001** [comment]
https://paloma.explorers.guru/transaction/F25ECCE28FABBC70111454084A2836F5A8D985A1C54E66E3A192AB91CBF4606C


please look at this another one.   all process seems ok but There was no transaction reflected in the wallet. Thanks
