### ISSUE TITLE
Error while loading shared libraries: /lib/libwasmvm.x86_64.so: invalid ELF header

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#498]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Some new installations are receiving the error that the libwasmvm library is an invalid ELF header. This is usually related to the file not being found.

palomad.service: Failed with result 'exit-code'.
palomad.service: Scheduled restart job, restart counter is at 4.
Stopped Paloma Node.
Started Paloma Node.
/usr/local/bin/palomad: error while loading shared libraries: /lib/libwasmvm.x86_64.so: invalid ELF header

linux version 20.04

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Run new install of Palomad

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

sudo wget -P /usr/lib https://github.com/CosmWasm/wasmvm/raw/main/internal/api/libwasmvm.x86_64.so
should function without issue on new install. All links should function.

**Comment by KyErgus** [comment]
OS: Ubuntu 20.04

results: palomad.service: Failed with result 'exit-code'.
palomad.service: Scheduled restart job, restart counter is at 4.
Stopped Paloma Node.
Started Paloma Node.
/usr/local/bin/palomad: error while loading shared libraries: /lib/libwasmvm.x86_64.so: invalid ELF header


Valoper: palomavaloper10y227j9d09pckexy32v2gckerj9a0kcewgf7xy

**Comment by taariq** [comment]
Closing. Library needs to be in the correct directory.
