### ISSUE TITLE
Enable WASMD snapshot register in app.go so that wasm is supported in state sync

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#499]
# Background

This is related to issue #494 which caused validators to receive incorrect AppHash.

Paloma chain doesn't support state sync as it doesn't include wasm in RPC snapshots. As such, if you don't have the wasm directory and the wasm contract is called, your node will not be able to run the contract and generate a different state => consensus failure.

# Done when
- [ ] enable wasmd with snapshot register to keep the folder https://github.com/palomachain/paloma/blob/master/app/app.go#L421
-

**Comment by Vizualni** [comment]
Just wanted to point that that the line of code in the Done when section is not relevant for this. Wrote a bit more context in the discord.

**Comment by taariq** [comment]
Confirmed that this fix requires upgrade to 	github.com/CosmWasm/wasmd v0.28.0. Moved to #504.
