### ISSUE TITLE
Upgrade Paloma to wasmd v0.28.0

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#504]
# Background

State-sync for Coswmasm contracts referenced in #499 requires an upgrade to wasmd v0.28.0. This will resolve issues in #494 

# Done when
- [x] Upgrade Paloma to wasmd v0.28.0 https://github.com/CosmWasm/wasmd/releases/tag/v0.28.0

**Comment by Vizualni** [comment]
wasmd upgraded to 0.28

**Comment by taariq** [comment]
@Vizualni the Cosmwasm team recommended that we upgrade to the latest https://github.com/CosmWasm/wasmd/releases/tag/v0.29.0-rc1
