### ISSUE TITLE
bug: Binance Chain - missing chain config error

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#510]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

server 173.255.229.106
After the upgrade to `bnb-main`, pigeon returns following error: 
```
Sep 28 22:12:17 localhost pigeon[450208]: {"error":"base error: dial unix: missing address\nwrapped error: base error: base error: missing chain config\nwrapped error: unrecoverable error\nwrapped error: reference chain id: bnb-main","level":"error","msg":"error while trying to process messages","time":"2022-09-28T22:12:17Z"}
```

I've double checked my config files. Regenerated my keys, and restarted pigeond after every change. 

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

Pigeon config yaml and service files: https://gist.github.com/verabehr/c48ee747e83c26f95db3544f158809f0

```
palomad version
v0.9.0
```

```
pigeon version
App version: v0.8.1
Build commit hash: cb743291054fa1b0a336662258a4efde6a968e3d
```

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

start pigeon and palomad services

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

no errors

**Comment by verabehr** [comment]
Update: Removing line 23 in my config.yaml (see gist linked above) seems to have solved the issue

**Comment by taariq** [comment]
Additional users with the same experience https://gist.github.com/alipostaci2001/b3b5e00273abc0aefc968b77b27a1801

**Comment by verabehr** [comment]
reopening as I'm still seeing this error (with and without empty line btw)

**Comment by taariq** [comment]
@Vizualni This is also still happening even though the validator has 0.5 BNB https://bscscan.com/address/0x81ce4997b1025158f680B242a96AF545E59d6f6e

**Comment by verabehr** [comment]
closing as user error
