### ISSUE TITLE
BUG: BNB chain data not updating in Paloma. Account Sequence mismatch Error. Validator jailed

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#523]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

time="2022-10-05T09:06:18+02:00" level=info msg="sending account info to paloma" acc-address=0x6dc59EE4bdFa2C791229004f29b08F783491a934 chain-reference-id=bnb-main chain-type=evm
time="2022-10-05T09:06:18+02:00" level=info msg="sending account info to paloma" acc-address=0x6dc59EE4bdFa2C791229004f29b08F783491a934 chain-reference-id=eth-main chain-type=evm
time="2022-10-05T09:06:25+02:00" level=error msg="couldn't update external chain info. Will try again." err="rpc error: code = InvalidArgument desc = account sequence mismatch, expected 76, got 75: incorrect account sequence: invalid request"
time="2022-10-05T09:06:58+02:00" level=error msg="couldn't broadcast signatures and process attestation" error="context canceled" message-ids="[78]" queue-name=evm/eth-main/evm-turnstone-message signed-messages="[map[id:78]]"

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

name: paloma
server_name: palomad
version: v0.10.2
commit: 0a754c6a0d8420adac5d8018b79f8502caecd168

App version: v0.9.1
commit: f6f4a62cd5d217067f7177bf683807eb287bda98

`paloma gas-adjustment: 1.5` on .pigeon/config.yaml

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Pigeon attestation on BNB chain fails

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

BNB chain attestation should work and tx inserted into block so validator is not jailed.

**Comment by Vizualni** [comment]
The main error here is: `account sequence mismatch, expected 76, got 75: incorrect account sequence: invalid request`. Do they have any script running in the background which is writing txs in favour of the validator? (e.g. increase stake every 5 minutes or something like that). Or do they have an older pigeon running in the background? Or they node is really lagging behind so that the account sequences cannot be synced.

**Comment by taariq** [comment]
@verabehr you are having this issue.

**Comment by measure-fi** [comment]
On mobile. Someone can try sshing to zenaida-0, then do `tmux a` then
ctrl-c and that will stop my script. It doesn't interface with this other
account but we can try it.

**Comment by taariq** [comment]
We will need new signing key for relayer-validators. Clsoing for now.
