### ISSUE TITLE
Add Codeql analyzer to CI workflow

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#526]
# Background

_Describe the problem that we are trying to solve with this feature._
_If a path to a solution is known, feel free to write it down, but have an open mind_

Alex from Confio suggested that adding https://github.com/CosmWasm/wasmd/blob/main/.github/workflows/codeql-analizer.yml will make our lives easier.

# Done when

- [ ] https://github.com/CosmWasm/wasmd/blob/main/.github/workflows/codeql-analizer.yml was added to Paloma's CI

**Comment by taariq** [comment]
Let's make our Cosmwasm debugging lives easier!

**Comment by taariq** [comment]
Closing as distraction to gas management.
