### ISSUE TITLE
Paloma Nest - SEND Grain

### ISSUE THREAD

**Issue by joycehermosilla** [palomachain/paloma#539]
Designs: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=3382%3A246
Assets: https://drive.google.com/drive/u/1/folders/1mPLJ5V6h0TVTLvNvjxZ_gCzuicBgUCT0

As a user of Paloma Wallet, I want to be able to send GRAIN to other Paloma wallets.

The user will access to SEND flow from the Balance view.
<img width="342" alt="Captura de pantalla 2022-10-17 a las 21 29 43" src="https://user-images.githubusercontent.com/22323189/196265689-65946892-ef3c-46ab-b277-2d4da13290c5.png">

After pressing the button SEND on the Balance view the user will be redirect to the Send view: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=3400%3A404
<img width="321" alt="Captura de pantalla 2022-10-17 a las 21 35 51" src="https://user-images.githubusercontent.com/22323189/196266707-516f50e5-2374-4c59-8003-7d81efa5bf44.png">

- [x] When on the Send view the user will need to input a recipient address (Paloma) and an amount. 
- [x] The user can optionally add a Memo.
<img width="424" alt="Captura de pantalla 2022-10-17 a las 21 33 49" src="https://user-images.githubusercontent.com/22323189/196266392-9b3a1bf6-890d-4603-8a01-f01cb2534da4.png">

- [x] The user should be able to see the current balance of the selected wallet.
<img width="204" alt="Captura de pantalla 2022-10-17 a las 21 34 04" src="https://user-images.githubusercontent.com/22323189/196266430-2b048d0e-abd7-463e-b97f-a666fca2746e.png">

- [x] User should input a Password for being able to Submit the transaction.
<img width="422" alt="Captura de pantalla 2022-10-17 a las 21 34 27" src="https://user-images.githubusercontent.com/22323189/196266489-c8a259d5-2ff6-42db-b01b-ceb462c23889.png">

- [x] After inputed a Password the button will change to enable 
<img width="308" alt="Captura de pantalla 2022-10-17 a las 21 36 22" src="https://user-images.githubusercontent.com/22323189/196266774-463aa66a-27ba-4c92-9623-e1dec147742c.png">

- [x] If the user input only a password and not a receipent adress should show this error
<img width="427" alt="Captura de pantalla 2022-10-17 a las 21 36 42" src="https://user-images.githubusercontent.com/22323189/196266830-b3da5ed1-5f7b-4356-abba-7c2dd2ef2a50.png">

- [x] If the user input only a password and not an amount of GRAINS should show this error
<img width="430" alt="Captura de pantalla 2022-10-17 a las 21 37 53" src="https://user-images.githubusercontent.com/22323189/196267029-572d6303-39af-4f4a-b2c3-3cf53e602546.png">

- [ ] We should show the breakdown of cost for the transaction
<img width="457" alt="Captura de pantalla 2022-10-17 a las 21 38 01" src="https://user-images.githubusercontent.com/22323189/196267054-85bed545-9e40-4cba-8584-2b461c006c6c.png">

- [ ] When the wallet adress is invalid should show this error
<img width="218" alt="Captura de pantalla 2022-10-17 a las 21 40 39" src="https://user-images.githubusercontent.com/22323189/196267529-588a3c5d-0cbc-4536-8481-712ab2463408.png">

- [ ] When the GRAIN amount is not enough should show this error
<img width="278" alt="Captura de pantalla 2022-10-17 a las 21 43 38" src="https://user-images.githubusercontent.com/22323189/196268066-f08d701f-15af-4089-99d3-4a60630d2ebc.png">

- [x] If the user inputs the correct recipient, amount, and password the transaction must start being processed.
<img width="462" alt="Captura de pantalla 2022-10-17 a las 21 45 12" src="https://user-images.githubusercontent.com/22323189/196268394-f5ab193d-9dac-47ff-8f67-86dd067238ea.png">

- [x] If the transaction was successfully completed we should show this view.
<img width="461" alt="Captura de pantalla 2022-10-17 a las 21 45 25" src="https://user-images.githubusercontent.com/22323189/196268432-51e67428-15a5-4100-b9ec-0a929658622c.png">

**Comment by verabehr** [comment]
@joycehermosilla @wdev733 I checked off the done items. 

1. Let's change "nesting transaction" to "hatching transactions"
2. I'm not sure the error messages make sense if we don't allow the user to click the button before all fields are filled in. I think it's not required. The user would see an error as soon as they enter one field which can be annoying.
