### ISSUE TITLE
Paloma Nest - ACTIVITY view

### ISSUE THREAD

**Issue by joycehermosilla** [palomachain/paloma#540]
As a user, I want to be able to see my last transaction history.

Design: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=3400%3A1006
Assets: https://drive.google.com/drive/u/1/folders/1mPLJ5V6h0TVTLvNvjxZ_gCzuicBgUCT0

- [x] We will show the last 5 transactions of the wallet address.
<img width="263" alt="Captura de pantalla 2022-10-17 a las 21 52 50" src="https://user-images.githubusercontent.com/22323189/196270184-fa5f3ca1-de44-4896-90f7-46c1174e8fd6.png">

- [x] The types of transactions are RECEIVE, SWAP, SEND, SPEND and CONTRACT INTERACTION. Each will have a special icon, that will show the date, the platform/interface where the transaction was made and the amount of grain that was used or received.

**Comment by verabehr** [comment]
@joycehermosilla this looks good to me. We can't test swap/spend/contract yet though
