### ISSUE TITLE
bug: paloma_sdk.py wallet and bank's instances not connecting 

### ISSUE THREAD

**Issue by fieldtheory123** [palomachain/paloma#542]
# What is happening?
paloma_sdk's LCDClient wallet and bank not connecting and raising 404 errors when called, while block height and similar queries work. 
<details>

  <summary>wallet code:</summary>

from paloma_sdk.client.lcd import LCDClient
from paloma_sdk.key.mnemonic import MnemonicKey
paloma = LCDClient(chain_id="paloma-testnet-12", url="https://testnet.palomaswap.com")
mk = MnemonicKey(mnemonic=MNEMONIC)
wallet = paloma.wallet(mk)
wallet.account_number()

</details>

<details>
  <summary>wallet error:</summary>

https://testnet.palomaswap.com/cosmos/auth/v1beta1/accounts/paloma1puu5exhjyacwh3wszhcljwfjznv58zxkmde7fu
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\lcdclient.py in _get(self, endpoint, params)
    107             try:
--> 108                 result = await response.json(content_type=None)
    109             except JSONDecodeError:

~\Anaconda3\lib\site-packages\aiohttp\client_reqrep.py in json(self, encoding, loads, content_type)
   1118 
-> 1119         return loads(stripped.decode(encoding))
   1120 

~\Anaconda3\lib\json\__init__.py in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    356             parse_constant is None and object_pairs_hook is None and not kw):
--> 357         return _default_decoder.decode(s)
    358     if cls is None:

~\Anaconda3\lib\json\decoder.py in decode(self, s, _w)
    339         if end != len(s):
--> 340             raise JSONDecodeError("Extra data", s, end)
    341         return obj

JSONDecodeError: Extra data: line 1 column 5 (char 4)

During handling of the above exception, another exception occurred:

LCDResponseError                          Traceback (most recent call last)
<ipython-input-14-3debbc8194ea> in <module>
----> 1 wallet.account_number()

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\wallet.py in account_number(self)
     72     def account_number(self) -> int:
     73         """Fetches account number for the account associated with the Key."""
---> 74         res = self.lcd.auth.account_info(self.key.acc_address)
     75         return res.account_number
     76 

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\api\_base.py in decorator(wrapped, instance, args, kwargs)
     27     @wrapt.decorator
     28     def decorator(wrapped, instance, args, kwargs):
---> 29         return instance._run_sync(async_call(instance, *args, **kwargs))
     30 
     31     return decorator

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\api\_base.py in _run_sync(self, coroutine)
     11     def _run_sync(self, coroutine):
     12         """Runs an asynchronous coroutine synchronously."""
---> 13         return self._c.loop.run_until_complete(coroutine)
     14 
     15     @staticmethod

~\Anaconda3\lib\site-packages\nest_asyncio.py in run_until_complete(self, future)
     87                 raise RuntimeError(
     88                     'Event loop stopped before Future completed.')
---> 89             return f.result()
     90 
     91     def _run_once(self):

~\Anaconda3\lib\asyncio\futures.py in result(self)
    176         self.__log_traceback = False
    177         if self._exception is not None:
--> 178             raise self._exception
    179         return self._result
    180 

~\Anaconda3\lib\asyncio\tasks.py in __step(***failed resolving arguments***)
    278                 # We use the `send` method directly, because coroutines
    279                 # don't have `__iter__` and `__next__` methods.
--> 280                 result = coro.send(None)
    281             else:
    282                 result = coro.throw(exc)

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\api\auth.py in account_info(self, address, params)
     34             Union[BaseAccount, ContinuousVestingAccount, DelayedVestingAccount, PeriodicVestingAccount]: account information
     35         """
---> 36         result = await self._c._get(f"/cosmos/auth/v1beta1/accounts/{address}", params)
     37         return Account.from_data(result["account"])
     38 

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\lcdclient.py in _get(self, *args, **kwargs)
    290         )
    291         try:
--> 292             result = await super()._get(*args, **kwargs)
    293         finally:
    294             await self.session.close()

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\lcdclient.py in _get(self, endpoint, params)
    108                 result = await response.json(content_type=None)
    109             except JSONDecodeError:
--> 110                 raise LCDResponseError(message=str(response.reason), response=response)
    111             if not 200 <= response.status < 299:
    112                 raise LCDResponseError(message=str(result), response=response)

LCDResponseError: Status 404 - Not Found

</details>

<details>

  <summary>bank code:</summary>

paloma.bank.balance(
        address="paloma1rk6tvacasnnyssfnn00zl7wz43pjnpn7vayqv6"
    )

</details>

<details>

  <summary>bank error:</summary>

https://testnet.palomaswap.com/cosmos/bank/v1beta1/balances/paloma1puu5exhjyacwh3wszhcljwfjznv58zxkmde7fu
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\lcdclient.py in _get(self, endpoint, params)
    107             try:
--> 108                 result = await response.json(content_type=None)
    109             except JSONDecodeError:

~\Anaconda3\lib\site-packages\aiohttp\client_reqrep.py in json(self, encoding, loads, content_type)
   1118 
-> 1119         return loads(stripped.decode(encoding))
   1120 

~\Anaconda3\lib\json\__init__.py in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    356             parse_constant is None and object_pairs_hook is None and not kw):
--> 357         return _default_decoder.decode(s)
    358     if cls is None:

~\Anaconda3\lib\json\decoder.py in decode(self, s, _w)
    339         if end != len(s):
--> 340             raise JSONDecodeError("Extra data", s, end)
    341         return obj

JSONDecodeError: Extra data: line 1 column 5 (char 4)

During handling of the above exception, another exception occurred:

LCDResponseError                          Traceback (most recent call last)
<ipython-input-20-8b3ebd5a96d5> in <module>
----> 1 paloma.bank.balance(
      2         address="paloma1puu5exhjyacwh3wszhcljwfjznv58zxkmde7fu"
      3     )

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\api\_base.py in decorator(wrapped, instance, args, kwargs)
     27     @wrapt.decorator
     28     def decorator(wrapped, instance, args, kwargs):
---> 29         return instance._run_sync(async_call(instance, *args, **kwargs))
     30 
     31     return decorator

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\api\_base.py in _run_sync(self, coroutine)
     11     def _run_sync(self, coroutine):
     12         """Runs an asynchronous coroutine synchronously."""
---> 13         return self._c.loop.run_until_complete(coroutine)
     14 
     15     @staticmethod

~\Anaconda3\lib\site-packages\nest_asyncio.py in run_until_complete(self, future)
     87                 raise RuntimeError(
     88                     'Event loop stopped before Future completed.')
---> 89             return f.result()
     90 
     91     def _run_once(self):

~\Anaconda3\lib\asyncio\futures.py in result(self)
    176         self.__log_traceback = False
    177         if self._exception is not None:
--> 178             raise self._exception
    179         return self._result
    180 

~\Anaconda3\lib\asyncio\tasks.py in __step(***failed resolving arguments***)
    278                 # We use the `send` method directly, because coroutines
    279                 # don't have `__iter__` and `__next__` methods.
--> 280                 result = coro.send(None)
    281             else:
    282                 result = coro.throw(exc)

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\api\bank.py in balance(self, address, params)
     23             Pagination: pagination info
     24         """
---> 25         res = await self._c._get(f"/cosmos/bank/v1beta1/balances/{address}", params)
     26         return Coins.from_data(res["balances"]), res.get("pagination")
     27 

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\lcdclient.py in _get(self, *args, **kwargs)
    290         )
    291         try:
--> 292             result = await super()._get(*args, **kwargs)
    293         finally:
    294             await self.session.close()

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\lcdclient.py in _get(self, endpoint, params)
    108                 result = await response.json(content_type=None)
    109             except JSONDecodeError:
--> 110                 raise LCDResponseError(message=str(response.reason), response=response)
    111             if not 200 <= response.status < 299:
    112                 raise LCDResponseError(message=str(result), response=response)

LCDResponseError: Status 404 - Not Found

</details>

{WRITE YOUR ANSWER HERE}

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

{WRITE YOUR ANSWER HERE}

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

{WRITE YOUR ANSWER HERE}

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

{WRITE YOUR ANSWER HERE}

**Comment by rootedbox** [comment]
@fieldtheory123 please use lcd.testnet.palomaswap.com

**Comment by rootedbox** [comment]
https://lcd.testnet.palomaswap.com

**Comment by fieldtheory123** [comment]
paloma = LCDClient(chain_id="paloma-testnet-12", url="https://lcd.testnet.palomaswap.com")     
fetch = paloma.tendermint.block_info() #['block']['header']['height']
https://lcd.testnet.palomaswap.com/block?height=
---------------------------------------------------------------------------
LCDResponseError                          Traceback (most recent call last)
<ipython-input-3-c1a701c0f8c1> in <module>
----> 1 fetch = paloma.tendermint.block_info() #['block']['header']['height']

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\api\_base.py in decorator(wrapped, instance, args, kwargs)
     27     @wrapt.decorator
     28     def decorator(wrapped, instance, args, kwargs):
---> 29         return instance._run_sync(async_call(instance, *args, **kwargs))
     30 
     31     return decorator

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\api\_base.py in _run_sync(self, coroutine)
     11     def _run_sync(self, coroutine):
     12         """Runs an asynchronous coroutine synchronously."""
---> 13         return self._c.loop.run_until_complete(coroutine)
     14 
     15     @staticmethod

~\Anaconda3\lib\site-packages\nest_asyncio.py in run_until_complete(self, future)
     87                 raise RuntimeError(
     88                     'Event loop stopped before Future completed.')
---> 89             return f.result()
     90 
     91     def _run_once(self):

~\Anaconda3\lib\asyncio\futures.py in result(self)
    176         self.__log_traceback = False
    177         if self._exception is not None:
--> 178             raise self._exception
    179         return self._result
    180 

~\Anaconda3\lib\asyncio\tasks.py in __step(***failed resolving arguments***)
    278                 # We use the `send` method directly, because coroutines
    279                 # don't have `__iter__` and `__next__` methods.
--> 280                 result = coro.send(None)
    281             else:
    282                 result = coro.throw(exc)

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\api\tendermint.py in block_info(self, height, params)
     58         """
     59         x = "" if height is None else height
---> 60         return await self._c._get(f"/block?height={x}", params)
     61 
     62 

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\lcdclient.py in _get(self, *args, **kwargs)
    290         )
    291         try:
--> 292             result = await super()._get(*args, **kwargs)
    293         finally:
    294             await self.session.close()

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\lcdclient.py in _get(self, endpoint, params)
    110                 raise LCDResponseError(message=str(response.reason), response=response)
    111             if not 200 <= response.status < 299:
--> 112                 raise LCDResponseError(message=str(result), response=response)
    113         self.last_request_height = (
    114             result.get("height") if result else self.last_request_height

LCDResponseError: Status 501 - {'code': 12, 'message': 'Not Implemented', 'details': []}

**Comment by fieldtheory123** [comment]
paloma = LCDClient(chain_id="paloma-testnet-12", url="https://lcd.testnet.palomaswap.com")     
fetch = paloma.tendermint.block_info() 
fetch = paloma.tendermint.block_info() #['block']['header']['height']
https://lcd.testnet.palomaswap.com/block?height=latest
---------------------------------------------------------------------------
LCDResponseError                          Traceback (most recent call last)
<ipython-input-3-c1a701c0f8c1> in <module>
----> 1 fetch = paloma.tendermint.block_info() #['block']['header']['height']

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\api\_base.py in decorator(wrapped, instance, args, kwargs)
     27     @wrapt.decorator
     28     def decorator(wrapped, instance, args, kwargs):
---> 29         return instance._run_sync(async_call(instance, *args, **kwargs))
     30 
     31     return decorator

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\api\_base.py in _run_sync(self, coroutine)
     11     def _run_sync(self, coroutine):
     12         """Runs an asynchronous coroutine synchronously."""
---> 13         return self._c.loop.run_until_complete(coroutine)
     14 
     15     @staticmethod

~\Anaconda3\lib\site-packages\nest_asyncio.py in run_until_complete(self, future)
     87                 raise RuntimeError(
     88                     'Event loop stopped before Future completed.')
---> 89             return f.result()
     90 
     91     def _run_once(self):

~\Anaconda3\lib\asyncio\futures.py in result(self)
    176         self.__log_traceback = False
    177         if self._exception is not None:
--> 178             raise self._exception
    179         return self._result
    180 

~\Anaconda3\lib\asyncio\tasks.py in __step(***failed resolving arguments***)
    278                 # We use the `send` method directly, because coroutines
    279                 # don't have `__iter__` and `__next__` methods.
--> 280                 result = coro.send(None)
    281             else:
    282                 result = coro.throw(exc)

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\api\tendermint.py in block_info(self, height, params)
     58         """
     59         x = "latest" if height is None else height
---> 60         return await self._c._get(f"/block?height={x}", params)
     61 
     62 

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\lcdclient.py in _get(self, *args, **kwargs)
    290         )
    291         try:
--> 292             result = await super()._get(*args, **kwargs)
    293         finally:
    294             await self.session.close()

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\lcdclient.py in _get(self, endpoint, params)
    110                 raise LCDResponseError(message=str(response.reason), response=response)
    111             if not 200 <= response.status < 299:
--> 112                 raise LCDResponseError(message=str(result), response=response)
    113         self.last_request_height = (
    114             result.get("height") if result else self.last_request_height

LCDResponseError: Status 501 - {'code': 12, 'message': 'Not Implemented', 'details': []}

**Comment by fieldtheory123** [comment]
paloma=LCDClient(chain_id='paloma-testnet-12',url="https://lcd.testnet.palomaswap.com")
paloma=LCDClient(chain_id='paloma-testnet-12',url="https://lcd.testnet.palomaswap.com")
fetch = paloma.tendermint.block_info() #['block']['header']['height']
https://lcd.testnet.palomaswap.com/block?height=
---------------------------------------------------------------------------
LCDResponseError                          Traceback (most recent call last)
<ipython-input-6-c1a701c0f8c1> in <module>
----> 1 fetch = paloma.tendermint.block_info() #['block']['header']['height']

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\api\_base.py in decorator(wrapped, instance, args, kwargs)
     27     @wrapt.decorator
     28     def decorator(wrapped, instance, args, kwargs):
---> 29         return instance._run_sync(async_call(instance, *args, **kwargs))
     30 
     31     return decorator

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\api\_base.py in _run_sync(self, coroutine)
     11     def _run_sync(self, coroutine):
     12         """Runs an asynchronous coroutine synchronously."""
---> 13         return self._c.loop.run_until_complete(coroutine)
     14 
     15     @staticmethod

~\Anaconda3\lib\site-packages\nest_asyncio.py in run_until_complete(self, future)
     87                 raise RuntimeError(
     88                     'Event loop stopped before Future completed.')
---> 89             return f.result()
     90 
     91     def _run_once(self):

~\Anaconda3\lib\asyncio\futures.py in result(self)
    176         self.__log_traceback = False
    177         if self._exception is not None:
--> 178             raise self._exception
    179         return self._result
    180 

~\Anaconda3\lib\asyncio\tasks.py in __step(***failed resolving arguments***)
    278                 # We use the `send` method directly, because coroutines
    279                 # don't have `__iter__` and `__next__` methods.
--> 280                 result = coro.send(None)
    281             else:
    282                 result = coro.throw(exc)

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\api\tendermint.py in block_info(self, height, params)
     58         """
     59         x = "" if height is None else height
---> 60         return await self._c._get(f"/block?height={x}", params)
     61 
     62 

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\lcdclient.py in _get(self, *args, **kwargs)
    290         )
    291         try:
--> 292             result = await super()._get(*args, **kwargs)
    293         finally:
    294             await self.session.close()

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\lcdclient.py in _get(self, endpoint, params)
    110                 raise LCDResponseError(message=str(response.reason), response=response)
    111             if not 200 <= response.status < 299:
--> 112                 raise LCDResponseError(message=str(result), response=response)
    113         self.last_request_height = (
    114             result.get("height") if result else self.last_request_height

LCDResponseError: Status 501 - {'code': 12, 'message': 'Not Implemented', 'details': []}

**Comment by fieldtheory123** [comment]
paloma.bank.balance(
        address="paloma1rk6tvacasnnyssfnn00zl7wz43pjnpn7vayqv6"
    )

https://lcd.testnet.palomaswap.com/cosmos/bank/v1beta1/balances/paloma1rk6tvacasnnyssfnn00zl7wz43pjnpn7vayqv6
---------------------------------------------------------------------------
LCDResponseError                          Traceback (most recent call last)
<ipython-input-7-31e6a71f7ed2> in <module>
----> 1 paloma.bank.balance(
      2         address="paloma1rk6tvacasnnyssfnn00zl7wz43pjnpn7vayqv6"
      3     )

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\api\_base.py in decorator(wrapped, instance, args, kwargs)
     27     @wrapt.decorator
     28     def decorator(wrapped, instance, args, kwargs):
---> 29         return instance._run_sync(async_call(instance, *args, **kwargs))
     30 
     31     return decorator

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\api\_base.py in _run_sync(self, coroutine)
     11     def _run_sync(self, coroutine):
     12         """Runs an asynchronous coroutine synchronously."""
---> 13         return self._c.loop.run_until_complete(coroutine)
     14 
     15     @staticmethod

~\Anaconda3\lib\site-packages\nest_asyncio.py in run_until_complete(self, future)
     87                 raise RuntimeError(
     88                     'Event loop stopped before Future completed.')
---> 89             return f.result()
     90 
     91     def _run_once(self):

~\Anaconda3\lib\asyncio\futures.py in result(self)
    176         self.__log_traceback = False
    177         if self._exception is not None:
--> 178             raise self._exception
    179         return self._result
    180 

~\Anaconda3\lib\asyncio\tasks.py in __step(***failed resolving arguments***)
    278                 # We use the `send` method directly, because coroutines
    279                 # don't have `__iter__` and `__next__` methods.
--> 280                 result = coro.send(None)
    281             else:
    282                 result = coro.throw(exc)

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\api\bank.py in balance(self, address, params)
     23             Pagination: pagination info
     24         """
---> 25         res = await self._c._get(f"/cosmos/bank/v1beta1/balances/{address}", params)
     26         return Coins.from_data(res["balances"]), res.get("pagination")
     27 

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\lcdclient.py in _get(self, *args, **kwargs)
    290         )
    291         try:
--> 292             result = await super()._get(*args, **kwargs)
    293         finally:
    294             await self.session.close()

~\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\lcdclient.py in _get(self, endpoint, params)
    110                 raise LCDResponseError(message=str(response.reason), response=response)
    111             if not 200 <= response.status < 299:
--> 112                 raise LCDResponseError(message=str(result), response=response)
    113         self.last_request_height = (
    114             result.get("height") if result else self.last_request_height

LCDResponseError: Status 400 - {'code': 3, 'message': 'rpc error: code = InvalidArgument desc = invalid address: decoding bech32 failed: invalid checksum (expected junrul got vayqv6): invalid request', 'details': []}

**Comment by fieldtheory123** [comment]
The issue is now resolved
