### ISSUE TITLE
BUG: Python SDK contains a file with terra in it's name

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#543]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

https://github.com/palomachain/paloma.py/blob/main/paloma_sdk/client/localterra.py should be ...localpaloma.py

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

{WRITE YOUR ANSWER HERE}

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

{WRITE YOUR ANSWER HERE}

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

{WRITE YOUR ANSWER HERE}

**Comment by taariq** [comment]
@rootedbox & @verabehr: is this fixed? If so, please close?

**Comment by verabehr** [comment]
not yet fixed. updated landing date

**Comment by taariq** [comment]
Closed with https://github.com/palomachain/paloma.py/pull/2. @rootedbox please confirm if needs to re-open.
