### ISSUE TITLE
bug: some validators are getting jailed due to pigeon being inactive when pigeon is running

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#547]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Some validators are getting jailed due to pigeon being inactive although pigeon is running. The jail reason is `validator's pigeon has been inactive`. This seems to happen after the validator was originally jailed because of a valid issue with pigeon (i.e. not enough funds in the ETH or BNB account).
Simply unjaling the validator after the external account balances have been replenished causes the issue, restarting pigeon solves the issue

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

Last instance: 
https://t.me/palomachain/27142
Corresponding logs for this validator 
<img width="1066" alt="Screen Shot 2022-10-21 at 2 44 06 PM" src="https://user-images.githubusercontent.com/19958639/197267669-30e0da07-1cee-49b6-8bc4-3223b0a0c008.png">
<img width="1017" alt="Screen Shot 2022-10-21 at 2 44 16 PM" src="https://user-images.githubusercontent.com/19958639/197267670-8513172b-fb53-453e-881d-ff164d13aa4b.png">

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

{WRITE YOUR ANSWER HERE}

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

TBD - best solution may be to stop pigeon if validator is getting jailed for a pigeon issue

**Comment by verabehr** [comment]
Tested this out with my validator. After unjail, pigeon ran into an account sequence mismatch error when trying to send the "keep alive" message which caused my validator to be jailed again. 

**Unjail transactions**: https://paloma.explorers.guru/transaction/BB1D32934452E1F3E7E168A4CCF91DB914517412BD78EDA6A19360EA42F1916C
**Logs**: 

```Oct 24 15:51:45 localhost pigeon[675738]: {"alive-until":"2022-10-22T15:22:17.037000045Z","level":"debug","msg":"checking keep alive","should-send-keep-alive":true,"time":"2022-10-24T15:51:45Z","time-now":"2022-10-24T15:51:45.7065727Z","ttl":-174568669572655}
Oct 24 15:51:52 localhost pigeon[675738]: {"error":"rpc error: code = InvalidArgument desc = account sequence mismatch, expected 8740, got 8739: incorrect account sequence: invalid request","level":"error","msg":"error while trying to keep pigeon alive","time":"2022-10-24T15:51:52Z"}
Oct 24 15:52:15 localhost pigeon[675738]: {"level":"debug","msg":"querying get alive time","time":"2022-10-24T15:52:15Z"}
Oct 24 15:52:15 localhost pigeon[675738]: {"level":"info","msg":"relayer loop","time":"2022-10-24T15:52:15Z"}
Oct 24 15:52:15 localhost pigeon[675738]: {"alive-until":"2022-10-22T15:22:17.037000045Z","level":"debug","msg":"checking keep alive","should-send-keep-alive":true,"time":"2022-10-24T15:52:15Z","time-now":"2022-10-24T15:52:15.70679334Z","ttl":-174598669793295}
Oct 24 15:52:17 localhost pigeon[675738]: {"level":"debug","msg":"got 0 messages from evm/bnb-main/evm-turnstone-message","queue-name":"evm/bnb-main/evm-turnstone-message","time":"2022-10-24T15:52:17Z"}
Oct 24 15:52:17 localhost pigeon[675738]: {"level":"debug","msg":"got 0 messages from evm/bnb-main/validators-balances","queue-name":"evm/bnb-main/validators-balances","time":"2022-10-24T15:52:17Z"}
Oct 24 15:52:17 localhost pigeon[675738]: {"level":"info","message-ids":[4540],"msg":"messages to sign","queue-name":"evm/eth-main/evm-turnstone-message","time":"2022-10-24T15:52:17Z"}
Oct 24 15:52:17 localhost pigeon[675738]: {"level":"info","message-id":4540,"msg":"signed a message","time":"2022-10-24T15:52:17Z"}
Oct 24 15:52:17 localhost pigeon[675738]: {"level":"info","message-ids":[4540],"msg":"signed messages","queue-name":"evm/eth-main/evm-turnstone-message","signed-messages":[{"id":4540}],"time":"2022-10-24T15:52:17Z"}
Oct 24 15:52:17 localhost pigeon[675738]: {"id":4540,"level":"debug","msg":"broadcasting signed message","queue-type-name":"evm/eth-main/evm-turnstone-message","time":"2022-10-24T15:52:17Z"}
Oct 24 15:52:21 localhost pigeon[675738]: {"error":"rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: validator palomavaloper18d4cfq63h4a9cz49d86pr84hpang7yvq04tyc6 cannot be a pigeon: validator is jailed: invalid request","level":"error","msg":"error while trying to keep pigeon alive","time":"2022-10-24T15:52:21Z"}```

**Comment by secard51** [comment]
I started to have the same problem with the new chain, I was not having a problem with testnet-12

**Comment by secard51** [comment]
@verabehr try pls

sed -i.bak -e 's|^pruning *=.*|pruning = "custom"|; s|^pruning-keep-recent *=.*|pruning-keep-recent = "100"|; s|^pruning-keep-every *=.*|pruning-keep-every = "0"|; s|^pruning-interval *=.*|pruning-interval = "10"|' $HOME/.paloma/config/app.toml

sed -i 's|^indexer *=.*|indexer = "kv"|' $HOME/.paloma/config/config.toml
