### ISSUE TITLE
bug: Paloma website total messages sent shows 0 sometimes

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#555]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Intermittently the website shows 0 as total number of messages sent. This also happened during an investor meeting

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

https://www.loom.com/share/8fd6f757cccd4b939ee2746c1038c694

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Numbers should never be 0 on website

**Comment by verabehr** [comment]
same thing just happened wiht the flock number @rootedbox I just went to the site (no refreshs) 
<img width="923" alt="Screen Shot 2022-10-26 at 7 33 46 PM" src="https://user-images.githubusercontent.com/19958639/198108159-e02a1066-6ae9-4357-9a09-b7c0e46f2fbb.png">

**Comment by verabehr** [comment]
@rootedbox still seeing this issue on the flock number - reopening

**Comment by rootedbox** [comment]
put in catches so if the system has an issue it won't die.. put default values in the front end just in case the back end does die.. put in longer waits between getting data because twitter was complaining.
