### ISSUE TITLE
Pigeon Bug when Sending signatures to BNB Compass-EVM: Unknown desc = account sequence mismatch

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#567]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Pigeon is attempting to broadcast signatures to BNB chain. Paloma attempts to execute message transaction, but returns error: 
`Nov 04 17:40:31 localhost pigeon[935711]: {"error":"rpc error: code = Unknown desc = rpc error: code = Unknown desc = account sequence mismatch, expected 2620, got 2619: incorrect account sequence [cosmos/cosmos-sdk@v0.45.10/x/auth/ante/sigverify.go:265] With gas wanted: '0' and gas used: '34713' : unknown request","level":"error","message-ids":[174],"msg":"couldn't broadcast signatures and process attestation","queue-name":"evm/bnb-main/evm-turnstone-message","signed-messages":[{"id":174}],"time":"2022-11-04T17:40:31Z"}
Nov 04 17:40:31 localhost pigeon[935711]: {"err":"rpc error: code = Unknown desc = rpc error: code = Unknown desc = account sequence mismatch, expected 2620, got 2619: incorrect account sequence [cosmos/cosmos-sdk@v0.45.10/x/auth/ante/sigverify.go:265] With gas wanted: '0' and gas used: '34713' : unknown request","level":"error","msg":"error returned in process loop","time":"2022-11-04T17:40:31Z"}`

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i></i>
<i></i>
<i></i>
</details>

1. Pigeon App version: v0.11.0 Build commit hash: a84b3dc384fd26136fd4f1abb24468d7a27f653d
2. Paloma version: v0.11.4

Error: Couldn’t broadcast signatures and process attestation on Paloma. Account Sequence Mismatch Error. Related to issue https://github.com/palomachain/paloma/issues/523 which was similar. Account sequence mismatch errors. However, now no pigeons are able to broadcast the validator set to BNB.

Pigeon config.yaml:
`loop-timeout: 5s
health-check-port: 5757

paloma:
  chain-id: paloma-testnet-12
  call-timeout: 20s
  keyring-dir: ~/.paloma
  keyring-pass-env-name: "PALOMA_KEYRING_PASS"
  keyring-type: os
  signing-key: ${VALIDATOR}
  base-rpc-url: http://localhost:26656
  gas-adjustment: 1.5
  gas-prices: 0.001ugrain
  account-prefix: paloma

evm:
  eth-main:
    chain-id: 1
    base-rpc-url: ${ETH_RPC_URL}
    keyring-pass-env-name: ETH_PASSWORD
    signing-key: ${ETH_SIGNING_KEY}
    keyring-dir: ~/.pigeon/keys/evm/eth-main
    gas-adjustment: 2
    tx-type: 2

  bnb-main:
    chain-id: 56
    base-rpc-url: ${BSC_RPC_URL}
    keyring-pass-env-name: BSC_PASSWORD
    signing-key: ${BSC_SIGNING_KEY}
    keyring-dir: ~/.pigeon/keys/evm/bnb-main
    gas-adjustment: 1.2
    tx-type: 0`

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

All pigeons are failing as no pigeons are broadcasting signatures to the BNB Vyper contract here: https://bscscan.com/address/0x0354f249AA64A494689799D4b861D1C9930eAcB5

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

This was successfully working prior to our migration away from Starport scaffolding here: 
https://github.com/palomachain/paloma/pull/553

Signatures successfully broadcast should be visible here: https://bscscan.com/address/0x0354f249AA64A494689799D4b861D1C9930eAcB5

**Comment by taariq** [comment]
1. It is possible that pigeon is caching the account sequence?
2. [https://github.com/palomachain/pigeon/blob/ddca5d2d35c3dc303816eaf532b01edc4af89291/chain/paloma/client.go](https://github.com/palomachain/pigeon/blob/ddca5d2d35c3dc303816eaf532b01edc4af89291/chain/paloma/client.go) defines how signatures are broadcast on Pigeon. 
3. Pigeon uses account sequence from Cosmos third-party proto here 
4. [https://github.com/palomachain/pigeon/tree/master/third_party_proto/proto/cosmos/tx](https://github.com/palomachain/pigeon/tree/master/third_party_proto/proto/cosmos/tx)

**Comment by verabehr** [comment]
seems to be related to this https://github.com/palomachain/paloma/issues/625
