### ISSUE TITLE
Connect Nest to Paloma Swap

### ISSUE THREAD

**Issue by joycehermosilla** [palomachain/paloma#578]
As a user of Paloma, I want to be able to Swap between tokens in the Paloma chain.

For that, I need to be able to connect to the Paloma Chain through Paloma Nest Wallet.
<img width="321" alt="Captura de Pantalla 2022-11-21 a las 13 07 22" src="https://user-images.githubusercontent.com/22323189/203049654-1692b664-8d09-4786-8943-ec881ef536f8.png">
https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=3768%3A484&t=vZcjZ27WKzzB1VNF-4

- [ ] If the user has already installed the Paloma Nest Chrome Extension, the pop-up of the extension should open with the authorization to connect Nest with Paloma Swap.

- [ ] In the case that the user has more than 1 wallet address on his/her account, we will show this view: 
https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=4004%3A1265&t=vZcjZ27WKzzB1VNF-4
The user needs to select the addresses wants to connect to Paloma swap:
<img width="332" alt="Captura de Pantalla 2022-11-21 a las 13 05 41" src="https://user-images.githubusercontent.com/22323189/203049184-090f7f72-465c-4dca-900a-dd896790fb96.png">

After confirming which accounts would be connected we will show this view: 
![Uploading Captura de Pantalla 2022-11-21 a las 13.07.04.png…]()

- [ ] If the user approves the connection. The wallet address will appear connected on the Paloma Swap website view.
https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=3966%3A3343&t=vZcjZ27WKzzB1VNF-4
<img width="635" alt="Captura de Pantalla 2022-11-21 a las 13 08 08" src="https://user-images.githubusercontent.com/22323189/203049865-92ec8a43-5ca8-47ba-9a9c-27d1a8a337fd.png">

- [ ] If the user cancel the connection, will be redirected to the main view of Paloma Swap.

- [ ] If the user doesn’t have installed the Chrome Extension a pop up should appear on the screen with the download button that will redirect to the Chrome Store. https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=4004%3A1561&t=vZcjZ27WKzzB1VNF-4
<img width="539" alt="Captura de Pantalla 2022-11-21 a las 13 13 39" src="https://user-images.githubusercontent.com/22323189/203051409-601ddd90-2971-4392-9374-34d7a44d6ec6.png">

**Comment by verabehr** [comment]
complete
