### ISSUE TITLE
Paloma.py: Create a pool on PalomaSwap with two cw20 tokens

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#581]
# Background
https://www.notion.so/volumefi/EPIC-12-10-Paloma-token-and-pool-creation-Python-wrapper-c33f995434d24d188a9a581d1f2a080d#3a683607e5c042bb93cf49d758c7dc17

# Done when
- [ ] a list of items, when checked, this ticket should be considered to be finished
- [ ] Paloma's Python SDK (https://github.com/palomachain/paloma.py) can be used to create a contract for a pool with two Paloma cw20 tokens (e.g. GRAIN<>FIT)
- [ ] Testing is complete
    - [ ] test deploying the contract
    - [ ] test creating a pool
    - [ ] test swap(), deposit() and withdraw() functions

**Comment by fieldtheory123** [comment]
cw20 token instantiate error:

code:

`import asyncio
from pathlib import Path

#import uvloop
from terra_proto.cosmwasm.wasm.v1 import AccessType
from paloma_sdk.client.lcd import AsyncLCDClient
from paloma_sdk.client.lcd.api.tx import CreateTxOptions
from paloma_sdk.core.wasm import MsgInstantiateContract, MsgStoreCode
from paloma_sdk.key.mnemonic import MnemonicKey
from paloma_sdk.core.wasm.data import AccessConfig
from paloma_sdk.util.contract import get_code_id, get_contract_address, read_file_as_b64
paloma = AsyncLCDClient(url="https://lcd.testnet.palomaswap.com/", chain_id="paloma-testnet-13")
paloma.gas_prices = "1ugrain"

acc = MnemonicKey(
    mnemonic="rotice oak worry limit wrap speak medal online prefer cluster roof addict wrist behave treat actual wasp year salad speed social layer crew genius"
)

acc2 = MnemonicKey(
    mnemonic="index light average senior silent limit usual local involve delay update rack cause inmate wall render magnet common feature laundry exact casual resource hundred"
)
test1 = paloma.wallet(acc)
test2 = paloma.wallet(acc2)

code_id = 49
print(f"code_id:{code_id}")

result = await paloma.cw20.instantiate(
    test1, code_id, "CW20 Token", "CW20", 9, 1_000_000_000_000_000, gas_limit=100000, amount="100000ugrain"
)
print(result)
contract_address = get_contract_address(result)

await paloma.cw20.transfer(
    test1, contract_address, test2.key.acc_address, 1_000_000_000
)

await paloma.session.close()
`

error log:

code_id:49
https://lcd.testnet.palomaswap.com/cosmos/auth/v1beta1/accounts/paloma1np4j94fwtka30gux8cqzgg36glvy0je2knq4uz
BlockTxBroadcastResult(height=0, txhash='75A1638ED073EA613F7EC96493C02713464143B373E68EA97A481E092AA9C1E2', raw_log='invalid coins', gas_wanted=0, gas_used=6666, logs=None, code=10, codespace='sdk', info=None, data=None, timestamp=None)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-9751ce291ff7> in <module>
     19 )
     20 print(result)
---> 21 contract_address = get_contract_address(result)
     22 
     23 await paloma.cw20.transfer(

~\Anaconda3\lib\site-packages\paloma_sdk\util\contract.py in get_contract_address(tx_result, msg_index)
     68         return AccAddress(contract_address)
     69     else:
---> 70         raise ValueError("could not parse code id -- tx logs are empty.")
     71 
     72 

ValueError: could not parse code id -- tx logs are empty.

**Comment by taariq** [comment]
@rootedbox Will you review this and confirm that we have a working SDK?

**Comment by taariq** [comment]
@wc117 & @webelf101: what's the status on this ticket?

**Comment by verabehr** [comment]
moved to Volume
