### ISSUE TITLE
Add more logs to Paloma

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#588]
Please add more logs to 
- https://github.com/palomachain/paloma/blob/a2651cd8cbb69e644c8026b2723206bd11cde318/x/evm/types/turnstone_abi.go#L134
- https://github.com/palomachain/paloma/blob/master/x/evm/keeper/keeper.go#L179

If possible add the snapshot id to these two lines as well 
- https://github.com/palomachain/paloma/blob/24d367b1c7379dee75a4f966ea260352b8319362/x/valset/keeper/keeper.go#L200 - https://github.com/palomachain/paloma/blob/24d367b1c7379dee75a4f966ea260352b8319362/x/valset/keeper/keeper.go#L179

Please rename this log line (I think adding (trigger snapshot) would work), so we can distinguish it from the other log line with the same description (same file L368)
https://github.com/palomachain/paloma/blob/24d367b1c7379dee75a4f966ea260352b8319362/x/valset/keeper/keeper.go#L186

**Comment by taariq** [comment]
This is very helpful. Let's make it happen @webelf101
