### ISSUE TITLE
Uploading a contract via the lcd fails at a relatively small size

### ISSUE THREAD

**Issue by measure-fi** [palomachain/paloma#594]
# What is happening?

The palomadex deploy script (sorry I don't have a minimization for this yet) uploads two contracts that are ~500+kB. When doing so they hit an error

```
RPC error -32600 - Invalid Request: error reading request body: http: request body too large
```

which appears to originate here https://github.com/tendermint/tendermint/blob/816c6bac00c63a421a1bdaeccbc081c5346cb0d8/rpc/jsonrpc/server/http_json_handler.go#L24-L26

That _should_ be fixable via the `app.toml` setting

```
# RPCMaxBodyBytes defines the Tendermint maximum response body (in bytes).
rpc-max-body-bytes = 1000000
```

but we have already increased this to 10000000 and are hitting the same error.

**Comment by taariq** [comment]
@measure-fi do we need to close this as no longer an issue?

**Comment by taariq** [comment]
Closing as no fix.

**Comment by verabehr** [comment]
moved to Volume
