### ISSUE TITLE
bug: p2p module - Ignoring inbound connection error

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#607]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

```sh
MESSAGE.err:duplicate ID<95efdc368307c56fcd2c0398f82feeb2d5bb1e48>
MESSAGE.id:95efdc368307c56fcd2c0398f82feeb2d5bb1e48
MESSAGE.level:info
MESSAGE.message:Ignoring inbound connection: error while adding peer
MESSAGE.module:p2p
```
- This occurred multiple times on the private testnet with three validator nodes. 
- they way the network is started is always the same - start on node 1, then start node 2 and 3, both using node 1 as persistent peer
- this occurred when using genesis with three validators (https://github.com/palomachain/private-testnet/blob/vera/multi-validator-genesis/turtle-dove-net/genesis.json) as well as when using genesis with only one validator (https://github.com/palomachain/private-testnet/blob/main/turtle-dove-net/genesis.json)
- 
# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

Paloma version:
--> latest tag (11.4) as well build directly from master with latest code
pigeon:
--> built directly from master with latest code

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

{WRITE YOUR ANSWER HERE}

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

{WRITE YOUR ANSWER HERE}

**Comment by alexanderbez** [comment]
Operators see this error literally all the time from Tendermint, so many things as to what the peering issue can be, but it's almost never software related.

**Comment by verabehr** [comment]
ok, closing this.
