### ISSUE TITLE
bug: consensus module - failed attempting to add vote

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#608]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

On the private testnet with 3 validator nodes, the following error shows
```sh
MESSAGE.err:vote.ValidatorAddress (F79D761B6748E2E374BBB5AA2245433AA0717CA4) does not match address (C75A7B14D65BAAF9E934F69E39D40B1C718FD45E) for vote.ValidatorIndex (0)
Ensure the genesis file is correct across all validators: invalid validator address
MESSAGE.level:info
MESSAGE.message:failed attempting to add vote
MESSAGE.module:consensus
```

- both addresses are valid and belong to one of the 3 validators in the network
- they way the network is started is always the same - start on node 1, then start node 2 and 3, both using node 1 as persistent peer
- during the multiple attempts, I've seen different combinations of addresses in the error message (always valid addresses)
- the very first time, we've seen this error was when having all three validators in the genesis file. (prior to that testing had been done with starting with one validator and creating the other validators after the chain started up)
- this seemed similar to this issue https://github.com/tendermint/tendermint/issues/4006, however, this issue also occurs when none of the three nodes stop.
- this may potentially be related to this issue: https://github.com/palomachain/paloma/issues/607
- genesis file used: https://github.com/palomachain/private-testnet/blob/vera/multi-validator-genesis/turtle-dove-net/genesis.json

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

Paloma version:
--> latest tag (11.4) as well build directly from master with latest code
pigeon:
--> built directly from master with latest code

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

{WRITE YOUR ANSWER HERE}

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

{WRITE YOUR ANSWER HERE}

**Comment by alexanderbez** [comment]
I really don't have a clue as to what's happening here. What I can give is some thoughts:

- The error comes from [`addVote`](https://github.com/tendermint/tendermint/blob/v0.34.24/types/vote_set.go#L156) in Tendermint
- Looking at `addVote`, it seems the error message is a misnomer, i.e. it doesn't seem it has anything to do with genesis. It seems like this error is triggered when the signer is not the expected signer (see the godocs).
- This leads me to believe that somehow validator's are signing with keys that they're sharing or something...idk, it's not very clear to me. I haven't seen this before. 

## Suggestions

Maybe try this with just 2 validators and ensure they're completely isolated, perhaps do this locally (no cloud) and see what happens. But it smells like either an infra/ops problem or somehow you're updating the tendermint validator set during `EndBlock` incorrectly s.t.

I also suggest looking at the valset updates given to Tendermint in the past 2 heights prior to the error and see if anything looks strange or unexpected. Maybe it has a corrupted valset.

**Comment by verabehr** [comment]
Thank you @alexanderbez. I've removed the .paloma directory on all 3 nodes and initialized again from scratch which solved the issue. We were working fine before yesterday, so I think that either during the many resets and restarts of the network or when moving from one validator in genesis to three, something got corrupted. Closing this.
