### ISSUE TITLE
BUG: Ledger support not added with Ledger support in Makefile

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#612]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Receiving error when trying to use LEGER flag: 
```Error: failed to generate ledger key: failed to retrieve device: ledger nano S: support for ledger devices is not available in this executable```

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

Master.

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

run command `./palomad keys add ledger1  --ledger` and see error

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

1. Ledger is enabled in Makefile and go.mod. Not sure why support not successful

**Comment by taariq** [comment]
@alexanderbez asking for a peek on this one as well.

**Comment by alexanderbez** [comment]
This happens only under TWO conditions:

1. You're cross-compiling. I.e. you've build for all operating systems on say, e.g. a macOS. Ledger requires cgo IIRC and thus cross-compilation does not work. If you're using a cross-compiled binary (e.g. from you CI build pipeline) then this will not work with Ledger. **You must pull the code and build/install from source**.
2. If you're building from source and you still get this error, then that means you're not building with the correct tags/build args. Ensure `ledger` is set in the build tags. If you've based the build process off of Gaia or nearly any other major network's Makefile, this should already be there. Please double check.

**Comment by alexanderbez** [comment]
Just checked the Makefile in this repo -- LGTM

So my question is, how was the binary you used/tested built?

**Comment by taariq** [comment]
using source I ran `LEDGER_ENABLED=true go build ./cmd/palomad` but I'm thinking maybe this was not correct?

**Comment by taariq** [comment]
Okay, used the command `LEDGER_ENABLED=true make install` under paloma directory and was able to get Ledger working. I'm assuming cross-compile on MacOS DID work?

**Comment by taariq** [comment]
Okay. Looks this is was built off Gaia. Okay. Closing. Clarified.
