### ISSUE TITLE
CodeQL Hangs taking hours requiring manual stops on Github CI. 

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#621]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

CodeQL Hangs taking hours requiring manual stops on Github CI. 

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

All branches.

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

All PRs are stuck with CodeQL Hangs taking hours and requiring stops. 

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

CodeQL runs within reasonable time frame or exits.

**Comment by measure-fi** [comment]
Disabled for now https://github.com/palomachain/paloma/commit/b357dea
