### ISSUE TITLE
bug: pigeon doesn't report external account information after external chain is added

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#622]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

After the proposals for deploying compass and supporting eth-main have passed, paloma does not receive the evm account information from the validator pigeons, even though there is a worthy snapshot at every 50 blocks. Each snapshot generated has no external account info. 

_Note: There are no errors, the update just doesn't seem to happen/get triggered. When it does get updated this is the pigeon log that one can observe_ 
```
MESSAGE.acc-address:0x6e95DB0BE5B442a45e23540bE059A34128e55304
MESSAGE.chain-reference-id:eth-main
MESSAGE.chain-type:evm
MESSAGE.level:info
MESSAGE.msg:sending account info to paloma
```

Eventually, this log https://github.com/palomachain/paloma/blob/master/x/paloma/keeper/keeper.go#L71 is observed and all pigeons (except one as not all validators can be in jail) are jailed with error `not supporting these external chains: [evm, eth-main]`. 

Unjailing the validators and restarting pigeon without any updates to the pigeon config or evm balances solves the issue. 

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

Paloma: latest master as well as tag 11.4
Pigeon: latest master as well as tag 0.11.0

Pigeon logs: https://drive.google.com/file/d/1ceQevHFsC50W9ZyUdOGfsIX0_zPknZ2a/view?usp=share_link
Paloma logs: https://drive.google.com/file/d/1uIsdAsN4c6FqrPx771znzVaZUL0IXN3L/view?usp=share_link
# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

- start the private three node testnet
- submit proposals for 1) deploying compass and 2) adding eth-main as chain
- start generating valset updates by delegating and undelegating stake to one of the validators.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Pigeons should not get jailed when they fulfill all requirements for the external chains.

**Comment by taariq** [comment]
External account information must be stored by the keeper so we now have to chase why that information is not being set.

**Comment by verabehr** [comment]
I updated my description to be clearer. It's not a storing issue, the information is not being sent.

**Comment by alexanderbez** [comment]
> I updated my description to be clearer. It's not a storing issue, the information is not being sent.

When you say, "not being sent", do you mean that the Pigeon processes are responsible for sending these updates? How, when, and by whome are chain infos/accounts _supposed_ to be sent?

**Comment by verabehr** [comment]
This is part of the relayer loop here https://github.com/palomachain/pigeon/blob/master/relayer/start.go#L63. As a validator, I expect this to be sent in every loop. cc @taariq

**Comment by alexanderbez** [comment]
Gotch, so a few questions:

1. Are you seeing `MsgAddExternalChainInfoForValidator` messages being sent to the chain? If so, are they erroring? 
2. Are you seeing any errors in the logs from the Pigeon's `Start` process?
3. Perhaps add a bunch of debug logs to `updateExternalChainInfos`, maybe `chainInfos` is empty.

**Comment by verabehr** [comment]
@alexanderbez - Looked further into this with @taariq @webelf101. The problem appears to be that this https://github.com/palomachain/pigeon/blob/b596fad2d0d4336534a0e40cdbcb7f91b9bbab80/relayer/start.go#L35-L40 is only called when pigeon starts. We do see it successfully being called when pigeon is restarted. 

Suggestion is to copy this part into the process, so that it is called as part of the relayer loop and not only on start.

**Comment by alexanderbez** [comment]
That makes sense to me. I would sync with the author of the code if possible? I wonder if this was simply overlooked or done intentionally. But yeah, moving it inside the loop makes sense.

**Comment by alexanderbez** [comment]
@verabehr the code you referenced is much different than pigeon `master`. In the `master` branch, you already execute `updateExternalChainInfos ` in a loop: https://github.com/palomachain/pigeon/blob/master/relayer/start.go#LL52C3-L71.

However, there is a return there...not sure why. Consider removing the return?

**Comment by alexanderbez** [comment]
https://github.com/palomachain/pigeon/pull/83

**Comment by verabehr** [comment]
odd, not sure how I landed on this non-master version. In any event, will
test PR 83. Thank you
