### ISSUE TITLE
Wallchain

### ISSUE THREAD

**Issue by wdev733** [palomachain/paloma#631]
1. Library for Message sender
- [ ] Build as a npm module and to be published
- [x] Check the paloma nest wallet is installed on the browser
- [x] Connect wallet
- [ ] Confirm transaction

2. Paloma Nest
- [x] Add message receiver in `Background.js` and `Content.js`
- [ ] Run transactions via `palomajs`
- [ ] Add views for `Connect wallet` and `Confirm transaction`

3. Paloma Swap UI
- [x] Add Connect wallet view
- [ ] Implement connect to `Paloma chain`
- [x] Implement wallchain

**Comment by taariq** [comment]
Thanks @wdev733. This clarifies the runway for landing the PalomaSwap UI requirements. Where does security review need to be implemented?

**Comment by wdev733** [comment]
@taariq It should be implemented on the `library` and `paloma nest wallet`

**Comment by verabehr** [comment]
@wdev733 let's move the `Implement wallchain` task into a separate ticket
