### ISSUE TITLE
Add node_reset code to Paloma nodes

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#633]
# Background

_Describe the problem that we are trying to solve with this feature._
_If a path to a solution is known, feel free to write it down, but have an open mind_

The team needs to be aware when a critical node is going down and all critical nodes should restart when 
# Done when
 
- [x] https://github.com/kallisto-finance/node_reset is added to Palomachain org in github
- [x] is installed on the LCD server, snapshot servers, faucet servers and the mainnet validator server, so that nodes auto-restart when the blocks don't progress
- [x] a sentry alert gets fired when a restart happens or fails

**Comment by rootedbox** [comment]
Code is complete but not on all servers yet.. will close when that is done.
