### ISSUE TITLE
bug: faucet is not working

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#637]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

The faucet returns an error when users try to get tokens 
<img width="531" alt="Screen Shot 2023-01-09 at 2 32 17 PM" src="https://user-images.githubusercontent.com/19958639/211413473-8234ce5c-8f2e-4a4f-b06c-01d5f7909db8.png">

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Go to faucet.palomaswap.com and request grain with a valid address.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

no errors, user receives grain

**Comment by rootedbox** [comment]
the faucet machine was connected to bird lady via ip.. I have now switched it to connect to testnet.palomaswap.com directly
