### ISSUE TITLE
bug: Addresses from Python SDK and from Palomad and Paloma Nest don't match.

### ISSUE THREAD

**Issue by wc117** [palomachain/paloma#638]
# How to reproduce?
<details>  <summary>https://github.com/palomachain/paloma.py/blob/ac7c6b0ef72264299dda1b72f271c3bbeb226224/integration_tests/wallet_address_issue.py#L15<br>This returns `paloma1x46rqay4d3cssq8gxxvqz8xt6nwlz4td5wpjhf` and the wallet works as the address. But when I add the same mnemonic to Paloma Nest, the wallet works as `paloma1cyyzpxplxdzkeea7kwsydadg87357qna8rgwj8`. I confirmed Paloma Nest address is the same as the address when I add the same mnemonic to `palomad`. It seems the Python SDK wallet forked from terra Python SDK is not compatible with Paloma.</summary>
</details>

**Comment by taariq** [comment]
Confirmed. This bug is due to Paloma.Py using Terra COINTYPE = 330 instead of Paloma.js COINTYPE for Paloma = 118. @rootedbox will you please refactor memonic.py to confirm to memonic.ts on the Paloma.js library so that we have consistency and proper key derivation in the Python SDK?
