### ISSUE TITLE
Extract deterministic message serialisation from a runner into a separate repository (utils)

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#64]
## Background

We need to have a same way of serializing messages for the chain and for the runner. Easiest solution is to make the serialization in a separate repository and have both runner and chain use the same repository. Sadly, for smart contract we will need to do this separately as it's written in Rust, but we can make it easier for Go.

## Done when

- [x] we have a new repository called utils (done https://github.com/VolumeFi/utils)
- [x] there is a new package in the repo called signing (or something similar)
- [x] the code which does signing is taken from the runner and copied into the signing package
- [x] runner is using the new package for message signing
- [ ] either (because chain first needs to have validator sets, thus it can't use it just yet)
  - [ ] we do the same thing for chain right now (depends on when we do this ticket)
  - [x] we create a ticket to have chain use the same repository

**Comment by taariq** [comment]
@Vizualni are we using this utils repo any more? Just checking.

**Comment by Vizualni** [comment]
@taariq we are using it both in paloma and sparrow
