### ISSUE TITLE
No binaries generated on the v0.11.5 tag release in Github

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#645]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

No binaries generated on the v0.11.5 tag release in Github

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

v0.11.5

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

No binaries generated on the v0.11.5 tag release in Github at tags

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

We want the binaries generated with correct versions under the tag.

**Comment by alexanderbez** [comment]
If you made a release by cutting a tag off of `release/v0.11.x` then you did the right thing. If no release was made, then you need to look at the config: https://github.com/palomachain/paloma/blob/master/.github/workflows/release.yml

**Comment by alexanderbez** [comment]
NVM, it looks like the release action targets ALL tags, which is fine I guess.

Take a look at the release job -> https://github.com/palomachain/paloma/actions/runs/3888434874/jobs/6635748787

It failed.

**Comment by taariq** [comment]
Binaries are created. All good to go.
