### ISSUE TITLE
Enable backups for hardware validator

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#649]
# Background

_Describe the problem that we are trying to solve with this feature._
_If a path to a solution is known, feel free to write it down, but have an open mind_

For mainnet, we want backups enabled on the Volume validator machine, so that we can easily restore the node if it gets into a bad state.
# Done when

- [ ] .paloma directory is backed up daily

**Comment by verabehr** [comment]
@taariq will you please confirm that this is what we want for this? I don't think we want the .pigeon folder as it contains the key.

**Comment by taariq** [comment]
Let's exclude the .pigeon folder from backups. Correct.
