### ISSUE TITLE
BUG: Testnet faucet returns 404 Error. No Testnet coins available

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#650]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

https://faucet.palomaswap.com/ fails to send coins.

webpackHotDevClient.js:60 WebSocket connection to 'wss://faucet.palomaswap.com/sockjs-node' failed: Error during WebSocket handshake: Unexpected response code: 404
./node_modules/react-dev-utils/webpackHotDevClient.js @ webpackHotDevClient.js:60

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

v0.11.5

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

https://faucet.palomaswap.com/

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Faucet coins must work.

**Comment by verabehr** [comment]
I'm not even able to see the page. I get this error: 
```
faucet.palomaswap.com/:15 
 GET https://faucet.palomaswap.com/static/js/vendors~main.chunk.js net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)
32by32.png:1 
 GET https://s3.ap-northeast-2.amazonaws.com/terra.money.home/static/images/favicon/32by32.png 403 (Forbidden)```

<img width="1414" alt="Screen Shot 2023-01-12 at 12 16 54 PM" src="https://user-images.githubusercontent.com/19958639/212135893-ab38796a-4cea-4fef-9377-21a48c8a38dd.png">

**Comment by taariq** [comment]
Closing as browser specific. Let's re-open if still an issue. Not working on Chromium.
