### ISSUE TITLE
Add Logger to track which process is calling GetCurrentSnapshot for issue #654

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#658]
# Background

From https://github.com/palomachain/paloma/issues/654#issuecomment-1384613282.

We want to add DEBUG logs around the following calls:
- `CheckExternalBalancesForChain`
https://github.com/palomachain/paloma/blob/master/x/evm/keeper/keeper.go#L736

- `TryDeployingLastSmartContractToAllChains` https://github.com/palomachain/paloma/blob/master/x/evm/keeper/keeper.go#L474

- `SaveNewSmartContract`
https://github.com/palomachain/paloma/blob/master/x/evm/keeper/keeper.go#L286

- `attestValidatorBalances`
https://github.com/palomachain/paloma/blob/master/x/evm/keeper/keeper.go#L62

- `attestRouter`
- https://github.com/palomachain/paloma/blob/master/x/evm/keeper/keeper.go#L55

1. We need to log what is calling these functions that then add information to the keeper.
2. When we have logs, we'll cut a new release for validators to upgrade so we can track DEBUG logs

# Done when
- [ ] logs are added

**Comment by webelf101** [comment]
TryDeployingLastSmartContractToAllChains
SaveNewSmartContract
These two functions already have Info() logs. I think we can ignore the two functions. @taariq

**Comment by taariq** [comment]
Got it. Let's ignore those then! Thank you!
