### ISSUE TITLE
bug: Invalid app version when building from source

### ISSUE THREAD

**Issue by kj89** [palomachain/paloma#668]
Description:
When building binaries from source app has invalid version.

How to reproduce:
```
git clone https://github.com/palomachain/paloma.git
cd paloma
git checkout v0.11.6
make build
./build/palomad version
```

Output:
```
name: paloma
server_name: palomad
version: HEAD-6a6c9280f76e0c5a510d80aebcfef4e94b7043c0
commit: 6a6c9280f76e0c5a510d80aebcfef4e94b7043c0
```

After starting palomad service we see an error in the logs:
```
12:06AM INF running app args=["start"] module=cosmovisor path=/home/paloma-testnet/.paloma/cosmovisor/genesis/bin/palomad
panic: invalid app version 'HEAD-6a6c9280f76e0c5a510d80aebcfef4e94b7043c0'
```

What is expected:
After building binaries we expect to get correct app version and no errors when running node service

**Comment by mahofmahof** [comment]
i have changed the 
VERSION := $(shell git describe --exact-match 2>/dev/null) to  
VERSION := v0.11.6 at the https://github.com/palomachain/paloma/blob/master/Makefile 
and after that built from the source. 
palomad binary worked without any problem on a raspberry pi.
It is a temporary solution but will be easier to debug with this.

**Comment by sergiomateiko** [comment]
my commit

version: v0.11.6
commit: 6a6c9280f76e0c5a510d80aebcfef4e94b7043c0
