### ISSUE TITLE
Migrate from Dynamic to static libwasm for Paloma wasm library

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#669]
# Background
palomad binaries that are compiled with dynamic cosmwasm lib. That is fine as long as people have the correct libwasmvm_ files on their box already. But this won't work if you have cosmwasm version upgrades (as in the wasmd v0.31.0 release for example). For an automated chain upgrade (via cosmosvisor for example) a static compiled binary makes more sense as it includes the cosmwasm lib already. A libwasmvm_ missmatch can be consensus breaking so we fail on startup already.

# Done when
Add Static compile to Makefile as per here:
https://github.com/osmosis-labs/osmosis/blob/main/Makefile#L107-L111

**Comment by verabehr** [comment]
@taariq should we migrate this to Volume?
