### ISSUE TITLE
bug: Paloma Mest Wallet add New wallet

### ISSUE THREAD

**Issue by KyErgus** [palomachain/paloma#678]
When adding a new wallet, the wallet is installed without Mnemonic approval. e.g; After saving the mnemonic, it asks you to enter the 3rd and 6th word. But when clicked without entering those words and without activating the confirmation bot, the bot works and the wallet is installed. In addition; Unable to switch between wallets and a white screen is given.

**Comment by verabehr** [comment]
fixed in version 1.3.1beta
