### ISSUE TITLE
add https://paloma.api.explorers.guru/api/  to our servers

### ISSUE THREAD

**Issue by rootedbox** [palomachain/paloma#680]
- [x] add/create FCD API endpoint testnet
- [x] add  FCD API endpoint mainnet
- [x] switch out API call in Paloma nest https://paloma.api.explorers.guru/api/v1/accounts/ and move it from the [wallet code](https://github.com/palomachain/paloma-nest/blob/master/src/common/config.js#L8) into  the [nest-service API](https://github.com/palomachain/paloma-nest-service/blob/main/config.example.json_)
- [x] move the explorer urls (https://github.com/palomachain/paloma-nest/blob/master/src/common/config.js#L5-L6) to the nest service config

explorer urls
TESTNET:
base_url = https://explorer.ppnv.space/paloma-testnet/
transaction endpoint = `${base_url}tx/

MAINNET
base_url = https://explorer.ppnv.space/paloma/
transaction endpoint = `${base_url}tx/

**Comment by wdev733** [comment]
@verabehr @rootedbox 
FYI, the api for fetching transaction histories is `{baseUrl}/api/v1/accounts/{address}/txs

Please make sure the txHistory api works on the `nest-service`

**Comment by verabehr** [comment]
@rootedbox FYI, the endpoint base url slightly changed. Updated here in the ticket
