### ISSUE TITLE
bug: Mixpanel missing data for BNB

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#691]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Mixpanel doesn't show any change in BNB messages sent, even though we have regular transactions here https://bscscan.com/address/0x370A1a665328170eFA6a0bb51f948108C23528BA

https://mixpanel.com/project/2744781/view/3280621/app/boards#id=3475733&editor-card-id=%22report-33268583%22 is just flat 

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

we should see the correct data

**Comment by rootedbox** [comment]
we never updated the config for this new address.. we were looking at 0x460898222468A1d375A8a2c8E92958e9ad006D7B I have updated the config.. and I also fixed a bug that could cause a exception in certain issues..
