### ISSUE TITLE
Clean up alerts

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#694]
# Background

_Describe the problem that we are trying to solve with this feature._
_If a path to a solution is known, feel free to write it down, but have an open mind_

# Done when

- [ ] Sentry alerts go to the discord alert channel as well
- [ ] description for errors are self-explanatory - e.g. "node stuck" alert needs to state that palomad was restarted and no further action is required
- [ ] Kallisto.finance sentry alerts are turned off

**Comment by rootedbox** [comment]
this can be closed

**Comment by verabehr** [comment]
We don't yet have Sentry alerts go into discord. Reopening this one
