### ISSUE TITLE
Set up refund script for Polygon Mainnet

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#697]
Need to set up refund script for POlygon mainnet as it goes live on 2/2 https://paloma.explorers.guru/proposal/4

**Comment by verabehr** [comment]
@webelf101 @fieldtheory123 what is left on this? Do you need any help from Jason to have this run daily?

**Comment by fieldtheory123** [comment]
@verabehr I think @webelf101 is finalizing his work of cleaning functions.py and run.py, which will be used for the polygon scrupts. Once he's done the polygon script will be complete and we can ask Jason to start a crobjob.
