### ISSUE TITLE
Updates to Paloma genesis

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#698]
# Background

Updates for Paloma mainnet genesis

# Done when

- [ ] Slashing updated as follows: 
```
"slashing": {
      "params": {
        "signed_blocks_window": "10000",
        "min_signed_per_window": "0.500000000000000000",
        "downtime_jail_duration": "600s",
        "slash_fraction_double_sign": "0.050000000000000000",
        "slash_fraction_downtime": "0.010000000000000000"
```

- [x] missing validators from community vote are added as genesis accounts
- [x] 1 validator who was not in initial community vote is reconciled
- [x] dancing banana venture genesis amount is updated
- [x] Paloma foundation1 genesis amount is updated

**Comment by verabehr** [comment]
first task moved to new ticket
