### ISSUE TITLE
Reduce NewRelic usage

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#701]
# Background

_Describe the problem that we are trying to solve with this feature._
_If a path to a solution is known, feel free to write it down, but have an open mind_

Newrlic bill got out of hand

# Done when

- [x] turn off newrelic on main-devnet-1 , main-devnet-2, main-devnet-3

- [ ] Confirm that we have the following setup now: 
   - [x] birdpoop2 node has newrelic, so we can monitor the public testnet
   - [x] private testnet nodes have it (no change needed), but only when actively testing as testnet is not running otherwise
   - [x] mainnet validator node should have it, so we can monitor mainnet
   - [x] no other nodes have it

**Comment by measure-fi** [comment]
I know we added a number of debug logs at the info level, is there a chance any of those stayed in?

**Comment by verabehr** [comment]
no we removed them, but we are running some instances in debug mode to debug

**Comment by rootedbox** [comment]
There can be a delay before they are removed from the panel.. I do not want to close this until they are removed from the panel.

**Comment by rootedbox** [comment]
This can be closed.
