### ISSUE TITLE
Run setup script and collect gentx

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#703]
- [x] Run latest setup script https://github.com/palomachain/mainnet/blob/master/cumulet/scripts/setup-cumulet-mainnet.sh
- [x] Collect all gentxs in this folder https://github.com/palomachain/mainnet/tree/master/cumulet/gentxs     
```
palomad collect-gentxs --gentx-dir [path to local directory]
```

- [x] open a PR on https://github.com/palomachain/mainnet/pulls from the Volumefi fork (use a new branch, not master)

**Comment by taariq** [comment]
@rootedbox this is the next step.
