### ISSUE TITLE
bug: my validator is missing in genesis.json

### ISSUE THREAD

**Issue by VitaValeriya** [palomachain/paloma#705]
In genesis.json for mainnet my validator is missing. 
https://github.com/palomachain/mainnet/blob/master/cumulet/genesis.json

Moniker VitaValeriya, gentx merged 
https://github.com/palomachain/mainnet/pull/104

**Comment by taariq** [comment]
https://github.com/palomachain/mainnet/blob/master/cumulet/genesis.json#L323 from https://github.com/palomachain/mainnet/blob/master/cumulet/gentxs/VitaValeriya%20GenTx

**Comment by VitaValeriya** [comment]
Hello,@taariq!
in the genesis file, my wallet is listed only in 2 places, but it should be in 3. My validator is not in the genesis file. Compare with the Firstcome wallet for example.
![Безымянный](https://user-images.githubusercontent.com/103098993/216802770-812d39b7-0014-4f95-9198-d4ae93f790e2.png)

In the part of the genesis file, where information about validators is indicated, my wallet is missing.

![Безымянный1](https://user-images.githubusercontent.com/103098993/216802787-6a380cdb-67a8-49c3-a01f-72ae0e582387.png)

**Comment by VitaValeriya** [comment]
also in genesis like my validator missing the following validators:
ERN VENTURES
MCB
catone
paloma.acloud.pp.ua
salomonval

**Comment by verabehr** [comment]
Noting that all of these had gentx submissions that either have a space in the file name or don't have `.json` as file extension. Seems like the collect-gentxs command ignores those. We'll have to update the file name and run again.

**Comment by taariq** [comment]
Closing as user error.
