### ISSUE TITLE
Users can connect unsupported chains to palomaswap

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#709]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

When I connect my metamask, I am not forced to connect on ethereum mainnet and an incorrect balance shows
<img width="549" alt="Screen Shot 2023-02-06 at 1 13 04 PM" src="https://user-images.githubusercontent.com/19958639/217052209-3621247a-72a8-4792-8899-ae684ea1e4ca.png">

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Users should be prompted to switch their network to ethereum mainnet

**Comment by verabehr** [comment]
loom https://www.loom.com/share/84097175229e4da9990da215c8eb8691 (cc @joycehermosilla )

**Comment by taariq** [comment]
Added my comments IN THE LOOM @wdev733

**Comment by verabehr** [comment]
@wdev733 seeing some additional weirdness when trying to connect with eth main https://www.loom.com/share/aabadb7bd5764e088dcaab4fa3fda6fd

**Comment by verabehr** [comment]
moved over to Volume
