### ISSUE TITLE
bug: rpc endpoint list shows incorrect base domain

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#712]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

testnet.palomaswap.com and rpc.palomachain.com don't show the correct host names 
<img width="460" alt="Screen Shot 2023-02-08 at 2 21 06 PM" src="https://user-images.githubusercontent.com/19958639/217630633-3fd0487f-832e-4f39-a681-af171b4afc17.png">

# What is the expected behavior?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

endpoints listed are correct including base domain

**Comment by taariq** [comment]
Fixed.
