### ISSUE TITLE
Paloma Nest Wallet mainnet $GRAIN send confirmation button not working.bug: what is happening

### ISSUE THREAD

**Issue by KyErgus** [palomachain/paloma#714]
# What is happening?

$GRAIN was sent to Paloma Nest Wallet via Paloma Mainnet with Keplr Wallet. However, when sending via Paloma Nest Wallet and Paloma Mainnet; Confirm button does not work. Detailed video link is available here: https://www.dropbox.com/s/ldojpqcqp9gy9ak/VID-20230213-WA0000.mp4?dl=0

- Operating system: MacOs Monterey 12.6
- Internet browser used: Google Chrome is up to date
Version 110.0.5481.77 (Official Build) (x86_64)
- Wallet Version: Paloma Nest(Beta) 1.3.2 Beta

Source Location | Directive | Status
-- | -- | --
popup.bundle.js:9 | script-src | blocked

```
        }
        ,
        67199: module=>{
            "use strict";
            function inquire(moduleName) {
                try {
                    var mod = eval("quire".replace(/^/, "re"))(moduleName);
                    if (mod && (mod.length || Object.keys(mod).length))
                        return mod
                } catch (e) {}
                return null
            }
            module.exports = inquire
        }
```

**Comment by taariq** [comment]
FYI @wdev733 & @verabehr

**Comment by verabehr** [comment]
@wdev733 FYI, I wasn't able to reproduce the issue

**Comment by verabehr** [comment]
update this just happened to me as well, but is intermittent. Seems like it's related to the simulate endpoint 
<img width="1299" alt="Screen Shot 2023-02-14 at 3 51 24 PM" src="https://user-images.githubusercontent.com/19958639/218860689-acf54e35-43af-431e-a14b-302e5cffe608.png">

**Comment by KyErgus** [comment]
I updated my wallet to 1.3.3 and I try again but I guess the problem is not fixed.


![Ekran Resmi 2023-02-17 18 57 26](https://user-images.githubusercontent.com/108483741/219703567-53338e9a-8cb9-42ed-b5bc-2a23b67b3117.png)

**Comment by taariq** [comment]
@KyErgus please update to current wallet and let us know if this still issue. We'll reopen.

**Comment by KyErgus** [comment]
I updated. there is no problem at the moment. token sending is working.
