### ISSUE TITLE
Palomaswap Feedback Feb 15

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#723]
### UI
- [x] The wallet UI doesn't fill out the whole popup window for Nest 
<img width="811" alt="Screen Shot 2023-02-15 at 2 57 20 PM" src="https://user-images.githubusercontent.com/19958639/219147525-fa9906af-2a3c-4328-9447-df2265cafc78.png">

- [x]  Please remove the floating question mark
<img width="431" alt="Screen Shot 2023-02-15 at 3 06 56 PM" src="https://user-images.githubusercontent.com/19958639/219147769-3e18c2a3-3287-4b96-ad87-ff1822b6f03d.png">

- [x] Please update error message copy to "Swap failed. Output token amount is too low. Try adjusting slippage" (cc Yoya - not sure if this is too long?) 
<img width="349" alt="Screen Shot 2023-02-15 at 2 56 53 PM" src="https://user-images.githubusercontent.com/19958639/219152055-6806fb7b-d031-471d-84aa-5ef732cff3f7.png">

### Nest connect issues
- [ ] I can't connect to Palomaswap by importing an existing wallet https://www.loom.com/share/90dcfa4a6365447f99c0d35a120da81c

### Metamask connect issues
- [x] Metamask wallet reconnects when page is refreshed even though I disconnected it https://www.loom.com/share/f1669e5b24c54001888e4a20450055eb

**Comment by joycehermosilla** [comment]
@verabehr @wdev733 Also, when pressing "I don't have a Paloma Wallet" nothing happens. 
<img width="436" alt="Captura de pantalla 2023-02-15 a las 22 10 44" src="https://user-images.githubusercontent.com/22323189/219166788-c6d5b994-9533-4a51-a463-3c292b7e3616.png">

We should show this view:
<img width="515" alt="Captura de pantalla 2023-02-15 a las 22 13 38" src="https://user-images.githubusercontent.com/22323189/219165924-cd0814bb-d300-492e-9612-c7792ef19080.png">

And then when the user presses "Download Nest" should open a new tab to: https://chrome.google.com/webstore/detail/paloma-nestbeta/cjmmdephaciiailjnoikekdebkcbcfmi

**Comment by verabehr** [comment]
I actually left a comment for that in the new designs. Ideally the browser
should detect if you have it or not, so that you see the right call to
action right away.

**Comment by joycehermosilla** [comment]
Yes agree. Adding the change here.  @verabehr @wdev733 

Connect Nest.
<img width="521" alt="Captura de pantalla 2023-02-16 a las 13 18 05" src="https://user-images.githubusercontent.com/22323189/219362646-13a05911-efbb-4aa7-8fa1-fcfc06c3e798.png">

a) If the user has installed the Paloma Nest Chrome Extention, the front end should detect it and open the Wallet.

b) If the user hasn't installed the Paloma Nest Chrome Extention, we should show this view:
<img width="546" alt="Captura de pantalla 2023-02-16 a las 13 19 15" src="https://user-images.githubusercontent.com/22323189/219362879-c60665ac-902f-40b4-899f-7c50845f552d.png">

- So when the user presses the button: Download Nest, we should open the Chrome Store in a new tab. LINK: https://chrome.google.com/webstore/detail/paloma-nestbeta/cjmmdephaciiailjnoikekdebkcbcfmi

**Comment by verabehr** [comment]
@wdev733 I'm still not able to connect paloma nest if I want to import my existing wallet using mnemonic. 
<img width="1422" alt="Screen Shot 2023-02-22 at 1 13 24 PM" src="https://user-images.githubusercontent.com/19958639/220720461-a6ccc7b3-d8f1-4519-9c2e-1736079ce0a5.png">
