### ISSUE TITLE
bug: nest wallet dows not popup arter pressing connect buton

### ISSUE THREAD

**Issue by mahofmahof** [palomachain/paloma#732]
# What is happening?
nest wallet does not pop up when trying to connect to palomaswap.com
at console gives this error

Denying load of chrome-extension://cjmmdephaciiailjnoikekdebkcbcfmi/popup.html. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.

{WRITE YOUR ANSWER HERE}

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

{WRITE YOUR ANSWER HERE}

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

{WRITE YOUR ANSWER HERE}

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

{WRITE YOUR ANSWER HERE}

**Comment by taariq** [comment]
FYI @verabehr

**Comment by wdev733** [comment]
@mahofmahof
- Please make sure your NEST version is 1.3.4
- Refresh your browser and try again

cc @taariq @verabehr
