### ISSUE TITLE
bug: Nest Wallet won't connect to https://www.palomaswap.com/uniswap-v2/

### ISSUE THREAD

**Issue by KyErgus** [palomachain/paloma#733]
# What is happening?
Nest Wallet won't connect to https://www.palomaswap.com/uniswap-v2/. 
When trying to connect; It says download Nest Wallet.

After going to https://www.palomaswap.com/uniswap-v2/ and connecting Ethereum wallet; When we try to start Nest Wallet, it asks us to download it even though Nest Wallet is installed. Even though I uninstalled Nest Wallet from the browser and reinstalled it, the problem was not resolved. Details are shown in the image.

Image abou it:
    https://www.dropbox.com/s/p9prl82wv1ukxoi/IMG-20230223-WA0005.jpg?dl=0
    https://www.dropbox.com/s/26t42ccirl8k1xh/IMG-20230223-WA0006.jpg?dl=0

The Browser console error output:
``` Denying load of chrome-extension://cjmmdephaciiailjnoikekdebkcbcfmi/popup.html. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension. ```
           
 - Operating system: MacOs Monterey 12.6
 - Internet browser used: Google Chrome is up to date Version 110.0.5481.77 (Official Build) (x86_64)
 - Wallet Version: Paloma Nest(Beta) 1.3.3 Beta

**Comment by verabehr** [comment]
This was fixed with version 1.3.4 beta which is now available in the Chrome web store (cc @taariq)

**Comment by taariq** [comment]
https://chrome.google.com/webstore/detail/paloma-nestbeta/cjmmdephaciiailjnoikekdebkcbcfmi
