### ISSUE TITLE
Paloma.js bug claiming grains rpc error: code = Unknown desc = invalid length; unexpected EOF: tx parse error

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#735]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

When attempting to claim GRAINS from Palomaswap, user enters their paloma address in paloma wallet and signs transaction to recover grains. However, user encounters the error
```
{
    "code": 2,
    "message": "rpc error: code = Unknown desc = invalid length; unexpected EOF: tx parse error [cosmos/cosmos-sdk@v0.45.11/x/auth/tx/decoder.go:21] With gas wanted: '0' and gas used: '19998' : unknown request",
    "details": []
}
```
Using Paloma.js: 
https://github.com/palomachain/paloma.js

Also, errors are detected errors in the LCD server logs. 

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

All current versions of Paloma.

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Current PalomaSwap wallet connect fails to claim GRAINs

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Paloma.js signs transaction in Chrome and sends tx to LCD server. No errors and user can claim their grains.

**Comment by taariq** [comment]
Proposed next steps from @rootedbox 

1. Log the claims tx message outputs to the lcd from both node.js and chrome extensions.
2, If the messages are different, work my way backwards to output message logging 
3. If the messages are the same then work way forward to output logs of next steps.

**Comment by rootedbox** [comment]
1. In order to log output messages I'm going to have to build / release a special version of paloma.js that has outputs to console debug information.. such as the output that is going to the lcd.
2.  I now know the message should be different as the error response is coming from the lcd.
