### ISSUE TITLE
Paloma Swap - Select DEX and Chain view

### ISSUE THREAD

**Issue by joycehermosilla** [palomachain/paloma#736]
As a user of Paloma swap I want to be able to access to swap on all the DEXes. That means we will have a long list of DEXEs and Chains to the user to select from.

- [ ] Remove the Side Menu and center the design to the screen. 
<img width="648" alt="Captura de pantalla 2023-02-27 a las 11 25 59" src="https://user-images.githubusercontent.com/22323189/221538834-cad83c88-efd1-4f8d-8160-d6b77f72635f.png">

- [ ] As a user I want to see a view before the swap where the user can select a DEX and Chain where they want to Swap.
https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=5922%3A10897&t=fUwM71mAfd9GUiuq-4
<img width="380" alt="Captura de pantalla 2023-02-27 a las 11 25 18" src="https://user-images.githubusercontent.com/22323189/221538675-3b642e85-84a3-4bf2-9a1b-8b47706f42b3.png">

- [ ] After the user select a DEX and Chain the Connect Wallet button will be enabled:
<img width="356" alt="Captura de pantalla 2023-02-27 a las 11 29 09" src="https://user-images.githubusercontent.com/22323189/221539542-b45fe5d2-48ef-42be-83be-8e847a01ce6e.png">

- [ ] "Connect Wallet"will be redirected to the Connect Wallet flow, where the user will connect their EVM wallet on the selected Chain and the Paloma Nest Wallet.
https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=4818%3A6489&t=fUwM71mAfd9GUiuq-4

- [ ] After finishing the Connect Wallet flow the user will land on the Swap view on the desired Chain and DEX. From the Swap view the user will be able to change the DEX and the Chain as well.

**Comment by verabehr** [comment]
moved to Volume
