### ISSUE TITLE
Mikhail will review all the dependabot PRs on both open and closed PRs

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#745]
# Background

1. Dependabot PRs review to merge both closed and open
2. Upgrade where possible and identify any breaking changes

# Done when
- [ ] Upgrades are merged

**Comment by mszuyev** [comment]
Left a comment: dependabot downgraded CosmosSDK version in all PRs, to the incompatible one, making PRs broken. Let me update everything but CosmosSDK manually.

**Comment by mszuyev** [comment]
Closed related Dependabot PRs, created a manual upgrade https://github.com/palomachain/paloma/pull/747
Unfortunately, upgrading to Cosmos SDK ver 1.46+ will require more effort, due to incompatibility, so will use it of v. 1.45.13 for now.

**Comment by taariq** [comment]
Fixed with #747 and #748
