### ISSUE TITLE
GRPC failure: "message": "codespace sdk code 18: invalid request: failed to load state at height 153

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#800]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

grpc query error on Cosmos SDK v.047.71 upgrade from Cosmos SDK v0.45.13 when running the test script: https://hackmd.io/@aleem/r1N5FILf3

 **"message": "codespace sdk code 18: invalid request: failed to load state at height 153; version does not exist (latest height: 153)",**

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Run grpc query:

`palomad q staking validators` 

or

`curl http://127.0.0.1/cosmos/staking/v1beta1/validators`

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Grpc queries return results.

**Comment by taariq** [comment]
Confirmed all queries fail except `palomad query blocks`

**Comment by 0xmuralik** [comment]
https://github.com/palomachain/paloma/blob/7df1e6a7abe43d775e435c1a7ad98e4acb02a72b/app/upgrades.go#L161
Is this correct?
Cause the cosmos-sdk/x/consensus module still uses the "consensus" store key. Do we have to add it to the added keys?

**Comment by taariq** [comment]
> https://github.com/palomachain/paloma/blob/7df1e6a7abe43d775e435c1a7ad98e4acb02a72b/app/upgrades.go#L161
> 
> Is this correct?
> Cause the cosmos-sdk/x/consensus module still uses the "consensus" store key. Do we have to add it to the added keys?

I'm not sure. Given that we've restarted a fresh network without upgrades, we think the UpgradeHandler is NOT the issue as we are unable to successfully query state without an upgrade. However, to your question, I am not sure it's correct given the premise that the consensus module uses the "consensus" store key.

**Comment by taariq** [comment]
@0xmuralik & @aleem1314 What's next for us here?

**Comment by 0xmuralik** [comment]
> @0xmuralik & @aleem1314 What's next for us here?

I'll get started on https://github.com/palomachain/paloma/issues/795
