### ISSUE TITLE
 expected: paloma-test-15, got: paloma-testnet-15

### ISSUE THREAD

**Issue by alipostaci2001** [palomachain/paloma#838]
after starting the  last update with v1..0.0 testnet , I encounter this problem on paloma-logs :

May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe systemd[1]: Started Paloma Node.
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: I[2023-05-16|06:17:19.720] starting node with ABCI Tendermint in-process module=server
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: I[2023-05-16|06:17:19.822] service start                                module=proxy msg="Starting multiAppConn service" impl=multiAppConn
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: I[2023-05-16|06:17:19.822] service start                                module=abci-client connection=query msg="Starting localClient service" impl=localClient
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: I[2023-05-16|06:17:19.822] service start                                module=abci-client connection=snapshot msg="Starting localClient service" impl=localClient
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: I[2023-05-16|06:17:19.822] service start                                module=abci-client connection=mempool msg="Starting localClient service" impl=localClient
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: I[2023-05-16|06:17:19.822] service start                                module=abci-client connection=consensus msg="Starting localClient service" impl=localClient
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: I[2023-05-16|06:17:19.822] service start                                module=events msg="Starting EventBus service" impl=EventBus
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: I[2023-05-16|06:17:19.822] service start                                module=pubsub msg="Starting PubSub service" impl=PubSub
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: I[2023-05-16|06:17:19.880] service start                                module=txindex msg="Starting IndexerService service" impl=IndexerService
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: I[2023-05-16|06:17:19.880] ABCI Handshake App Info                      module=consensus height=1765025 hash=B0EACECC7730FA1D7076FADC44602228564496B27BF03AB3B58E783DF6FF170A software-version=1.0.0-beta2 protocol-version=0
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: I[2023-05-16|06:17:19.880] ABCI Replay Blocks                           module=consensus appHeight=1765025 storeHeight=1765026 stateHeight=1765025
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: I[2023-05-16|06:17:19.880] Replay last block using real app             module=consensus
**May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: panic: invalid chain-id on BeginBlock; expected: paloma-test-15, got: paloma-testnet-15**
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: goroutine 11 [running]:
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc0011d5dc0, 0x20, 0x20}, {{0xb, 0x0}, {0xc001449728, 0x11}, 0x1aeea2, {0x1739bbe1, ...}, ...}, ...})
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]:         /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.1/baseapp/abci.go:154 +0xb28
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: github.com/cometbft/cometbft/abci/client.(*localClient).BeginBlockSync(_, {{0xc0011d5dc0, 0x20, 0x20}, {{0xb, 0x0}, {0xc001449728, 0x11}, 0x1aeea2, {0x1739bbe1, ...}, ...}, ...})
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]:         /root/go/pkg/mod/github.com/cometbft/cometbft@v0.37.0/abci/client/local_client.go:283 +0x118
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: github.com/cometbft/cometbft/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc0011d5dc0, 0x20, 0x20}, {{0xb, 0x0}, {0xc001449728, 0x11}, 0x1aeea2, {0x1739bbe1, ...}, ...}, ...})
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]:         /root/go/pkg/mod/github.com/cometbft/cometbft@v0.37.0/proxy/app_conn.go:101 +0x135
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: github.com/cometbft/cometbft/state.execBlockOnProxyApp({0x361b8e0?, 0xc0001a64e0}, {0x362cfc0, 0xc00034e3d8}, 0xc000b870e0, {0x36321c0, 0xc000136fc0}, 0x1aeea1?)
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]:         /root/go/pkg/mod/github.com/cometbft/cometbft@v0.37.0/state/execution.go:363 +0x3e3
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: github.com/cometbft/cometbft/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc002e16820, 0x7}}, {0xc001449098, 0x11}, 0x1, 0x1aeea1, {{0xc001188480, ...}, ...}, ...}, ...)
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]:         /root/go/pkg/mod/github.com/cometbft/cometbft@v0.37.0/state/execution.go:197 +0x151
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: github.com/cometbft/cometbft/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc002e16820, 0x7}}, {0xc001449098, 0x11}, 0x1, 0x1aeea1, {{0xc001188480, ...}, ...}, ...}, ...)
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]:         /root/go/pkg/mod/github.com/cometbft/cometbft@v0.37.0/consensus/replay.go:503 +0x217
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: github.com/cometbft/cometbft/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc002e16820, 0x7}}, {0xc001449098, 0x11}, 0x1, 0x1aeea1, {{0xc001188480, ...}, ...}, ...}, ...)
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]:         /root/go/pkg/mod/github.com/cometbft/cometbft@v0.37.0/consensus/replay.go:416 +0x713
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: github.com/cometbft/cometbft/consensus.(*Handshaker).Handshake(0xc00066bdb0, {0x36348a0, 0xc0004e2700})
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]:         /root/go/pkg/mod/github.com/cometbft/cometbft@v0.37.0/consensus/replay.go:268 +0x3ca
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: github.com/cometbft/cometbft/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc002e16820, 0x7}}, {0xc001449098, 0x11}, 0x1, 0x1aeea1, ...}, ...)
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]:         /root/go/pkg/mod/github.com/cometbft/cometbft@v0.37.0/node/node.go:328 +0x198
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: github.com/cometbft/cometbft/node.NewNode(0xc000bd1340, {0x36039f0, 0xc000bac780}, 0xc000f095a0, {0x35f37a0, 0xc001208d38}, 0x1?, 0x4ca8a98?, 0xc000f09790, {0x361b8e0, ...}, ...)
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]:         /root/go/pkg/mod/github.com/cometbft/cometbft@v0.37.0/node/node.go:778 +0x56d
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x3632dc0, 0xc000c18bd0}, 0x0, {0xc00041deb0, 0xe}, {0x363dc00, ...}, ...}, ...)
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]:         /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.1/server/start.go:315 +0x76f
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: github.com/cosmos/cosmos-sdk/server.StartCmd.func2.2()
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]:         /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.1/server/start.go:151 +0x58
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: github.com/cosmos/cosmos-sdk/server.wrapCPUProfile.func2()
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]:         /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.1/server/start.go:551 +0x29
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]: created by github.com/cosmos/cosmos-sdk/server.wrapCPUProfile
May 16 06:17:19 Ubuntu-2004-focal-64-minimal-hwe palomad[15850]:         /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.1/server/start.go:550 +0x24a

**Comment by kinrokinro** [comment]
@alipostaci2001 replace your genesis with a valid one:
```
wget -O ~/.paloma/config/genesis.json https://raw.githubusercontent.com/palomachain/testnet/master/paloma-testnet-15/genesis.json
```

**Comment by taariq** [comment]
Closing for now as related to old genesis issue.
