### ISSUE TITLE
Docker support for running our chain locally

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#85]
# Background

Should be done before going to a closed alpha testing. This is something that's going to make local testing easier.

# Done when

TODO

- [x] a dockerfile for paloma
- [x] a dockerfile for sparrow
- [x] compose files for running the chain in the local-dev mode
- [x] compose files for running the chain in the local-testnet mode

**Comment by taariq** [comment]
@Vizualni will you document the blocker issues for you. Jehan has offered to take a look.
