### ISSUE TITLE
A fix suggestion

### ISSUE THREAD

**Issue by KyErgus** [palomachain/paloma#850]
# What is happening?
- When wallets are not connected in palomaswap.com application, while Curve is selected, when choosing chain, it gives a wallet connection warning. but there is no such warning for other Dexler.

- Detailed demonstration is available in the video below.

- https://www.dropbox.com/s/si681t18sg4fwi6/REC-20230521142807.mp4?dl=0

**Comment by taariq** [comment]
Confirmed received and assigned to @verabehr

**Comment by taariq** [comment]
@verabehr do we have a status on this?

**Comment by verabehr** [comment]
@taariq moved to the Palomaboard for @wdev733 's queue

**Comment by verabehr** [comment]
this was fixed
