### ISSUE TITLE
[PLACEHOLDER] Closed alpha testing prepare

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#86]
# Background

A big ticket! This is a placeholder ticket that will include things that we need to do for the private alpha testing.

# Done when

- [ ] a list of items, when checked, this ticket should be considered to be finished

**Comment by Vizualni** [comment]
@taariq This ticket was originally made for the original testnet that we planned on doing in mid of June

**Comment by taariq** [comment]
@Vizualni given this is for the June testnet, what due date should this ticket be? 05/27 or something further out?
