### ISSUE TITLE
bug: palomad has peer issue after upgrading to v1.1.0

### ISSUE THREAD

**Issue by DasRasyo** [palomachain/paloma#862]
After upgrading palomad v1.1.0 i had peer issue. Downgraded to v1.1.0 and looks ok. Here you can see v1.1.0 logs(palomad)

https://gist.github.com/DasRasyo/82ca2a435823caf3e2f44f35ead09b5b

**Comment by taariq** [comment]
Discord Commentary: https://discord.com/channels/987730379182051408/1072137820405235762/1112073207420289064.

**Comment by taariq** [comment]
Closing. This is a semver rules issue. We need to upgrade via proposal for major number upgrades.
