### ISSUE TITLE
BNB error 

### ISSUE THREAD

**Issue by ERNcrypto** [palomachain/paloma#863]
Started Pigeon daemon.
*coo! coo!*
time="2023-05-28T13:44:23Z" level=info msg="app info" PID=20985 commit=c553070bd4686c4fe1d5500cf21d00527be2c310 version=v1.0.0
time="2023-05-28T13:44:23Z" level=info msg="Starting healthcheck server"
time="2023-05-28T13:44:23Z" level=info msg="paloma detected being online. Sleeping for 5 seconds to give it time to properly start."
time="2023-05-28T13:44:28Z" level=info msg="validator is staking"
time="2023-05-28T13:44:28Z" level=info msg="starting relayer"
time="2023-05-28T13:44:28Z" level=info msg="relayer loop"
time="2023-05-28T13:44:28Z" level=error msg="error while trying to process messages" error="base error: base error: missing chain config\nwrapped error: unrecoverable error\nwrapped error: reference chain id: bnb-main"

**Comment by taariq** [comment]
Thanks @ERNcrypto . Please also complete the following details:

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

{WRITE YOUR ANSWER HERE}

**Comment by ERNcrypto** [comment]
> 
pigeon version
App version: v1.0.0
Build commit hash: c553070bd4686c4fe1d5500cf21d00527be2c310

palomad version
1.0.0

sudo journalctl -u pigeond -f --no-hostname -o cat
time="2023-05-28T15:12:08Z" level=info msg="relayer loop"
time="2023-05-28T15:12:08Z" level=error msg="couldn't build processors to update external chain info" err="base error: base error: missing chain config\nwrapped error: unrecoverable error\nwrapped error: reference chain id: bnb-main"
time="2023-05-28T15:12:08Z" level=error msg="error while trying to process messages" error="base error: base error: missing chain config\nwrapped error: unrecoverable error\nwrapped error: reference chain id: bnb-main"
time="2023-05-28T15:12:25Z" level=error msg="error while trying to keep pigeon alive" error="rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: validator palomavaloper1am3k7czusdcewv55nhaugu2drn38af9464n65p cannot be a pigeon: validator is jailed [cosmos/cosmos-sdk@v0.47.1/baseapp/baseapp.go:792] With gas wanted: '18446744073709551615' and gas used: '29886' : unknown request"
time="2023-05-28T15:12:55Z" level=error msg="error while trying to keep pigeon alive" error="rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: validator palomavaloper1am3k7czusdcewv55nhaugu2drn38af9464n65p cannot be a pigeon: validator is jailed [cosmos/cosmos-sdk@v0.47.1/baseapp/baseapp.go:792] With gas wanted: '18446744073709551615' and gas used: '29886' : unknown request"
time="2023-05-28T15:13:08Z" level=info msg="relayer loop"
time="2023-05-28T15:13:08Z" level=error msg="couldn't build processors to update external chain info" err="base error: base error: missing chain config\nwrapped error: unrecoverable error\nwrapped error: reference chain id: bnb-main"
time="2023-05-28T15:13:08Z" level=error msg="error while trying to process messages" error="base error: base error: missing chain config\nwrapped error: unrecoverable error\nwrapped error: reference chain id: bnb-main"
time="2023-05-28T15:13:25Z" level=error msg="error while trying to keep pigeon alive" error="rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: validator palomavaloper1am3k7czusdcewv55nhaugu2drn38af9464n65p cannot be a pigeon: validator is jailed [cosmos/cosmos-sdk@v0.47.1/baseapp/baseapp.go:792] With gas wanted: '18446744073709551615' and gas used: '29886' : unknown request"
time="2023-05-28T15:13:55Z" level=error msg="error while trying to keep pigeon alive" error="rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: validator palomavaloper1am3k7czusdcewv55nhaugu2drn38af9464n65p cannot be a pigeon: validator is jailed [cosmos/cosmos-sdk@v0.47.1/baseapp/baseapp.go:792] With gas wanted: '18446744073709551615' and gas used: '29886' : unknown request"
time="2023-05-28T15:14:08Z" level=info msg="relayer loop"
time="2023-05-28T15:14:08Z" level=error msg="couldn't build processors to update external chain info" err="base error: base error: missing chain config\nwrapped error: unrecoverable error\nwrapped error: reference chain id: bnb-main"
time="2023-05-28T15:14:08Z" level=error msg="error while trying to process messages" error="base error: base error: missing chain config\nwrapped error: unrecoverable error\nwrapped error: reference chain id: bnb-main"


I[2023-05-28|15:14:33.005] executed block                               module=state height=1662996 num_valid_txs=3 num_invalid_txs=0
I[2023-05-28|15:14:33.016] commit synced                                module=server commit=436F6D6D697449447B5B31323820343020323437203138382031323420313838203139352031383620313536203230203132342031313120313534203133362031373820313832203133362031333120383520323230203937203230203832203136312031373620313439203233342038302031362032333620323135203233355D3A3139363031347D
I[2023-05-28|15:14:33.016] committed state                              module=state height=1662996 num_txs=3 app_hash=8028F7BC7CBCC3BA9C147C6F9A88B2B6888355DC611452A1B095EA5010ECD7EB
I[2023-05-28|15:14:33.019] indexed block exents                         module=txindex height=1662996
I[2023-05-28|15:14:33.401] Ensure peers                                 module=pex numOutPeers=10 numInPeers=0 numDialing=0 numToDial=0
I[2023-05-28|15:14:37.978] Timed out                                    module=consensus dur=4.959538733s height=1662997 round=0 step=RoundStepNewHeight
I[2023-05-28|15:14:38.130] received proposal                            module=consensus proposal="Proposal{1662997/0 (03D93000AA8AB387431FCE953DD883E648B936CC7FFA19FABA246EBD047BCDD4:1:E1C8656C4327, -1) B0240D567E54 @ 2023-05-28T15:14:37.89882994Z}"
I[2023-05-28|15:14:38.131] received complete proposal block             module=consensus height=1662997 hash=03D93000AA8AB387431FCE953DD883E648B936CC7FFA19FABA246EBD047BCDD4
I[2023-05-28|15:14:38.585] finalizing commit of block                   module=consensus height=1662997 hash=03D93000AA8AB387431FCE953DD883E648B936CC7FFA19FABA246EBD047BCDD4 root=8028F7BC7CBCC3BA9C147C6F9A88B2B6888355DC611452A1B095EA5010ECD7EB num_txs=8
I[2023-05-28|15:14:38.599] minted coins from module account             module=x/bank amount=30468534ugrain from=mint
I[2023-05-28|15:14:38.620] abci-validator-size                          module=x/palomaconsensus 0=(MISSING)
I[2023-05-28|15:14:38.621] trying to deploy smart contract to EVM chain module=x/evm smart-contract-id=1 chain-reference-id=bnb-main
I[2023-05-28|15:14:38.621] deploying smart contracts actually           module=x/evm smart-contract-id=1 chain-reference-id=bnb-main
E[2023-05-28|15:14:38.621] error adding a message to deploy smart contract to chain module=x/evm chain-reference-id=bnb-main smart-contract-id=1 err="invalid character '\\\\' looking for beginning of object key string"
I[2023-05-28|15:14:38.621] trying to deploy smart contract to EVM chain module=x/evm smart-contract-id=1 chain-reference-id=eth-main
I[2023-05-28|15:14:38.621] deploying smart contracts actually           module=x/evm smart-contract-id=1 chain-reference-id=eth-main
E[2023-05-28|15:14:38.621] error adding a message to deploy smart contract to chain module=x/evm chain-reference-id=eth-main smart-contract-id=1 err="invalid character '\\\\' looking for beginning of object key string"
E[2023-05-28|15:14:38.621] error while trying to deploy smart contract to all chains module=x/evm err="there are 2 errors in the group:\nerror  1: invalid character '\\\\' looking for beginning of object key string\nerror  2: invalid character '\\\\' looking for beginning of object key string\n" smart-contract-id=1
I[2023-05-28|15:14:38.621] executed block                               module=state height=1662997 num_valid_txs=8 num_invalid_txs=0
I[2023-05-28|15:14:38.639] commit synced                                module=server commit=436F6D6D697449447B5B393120393520313131203230342039322033372031332031353120363620313734203139203232342038203230352039302034312032333420353920332036382032303720383020363420323331203134332031323420323533203137332031353220313430203235203132365D3A3139363031357D
I[2023-05-28|15:14:38.639] committed state                              module=state height=1662997 num_txs=8 app_hash=5B5F6FCC5C250D9742AE13E008CD5A29EA3B0344CF5040E78F7CFDAD988C197E
I[2023-05-28|15:14:38.643] indexed block exents                         module=txindex height=1662997
I[2023-05-28|15:14:43.578] Timed out                                    module=consensus dur=4.935987037s height=1662998 round=0 step=RoundStepNewHeight
I[2023-05-28|15:14:43.809] received proposal                            module=consensus proposal="Proposal{1662998/0 (7C4977461153F7C7C6D6054DDE18E2D290D0B79941CD7350BF22C93FBD280237:1:EAEE0E7A430B, -1) 7A501B10D022 @ 2023-05-28T15:14:43.60698947Z}"
I[2023-05-28|15:14:43.813] received complete proposal block             module=consensus height=1662998 hash=7C4977461153F7C7C6D6054DDE18E2D290D0B79941CD7350BF22C93FBD280237
I[2023-05-28|15:14:44.246] finalizing commit of block                   module=consensus height=1662998 hash=7C4977461153F7C7C6D6054DDE18E2D290D0B79941CD7350BF22C93FBD280237 root=5B5F6FCC5C250D9742AE13E008CD5A29EA3B0344CF5040E78F7CFDAD988C197E num_txs=6
I[2023-05-28|15:14:44.258] minted coins from module account             module=x/bank amount=30468539ugrain from=mint
I[2023-05-28|15:14:44.279] abci-validator-size                          module=x/palomaconsensus 0=(MISSING)
I[2023-05-28|15:14:44.280] trying to deploy smart contract to EVM chain module=x/evm smart-contract-id=1 chain-reference-id=bnb-main
I[2023-05-28|15:14:44.280] deploying smart contracts actually           module=x/evm smart-contract-id=1 chain-reference-id=bnb-main
E[2023-05-28|15:14:44.280] error adding a message to deploy smart contract to chain module=x/evm chain-reference-id=bnb-main smart-contract-id=1 err="invalid character '\\\\' looking for beginning of object key string"
I[2023-05-28|15:14:44.280] trying to deploy smart contract to EVM chain module=x/evm smart-contract-id=1 chain-reference-id=eth-main
I[2023-05-28|15:14:44.280] deploying smart contracts actually           module=x/evm smart-contract-id=1 chain-reference-id=eth-main
E[2023-05-28|15:14:44.280] error adding a message to deploy smart contract to chain module=x/evm chain-reference-id=eth-main smart-contract-id=1 err="invalid character '\\\\' looking for beginning of object key string"
E[2023-05-28|15:14:44.280] error while trying to deploy smart contract to all chains module=x/evm err="there are 2 errors in the group:\nerror  1: invalid character '\\\\' looking for beginning of object key string\nerror  2: invalid character '\\\\' looking for beginning of object key string\n" smart-contract-id=1
I[2023-05-28|15:14:44.280] executed block                               module=state height=1662998 num_valid_txs=5 num_invalid_txs=1
I[2023-05-28|15:14:44.295] commit synced                                module=server commit=436F6D6D697449447B5B353920313030203130302031313620353020363220323230203831203132372032303020313238203437203933203235332031382031373220323420313334203820313431203935203131342034362032343120343320313520323038203130332031323420323339203135302036345D3A3139363031367D
I[2023-05-28|15:14:44.295] committed state                              module=state height=1662998 num_txs=6 app_hash=3B646474323EDC517FC8802F5DFD12AC1886088D5F722EF12B0FD0677CEF9640
I[2023-05-28|15:14:44.300] indexed block exents                         module=txindex height=1662998
I[2023-05-28|15:14:49.238] Timed out                                    module=consensus dur=4.940030084s height=1662999 round=0 step=RoundStepNewHeight
I[2023-05-28|15:14:49.469] received proposal                            module=consensus proposal="Proposal{1662999/0 (5C573E08DEA0DDC837B26253C796CD017C2AC528AB63E20B95049BC2034CB0F3:1:575128929705, -1) 18795455BA58 @ 2023-05-28T15:14:49.252130162Z}"
I[2023-05-28|15:14:49.469] received complete proposal block             module=consensus height=1662999 hash=5C573E08DEA0DDC837B26253C796CD017C2AC528AB63E20B95049BC2034CB0F3
I[2023-05-28|15:14:49.916] finalizing commit of block                   module=consensus height=1662999 hash=5C573E08DEA0DDC837B26253C796CD017C2AC528AB63E20B95049BC2034CB0F3 root=3B646474323EDC517FC8802F5DFD12AC1886088D5F722EF12B0FD0677CEF9640 num_txs=9
I[2023-05-28|15:14:49.925] minted coins from module account             module=x/bank amount=30468544ugrain from=mint
I[2023-05-28|15:14:49.943] abci-validator-size                          module=x/palomaconsensus 0=(MISSING)
I[2023-05-28|15:14:49.943] trying to deploy smart contract to EVM chain module=x/evm smart-contract-id=1 chain-reference-id=bnb-main
I[2023-05-28|15:14:49.944] deploying smart contracts actually           module=x/evm smart-contract-id=1 chain-reference-id=bnb-main
E[2023-05-28|15:14:49.944] error adding a message to deploy smart contract to chain module=x/evm chain-reference-id=bnb-main smart-contract-id=1 err="invalid character '\\\\' looking for beginning of object key string"
I[2023-05-28|15:14:49.944] trying to deploy smart contract to EVM chain module=x/evm smart-contract-id=1 chain-reference-id=eth-main
I[2023-05-28|15:14:49.944] deploying smart contracts actually           module=x/evm smart-contract-id=1 chain-reference-id=eth-main
E[2023-05-28|15:14:49.944] error adding a message to deploy smart contract to chain module=x/evm chain-reference-id=eth-main smart-contract-id=1 err="invalid character '\\\\' looking for beginning of object key string"
E[2023-05-28|15:14:49.944] error while trying to deploy smart contract to all chains module=x/evm err="there are 2 errors in the group:\nerror  1: invalid character '\\\\' looking for beginning of object key string\nerror  2: invalid character '\\\\' looking for beginning of object key string\n" smart-contract-id=1
I[2023-05-28|15:14:49.944] executed block                               module=state height=1662999 num_valid_txs=9 num_invalid_txs=0
I[2023-05-28|15:14:49.958] commit synced                                module=server commit=436F6D6D697449447B5B31353220313230203434203132332032313920313820323131203337203231302032323020313937203130203230362037203231312032333220313333203336203231362031373420393420313137203231312032323720323533203131302035203234203133322031303420313333203231315D3A3139363031377D
I[2023-05-28|15:14:49.958] committed state                              module=state height=1662999 num_txs=9 app_hash=98782C7BDB12D325D2DCC50ACE07D3E88524D8AE5E75D3E3FD6E0518846885D3
I[2023-05-28|15:14:49.962] indexed block exents                         module=txindex height=1662999

**Comment by verabehr** [comment]
@ERNcrypto will you please double check your `~/.pigeon/config.yaml` and your `~/.pigeon/env.sh` files. Pigeon is complaining that it doesn't have the config for bnb chain, so something might be missing or incorrect in either of these files

**Comment by ERNcrypto** [comment]
> @ERNcrypto will you please double check your `~/.pigeon/config.yaml` and your `~/.pigeon/env.sh` files. Pigeon is complaining that it doesn't have the config for bnb chain, so something might be missing or incorrect in either of these files

loop-timeout: 5s
health-check-port: 5757

paloma:
  chain-id: messenger
  call-timeout: 20s
  keyring-dir: ~/.paloma
  keyring-pass-env-name: PALOMA_PASSWORD
  keyring-type: os
  signing-key: wallet
  base-rpc-url: http://localhost:26657
  gas-adjustment: 1.5
  gas-prices: 0.001ugrain
  account-prefix: paloma

evm:
  eth-main:
    chain-id: 1
    base-rpc-url: ${ETH_RPC_URL}
    keyring-pass-env-name: "ETH_PASSWORD"
    signing-key: ${ETH_SIGNING_KEY}
    keyring-dir: ~/.pigeon/keys/evm/eth-main
    gas-adjustment: 1.9
    tx-type: 2
bnb-main:
    chain-id: 56
    base-rpc-url: https://snowy-bitter-dawn.bsc.discover.quiknode.pro/cf8b9aa75064c8fdc.../
    keyring-pass-env-name: "BNB_PASSWORD"
    signing-key: ${BNB_SIGNING_KEY}
    keyring-dir: ~/.pigeon/keys/evm/bnb-main
    gas-adjustment: 1.2
    tx-type: 0

**Comment by taariq** [comment]
This will be fixed in the coming updates.
