### ISSUE TITLE
[PLACEHOLDER] [BIG TICKET] Attestation module

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#87]
# Background

Just a placeholder ticket which will be broken many smaller tickets.

Should remove #84 when this is done

# Done when

- [ ] a list of items, when checked, this ticket should be considered to be finished

**Comment by verabehr** [comment]
requires work on Paloma, Sparrow and possibly on Turnstone as well

**Comment by Vizualni** [comment]
This was done.
