### ISSUE TITLE
BUG: msg="not found" and "couldn't build processors to update external chain info" err="not found before jail

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#939]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Validator https://paloma.explorers.guru/validator/palomavaloper1tdw23fpnxh2uk3djtteh7eaydymrfgnaepkpkz keeps entering jail with the errors:
```
Aug 04 09:56:28 Ubuntu-2004-focal-64-minimal-hwe pigeon[3479406]: time="2023-08-04T09:56:28+02:00" level=info msg="checking if validator is staking"
Aug 04 09:56:28 Ubuntu-2004-focal-64-minimal-hwe pigeon[3479406]: time="2023-08-04T09:56:28+02:00" level=info msg="validator is staking"
Aug 04 09:56:28 Ubuntu-2004-focal-64-minimal-hwe pigeon[3479406]: time="2023-08-04T09:56:28+02:00" level=error msg="not found"
Aug 04 09:56:28 Ubuntu-2004-focal-64-minimal-hwe pigeon[3479406]: time="2023-08-04T09:56:28+02:00" level=info msg="attester loop"
Aug 04 09:56:29 Ubuntu-2004-focal-64-minimal-hwe pigeon[3479406]: time="2023-08-04T09:56:29+02:00" level=error msg="not found"
Aug 04 09:56:29 Ubuntu-2004-focal-64-minimal-hwe pigeon[3479406]: time="2023-08-04T09:56:29+02:00" level=info msg="relayer loop"
Aug 04 09:56:29 Ubuntu-2004-focal-64-minimal-hwe pigeon[3479406]: time="2023-08-04T09:56:29+02:00" level=error msg="not found"
Aug 04 09:56:29 Ubuntu-2004-focal-64-minimal-hwe pigeon[3479406]: time="2023-08-04T09:56:29+02:00" level=error msg="not found"
Aug 04 09:56:29 Ubuntu-2004-focal-64-minimal-hwe pigeon[3479406]: time="2023-08-04T09:56:29+02:00" level=info msg="signer loop"
Aug 04 09:56:30 Ubuntu-2004-focal-64-minimal-hwe pigeon[3479406]: time="2023-08-04T09:56:30+02:00" level=error msg="couldn't build processors to update external chain info" err="not found"
Aug 04 09:56:30 Ubuntu-2004-focal-64-minimal-hwe pigeon[3479406]: time="2023-08-04T09:56:30+02:00" level=error msg="not found"
Aug 04 09:56:30 Ubuntu-2004-focal-64-minimal-hwe pigeon[3479406]: time="2023-08-04T09:56:30+02:00" level=error msg="not found"
Aug 04 09:56:30 Ubuntu-2004-focal-64-minimal-hwe pigeon[3479406]: time="2023-08-04T09:56:30+02:00" level=info msg="attester loop"
Aug 04 09:56:31 Ubuntu-2004-focal-64-minimal-hwe pigeon[3479406]: time="2023-08-04T09:56:31+02:00" level=error msg="not found"
```

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

Paloma v1.6.1
Pigeon 1.5.2

Logs: https://gist.github.com/D-Elektra/55f28d2a041d80fcaf90059bd6a1f45b

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

No able to reproduce

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

attestor and relayers are found?

**Comment by taariq** [comment]
@ToasterTheBrave this pigeon is using our bnb ednpoint, but still ending again in jail. I think this might be a diff issue.

1. The attestation message is not getting into a block. Is it because the validator key is now overloading signing too many messages

```
time="2023-08-04T23:05:47Z" level=info msg="validator is staking"
time="2023-08-04T23:05:49Z" level=error msg="error attesting messages" action=attest error="there are 1 errors in the group:\nerror  1: timed out after: 60000000000; timed out after waiting for tx to get included i>time="2023-08-04T23:05:49Z" level=error msg="error returned in process loop" err="there are 1 errors in the group:\nerror  1: timed out after: 60000000000; timed out after waiting for tx to get included in the bloc>time="2023-08-04T23:05:49Z" level=info msg="attester loop"
```

**Comment by taariq** [comment]
curl -s localhost:$PALOMA_RPC_LADDR_PORT/unconfirmed_txs | jq .result
{
  "n_txs": "3",
  "total": "3",
  "total_bytes": "1674",
  "txs": [
    "CpYECpMECj4vcGFsb21hY2hhaW4ucGFsb21hLnZhbHNldC5Nc2dBZGRFeHRlcm5hbENoYWluSW5mb0ZvclZhbGlkYXRvchLQAwotcGFsb21hMWM4dXhra3owMHFuOTd3c3A5dW04eTNhOHdsbXJ2M2M1NjI5anJuElEKA2V2bRIIYm5iLW1haW4aKjB4RWUyMTMwMWFGMWQ5NTYyQjVjQkVkZjUyMDA3N0VhMGE5YkM5ZDUzNSIU7iEwGvHZVitcvt9SAHfqCpvJ1TUSUQoDZXZtEghldGgtbWFpbhoqMHhFZTIxMzAxYUYxZDk1NjJCNWNCRWRmNTIwMDc3RWEwYTliQzlkNTM1IhTuITAa8dlWK1y+31IAd+oKm8nVNRJSCgNldm0SCWthdmEtbWFpbhoqMHhFZTIxMzAxYUYxZDk1NjJCNWNCRWRmNTIwMDc3RWEwYTliQzlkNTM1IhTuITAa8dlWK1y+31IAd+oKm8nVNRJTCgNldm0SCm1hdGljLW1haW4aKjB4RWUyMTMwMWFGMWQ5NTYyQjVjQkVkZjUyMDA3N0VhMGE5YkM5ZDUzNSIU7iEwGvHZVitcvt9SAHfqCpvJ1TUSUAoDZXZtEgdvcC1tYWluGioweEVlMjEzMDFhRjFkOTU2MkI1Y0JFZGY1MjAwNzdFYTBhOWJDOWQ1MzUiFO4hMBrx2VYrXL7fUgB36gqbydU1EmkKUgpGCh8vY29zbW9zLmNyeXB0by5zZWNwMjU2azEuUHViS2V5EiMKIQKp8N8JyrNcZETvX6BrkRiq/nwHNhhoertylyTY7q2p0BIECgIIARjzrAsSEwoNCgZ1Z3JhaW4SAzE4ORCVwQsaQEQbr3MevjKxVua/S/5p3idnPcTP3JjdzgBAP8mHsVG0Z98SDTvGgrfvQs8H1wI0R8ZfAevlpbw8mhitk9ctoIs=",
    "Cl4KXAoiL2Nvc21vcy5zbGFzaGluZy52MWJldGExLk1zZ1VuamFpbBI2CjRwYWxvbWF2YWxvcGVyMW5sd3pjZWdtN2t4ZzZycG1rcW1wbDNhZnZhcGt5cDRtc2w3Z3dnEloKUgpGCh8vY29zbW9zLmNyeXB0by5zZWNwMjU2azEuUHViS2V5EiMKIQK7uZ5/+joNKkQPJa1BR0oeERyydBnwBHmjS8Mm32jsrBIECgIIARjP2gUSBBCgwh4aQBa4OjsiHsdUQAgGEDT6BqdvG4fp+Cjz49Zek76KB3iEc1D0bZxu+mKXQkPzL2f6GRd1or6f35Hc/XlVkWVVISw=",
    "CpYECpMECj4vcGFsb21hY2hhaW4ucGFsb21hLnZhbHNldC5Nc2dBZGRFeHRlcm5hbENoYWluSW5mb0ZvclZhbGlkYXRvchLQAwotcGFsb21hMXN3YTVrY2Y5Y2w1ZHgyeXB4MGM1cjllNXFkZm56cDl3cTU5ejJsElEKA2V2bRIIYm5iLW1haW4aKjB4MTlmNTkxMUU0Y0E2OUUzMDQ0OWFENkJCNzFEZTM0MUYwMUYxMThCQiIUGfWRHkymnjBEmta7cd40HwHxGLsSUQoDZXZtEghldGgtbWFpbhoqMHgxOWY1OTExRTRjQTY5RTMwNDQ5YUQ2QkI3MURlMzQxRjAxRjExOEJCIhQZ9ZEeTKaeMESa1rtx3jQfAfEYuxJSCgNldm0SCWthdmEtbWFpbhoqMHgxOWY1OTExRTRjQTY5RTMwNDQ5YUQ2QkI3MURlMzQxRjAxRjExOEJCIhQZ9ZEeTKaeMESa1rtx3jQfAfEYuxJTCgNldm0SCm1hdGljLW1haW4aKjB4MTlmNTkxMUU0Y0E2OUUzMDQ0OWFENkJCNzFEZTM0MUYwMUYxMThCQiIUGfWRHkymnjBEmta7cd40HwHxGLsSUAoDZXZtEgdvcC1tYWluGioweDE5ZjU5MTFFNGNBNjlFMzA0NDlhRDZCQjcxRGUzNDFGMDFGMTE4QkIiFBn1kR5Mpp4wRJrWu3HeNB8B8Ri7EmkKUgpGCh8vY29zbW9zLmNyeXB0by5zZWNwMjU2azEuUHViS2V5EiMKIQLjUKkO0Ac2o30MJ0NmUb7hGmVVuaptRTDcL7Eci4HOmRIECgIIARio0gwSEwoNCgZ1Z3JhaW4SAzE5NxD0sA8aQJDXCKD+fXp+Yw/TyyDCqmaD4sMUZcViZWV7kXCFsCPxGKVhx1IZPktUWBjcEfF0D3Wbp+azgwCupS+35mum3WI="
  ]
}

**Comment by taariq** [comment]
The mempool only has 3 txes
It's not full.

**Comment by taariq** [comment]
time="2023-08-04T23:57:29Z" level=error msg="couldn't broadcast signatures and process attestation" action=sign error="timed out after: 60000000000; timed out after waiting for tx to get included in the block" message-ids="[54073 54074 54075]" messages-to-sign="[54073 54074 54075]" queue-name=evm/eth-main/evm-turnstone-message signed-messages="[map[id:54073] map[id:54074] map[id:54075]]"
time="2023-08-04T23:57:29Z" level=error msg="error returned in process loop" err="timed out after: 60000000000; timed out after waiting for tx to get included in the block"

**Comment by byte-bandit** [comment]
I'm not convinced it's the root cause here, but every time I have come across the `not found` error in this context, it was related to endpoint configuration (namely POKT for kava). It might be helpful to confirm with the validator which endpoint provider is being used.
