### ISSUE TITLE
Turnstone setup, deposit and withdrawal

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#96]
# Background

Epic: https://www.notion.so/volumefi/EPIC-05-06-Paloma-s-smart-contract-3d91b9a340d24d6ea5e5030dcc9efcf7

# Done when

## Initial setup

- [x] a hello world example of the smart contract is made and it's possible to compile it
- [x] Github actions which are building a project and running tests

## Deposit

- [x] following the epic's structure users can deposit funds and it is associated with the job id that they have provided
- [x] a query endpoint to get the funds in the job id
- [x] a query endpoint to get the customer's funds in total and broken down per job

## Withdrawal

- [x] customers can withdraw their money by following the epic's https://www.notion.so/volumefi/EPIC-05-06-Paloma-s-smart-contract-3d91b9a340d24d6ea5e5030dcc9efcf7 requirements

**Comment by taariq** [comment]
@measure-fi This one is yours now.

**Comment by measure-fi** [comment]
Fixed in https://github.com/palomachain/turnstone/pull/3
