### ISSUE TITLE
[INVESTIGATION] Turnstone - contract migration

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#97]
# Background

Something to keep in mind and we should do this early as we can: https://docs.terra.money/docs/develop/dapp/quick-start/contract-migration.html

# Done when

- [ ] a list of items, when checked, this ticket should be considered to be finished

**Comment by taariq** [comment]
@Vizualni we do not want to practice contract migration as there are several unknowns with contract upgrades. Our posture is that we will deploy new contracts and the user will migrate to the new contract. This is the most reliable method in ETH and I want us to continue to pursue contract replacement, not upgrades or migrations. We cannot trust the chain to migrate and if it fails with billions on it, then that's substantial risk.

**Comment by taariq** [comment]
I would recommend closing this as not needed.

**Comment by Vizualni** [comment]
I see. I'd very much like to keep this open, as I'd like to learn more about this before we go public and keep it as a reminder. I'll add the low priority to this as well. I'd like to learn more about this and try to investigate possible alternatives if we'd ever need to do a migration and see what is the best approach for us and the people involved.

**Comment by Vizualni** [comment]
Closing this as it's not relevant right now.
