### ISSUE TITLE
bug: suspicious increase in ethereum RPC requests and eth_getLogs errors

### ISSUE THREAD

**Issue by k4b3z4** [palomachain/paloma#976]
# suspicious increase in ethereum RPC requests and eth_getLogs errors

![image](https://github.com/palomachain/paloma/assets/1950436/d7bb0aee-bdea-4b07-94f0-8b78d128fa56)

![image](https://github.com/palomachain/paloma/assets/1950436/c6fbc176-7f90-4212-bec6-303abf2949a6)

**Comment by taariq** [comment]
@k4b3z4 what version of Compass and Pigeon are u using?

**Comment by taariq** [comment]
@k4b3z4 will you share output of the actual calls and their numbers?

**Comment by k4b3z4** [comment]
> @k4b3z4 what version of Compass and Pigeon are u using?

paloma@testnet:~$ pigeon version
App version: v1.8.0
Build commit hash: 5ab6cb5a0cfebaca418f9d0b3eefb1dd2f723e69
paloma@testnet:~$ palomad version
1.8.0

**Comment by k4b3z4** [comment]
[pigeond.log](https://github.com/palomachain/paloma/files/12613448/pigeond.log)

Are the last 2k lines of the log useful or can I find the calls somewhere else?

**Comment by taariq** [comment]
We also need the calls from your RPC provider. The call count.

**Comment by byte-bandit** [comment]
This might have been related to the failing compass EVM deployment to `eth-main`. @k4b3z4 Does this issue still persist or have calls declined again since `9/14` ish?

**Comment by byte-bandit** [comment]
@k4b3z4 

This should be resolved by the next iteration of Pigeon, see: See https://github.com/palomachain/paloma/issues/977
