### ISSUE TITLE
Figure out the gas cost for verifying 20 signatures

### ISSUE THREAD

**Issue by Vizualni** [palomachain/paloma#99]
# Background

As per Jehan's feedback, we should figure out how much gas it cost to verify signatures on Terra. We should use https://docs.rs/cosmwasm-std/latest/cosmwasm_std/trait.Api.html#tymethod.secp256k1_verify and random 20 signatures which we need to verify to figure out the gas cost.
Why 20? Jehan's feedback was that if we were to compare it with other networks, approx 20 validators are holding 2/3 of staking power.

# Done when

- [ ] a new throwaway smart contract which calculates the gas is deployed to terra's mainnet
- [ ] a gas cost is sent over to this github ticket so that we have it written down here as well
- [ ] send it in discord in #paloma chain so that we can have a discussion to see if that's ok

**Comment by measure-fi** [comment]
@taariq @Vizualni `terra1ndlz3aafxg2w34jvvkuglnwzh4pckzl043cl0r`.

**Comment by measure-fi** [comment]
On testnet this uses 185357 gas. Testing on main.

```
☞ wasmd tx wasm execute $CONTRACT '{}' --amount 100upebble --from wallet $TXFLAG -y
gas estimate: 185357
logs: []
raw_log: '[]'
txhash: 3840CD027933AE3BEBC2507B33B2CE8B67170A39DE6E10F2D85E1D821E802F08
```

**Comment by measure-fi** [comment]
And [on mainnet](https://finder.terra.money/mainnet/tx/48B1736F2B21D62D96468113435331CEF4B2F223EF692F2816E7A0A6C36F0ED4):

- Transaction fee: 0.031809 UST
- Gas Used: 116443

**Comment by measure-fi** [comment]
[Thread in #paloma](https://discord.com/channels/902712061182771270/943524017460092978/971477094347456673)

**Comment by measure-fi** [comment]
Slightly better methodology in 

Should probably have done this on testnet instead. In any case trying this
- [with 0 verifications](https://terrasco.pe/mainnet/tx/01DEA1E90F4E5E6D0C377A75CFC016430CDE58AE37C0EBB31FFDF64E6AEBA0E3)
- [with 150 verifications](https://terrasco.pe/mainnet/tx/FA888A204BB67BB95EBF593847C11E3C717E75176191E61A9CDE28204FD70A63)

Gives us the gas amount per signature verification:
```
(247484 - 96036) / 150 = 1010
```
