### ISSUE TITLE
 EVM ticket 

### ISSUE THREAD

**Issue by erkancamli** [palomachain/paloma#991]
I keep getting jailed on mainnet palomavaloper1qf7np0rp3qutvn08vc6qz0y7ffc02cncwdvdtd

Eth: 0x0DAaBB4FF60423Eb1F14cC6731394e098ad51bcb  0.0377
Bnb: 0xf9F9176a96017139ED75F91F047ec11574826304  0.079
Matic: 0x7ab3A897b3B3aEFB55790ade13f4eA1469C7D581  10
OP: 0x5464ece659c78FbE249f6E5Ef763f378D5ADddFe 0,0516
Arb: 0x82407edAE217416408A806027057F8c51D7c7290  0.011
Base: 0xD03CB05a84E6f93453e528940Fa1a8EfdEDaEc34  0.015

**Comment by taariq** [comment]
@erkancamli which versions of Paloma are you running?

**Comment by taariq** [comment]
@erkancamli ah. Wee see the prolem. your ETH balance is below the minimum 0.05 ETH. We'll refund your failed tx.

**Comment by erkancamli** [comment]
> @erkancamli which versions of Paloma are you running?

root@ubuntu-8gb-hel1-1:~# palomad version
1.8.2
root@ubuntu-8gb-hel1-1:~# pigeon version
App version: v1.8.2
Build commit hash: 1a87a3bafaa0e43ec27ca6cb7a6dc7645dd87e9b
root@ubuntu-8gb-hel1-1:~#

**Comment by taariq** [comment]
closing as fixed.
